### PR TITLE
Algebraic solving updates

### LINKED ISSUE #1743: real_solutions does not find real solutions
@ederc Is `real_solution` guaranteed to work or is this just a heuristic answer? In the following example, `precision = 2000` should be plenty of bits for the answer, but it is still wrong.
```
julia> R, (x1, x2) = PolynomialRing(QQ, ["x1", "x2"])
(Multivariate Polynomial Ring in x1, x2 over Rational Field, fmpq_mpoly[x1, x2])

julia> I = ideal(R, [x1 + fmpz(2)^100, x2 + fmpz(2)^100])
ideal(x1 + 1267650600228229401496703205376, x2 + 1267650600228229401496703205376)

julia> real_solutions(I, precision = 2000)[1]
1-element Vector{Vector{fmpq}}:
 [525909043195792924294468720826510030157594067095003457925744730444645184165685841422411472086483389042629938328710035990104663714019990454282490346962201145280253003011761131070166446404767222426736551201364603258293504504353180087089822382167609248221931818500472253181827147579664655709029886763125509418115386014392956304911363626981064761038488849542690257311741845774276006361634326522537936337281623017499898987832769801489157764050590678937690498499212717579345760390961060500199348194447675175249694053882119149293356125122290950450439762719112412932605081326145619151918067782294458618315089421//229626139054850904846566640235536396804463540417739040095528547365153252278474062771331897263301253983689192927797492554689423792172611066285186271233330637078259978290624560001377558296480089742857853980126972489563230927292776727894634052080932707941809993116324797617889259211246623299072328443940665362688337817968917011204758969615828117801869553000858005433413251661044016264472562583522535766634413197990792836254043559716808084319706366503081778867804183841109915567179344078320163914433261165510760851167452031056697572838864109017830551567765250350871057601645685541635930907524369702298058752, -1267650600228229401496703205376]
```

### PR DESCRIPTION
**Pull request by ederc**
Bumps `AlgebraicSolving.jl` to version 0.3.0 which provides `msolve_jll.jl` resp. `msolve` version 0.4.6.

1. Fixes #1743 (adds it also as a test).
2. Adds internal function `_rational_solutions` as discussed in #1744.

Ping: @thofma

### CODE REVIEW

File: test/Rings/solving-test.jl [hunk 1]
```diff
@@ -15,8 +15,13 @@
     @test res[2].param[1] == -1 * p1
     @test res[2].param[2] == -1 * p2
 
+    rat_sols = Vector{fmpq}[[1, 0, 0], [1//3, 0, 1//3]]
+    rat_res = Oscar._rational_solutions(I)
+    @test rat_res == rat_sols
```
Comment (thofma) [inline test/Rings/solving-test.jl]:
```suggestion
    @test length(rat_res) == 2 && issetequal(rat_res, rat_sols)
```
To avoid problems with the ordering.

**Review by thofma — APPROVED** [review]
