### PR TITLE
Fix 1580

### LINKED ISSUE #1580: Bug in affine_cone
**Describe the bug**
Some dispatch ambiguity. Needs #1579 to run the following example. @HechtiDerLachs 
**To Reproduce**
**Describe the bug**
Some dispatch ambiguity. Needs #1579 to run the following example. @HechtiDerLachs 
**To Reproduce**
```   
   R,(x,) = PolynomialRing(GF(3),["x"])
   Rx,i = localization(R, x)
   x = Rx(x)
   P2 = projective_space(Rx, 2)
   affine_cone(P2) # boom
   S = ambient_ring(P2)  
   (s0, s1, s2) = homogeneous_coordinates(P2)
   A = subscheme(P2, [s0+1//x*s1])
   B = subscheme(P2, [x*s0+s1])
   Acone = affine_cone(A)
   Bcone = affine_cone(B)
```

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
This should fix https://github.com/oscar-system/Oscar.jl/issues/1580.

### CODE REVIEW

File: experimental/Schemes/ProjectiveModules.jl [hunk 1]
```diff
@@ -142,32 +142,86 @@ function _is_projective(A::MatElem, X::AbsSpec)
...
-  if check
-    all(x->(x in localized_modulus(parent(a))), gens(modulus(R))) || error("no valid coercion")
-  end
-  (iszero(lifted_numerator(a)) || iszero(numerator(a))) && return zero(R)
-  isone(lifted_denominator(a)) && return R(lifted_numerator(a))
-  ### TODO: divexact is still not implemented for MPolyQuo. 
-  # Once this is done, return to that method.
-  #return R(lift(divexact(numerator(a), denominator(a))))
-  error("`divexact` not implemented for `MPolyQuo`")
+function Localization(A::MPolyLocalizedRing, f::MPolyLocalizedRingElem)
```
Comment (simonbrandhorst) [inline experimental/Schemes/ProjectiveModules.jl:224]: Please add a test.

**Review by simonbrandhorst — CHANGES_REQUESTED** [review]
Looks reasonable and fixes the bug. 
Approved once you add the extra test.

**Comment by HechtiDerLachs** [comment]
Let's see about the code coverage now. I added one test that should do the job.

**Review by simonbrandhorst — APPROVED** [review]
