### PR TITLE
Fix overflows and type stability in hilbert_*

### LINKED ISSUE #573: functions related to hilbert_polynomial use unsafe Int arithmetic and an odd mix of fmpz/fmpq arithmetic
@wdecker For example, we have
https://github.com/oscar-system/Oscar.jl/blob/c6c64dc50951b8a7cfaaee415283b5555e6e9b17/src/Rings/mpoly-affine-algebras.jl#L116-L123
The `binomial` with `(Int, Int)` arguments returns `Int` and apparently throws on overflow, and the `hilbert_function(H, d)` returns `fmpq`. This is bad for the infered return type of this function.

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #573

Previously `factorial` and `binomial` were called with `Int` arguments and could overflow, which is fixed. Also, a bunch of type stability issues were fixed (`@code_warntype` is a great tool to find them).

<s>One remains: `degree` for `HilberData` can return either `fmpz` or `fmpq` -- the latter seems weird. I'll mark the problematic spot in the diff.</s> Nevermind, I think I got it now

### CODE REVIEW

File: src/Rings/mpoly-graded.jl [hunk 1]
```diff
@@ -1573,18 +1569,16 @@ end
...
   P = hilbert_polynomial(H)
-  if P==zero(parent(P))
+  if iszero(P)
      q, _ = hilbert_series(H, 2)
      return q(1)
   end
-  return leading_coefficient(P)*factorial(degree(P))
+  deg = leading_coefficient(P)*factorial(ZZ(degree(P)))
+  @assert isone(denominator(deg))
+  return numerator(deg)
```
Comment (fingolfin) [inline src/Rings/mpoly-graded.jl:1581]: @wdecker please verify this is correct

File: src/Rings/MPolyQuo.jl [hunk 2]
```diff
@@ -28,10 +28,10 @@ function show(io::IO, Q::MPolyQuo)
...
 end
 
-gens(Q::MPolyQuo) = [Q(x) for x = gens(Q.R)]
-ngens(Q::MPolyQuo) = ngens(Q.R)
-gen(Q::MPolyQuo, i::Int) = Q(gen(Q.R, i))
-Base.getindex(Q::MPolyQuo, i::Int) = Q(Q.R[i])
+gens(Q::MPolyQuo) = [Q(x) for x = gens(Q.R)]::Vector{elem_type(Q)}
+ngens(Q::MPolyQuo) = ngens(Q.R)::Int
+gen(Q::MPolyQuo, i::Int) = Q(gen(Q.R, i))::elem_type(Q)
+Base.getindex(Q::MPolyQuo, i::Int) = Q(Q.R[i])::elem_type(Q)
```
Comment (fingolfin) [inline src/Rings/MPolyQuo.jl:34]: This is kind of a bandaid, and e.g. `base_ring` below is not type stable as it is. To fix this "properly", I think we'd need to add another type argument to `MPolyQuo` to record the type of `Q.R`

File: src/Rings/mpoly-affine-algebras.jl [hunk 3]
```diff
@@ -250,7 +248,7 @@ julia> degree(A)
 """
 function degree(A::MPolyQuo)
    if iszero(A.I)
-       return 1
+       return ZZ(1)
```
Comment (fingolfin) [inline src/Rings/mpoly-affine-algebras.jl:251]: Perhaps we think the degree in "realistic" (?? whatever that means?) examples can never overflow an `Int` -- then we could change this back here, but also `degree` for `HilbertData`, called below, ought to be adjusted?

Comment (afkafkafk13) [reply src/Rings/mpoly-affine-algebras.jl:251]: Let me put it this way: If degree would overflow  an int64, then the example would be so large that we would not stand a chance to even reach this point, because something on the way (groebner-basis) would have exhausted our memory anyway.
 (Do not be misled by the multiplication with the d! -- this is not a hack, but a knowledgable and well-controlled canceling of the denomiator already present in mathematical textbooks of the subject.)

File: src/Rings/mpoly-graded.jl (hunk 1 above)
Comment (afkafkafk13) [reply src/Rings/mpoly-graded.jl:1581]: I am not wdecker, but the assertion is correct

**Comment by thofma** [comment]
With many variables it is relatively easy to construct examples where it overflows making `fmpz` necessary?
```
julia> R, (w, x, y, z, u, v) = GradedPolynomialRing(QQ, ["w", "x", "y", "z", "u", "v"]);

julia> A, _ = quo(R, ideal(R, [w^20000, x^20000, y^20000, z^20000, u^20000, v^20000]));

julia> degree(A)
20
```

Compare with Singular:
```
> ring r = 0, (x, y, z, w, u, v), dp;
> ideal i = x^20000, y^20000, z^20000, w^20000, u^20000, v^20000;
> ideal j = std(i);
> vdim(j);
   ? int overflow in vdim
   ? error occurred in or before STDIN line 4: `vdim(j);`
> degree(j);
Singular : signal 11 (v: 4312):
current line:>>degree(j);<<
Segment fault/Bus error occurred at 7fe1a2f25b30 because of 10202 (r:1667122415)
please inform the authors
```

I actually had examples in my research, where Singular was quick to compute a Gröbner basis, but failed computing the degree/dimension of the quotient.

P.S.: Maybe add this as tests?

**Comment by afkafkafk13** [comment]
good point! you can get to the point in the function without computing a standard basis, if your ideal is already a standard basis and knows about it -- like in the monomial case. So we should not guess about 'reasonable', but do it properly.

File: src/Rings/MPolyQuo.jl (hunk 2 above)
Comment (tthsqe12) [reply src/Rings/MPolyQuo.jl:34]: These kind of assertions are all over the place in Singular.jl and AbstractAlgebra.jl. I believe that they are used in place of more type parameters.

**Comment by fingolfin** [comment]
@thofma I could add your example as a test, but it already gives the same result now, so I am not sure it'd prove something here? Or perhaps I am missing something?

**Comment by tthsqe12** [comment]
It looks bad. I think the answer is supposed to be `n^6`.
```
julia> R, (w, x, y, z, u, v) = GradedPolynomialRing(QQ, ["w", "x", "y", "z", "u", "v"]);

julia> for n in (1, 2, 3, 4, 5, 100, 20000)
          A, _ = quo(R, ideal(R, [w^n, x^n, y^n, z^n, u^n, v^n]))
          println(n => degree(A))
       end
1 => 1
2 => 64
3 => 729
4 => 4096
5 => 15625
100 => 1000000000000
20000 => 20
```

**Review by tthsqe12 — COMMENTED** [review]
I will be looking for the overflow bug in thofma's n^6 example above.

**Comment by fingolfin** [comment]
@tthsqe12 ahh of course. I didn't stop to think of what that computation does. yes, it should be `n^6`. So, there's still a bug even after this PR. But it seems we can perhaps merge the PR for now as is, as it doesn't make things worse as far as I can tell? If anyone would like to approve it?

**Review by tthsqe12 — APPROVED** [review]
Alright, I will find that bug and fix it in a later PR (hopefully).
