### PR TITLE
fix a problem with `isomorphism` for trivial groups

### LINKED ISSUE #3583: `gmodule_minimal_field`: throws GAP error for book-example
This code (from `explSL25.jlcon`) works with Oscar 1.0.0 but fails on the current master:
```
julia> G = SL(2, 5);

julia> T = character_table(G);

julia> R = gmodule(T[end]);

julia> S = gmodule(CyclotomicField, R)
G-module for G acting on vector space of dimension 6 over cyclotomic field of order 5

julia> gmodule_minimal_field(S)
ERROR: Error thrown by GAP: Error, <gens> and <imgs> must be lists of same length at /home/lorenz/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/ghom.gi:300 called from
GroupGeneralMappingByImagesNC( G, H, gens, imgs ) at /home/lorenz/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/ghom.gi:421 called from
GroupGeneralMappingByImages( G, H, Ggens, Hgens ) at /home/lorenz/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/ghom.gi:64 called from
<function "GroupHomomorphismByImages">( <arguments> )
 called from read-eval loop at *defin*:0

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] ThrowObserver(depth::Int32)
    @ GAP ~/.julia/packages/GAP/SPegz/src/GAP.jl:89
  [3] _call_gap_func(func::GAP.GapObj, a1::GAP.GapObj, a2::GAP.GapObj, a3::GAP.GapObj, a4::GAP.GapObj)
    @ GAP ~/.julia/packages/GAP/SPegz/src/ccalls.jl:372
  [4] (::GAP.GapObj)(a1::GAP.GapObj, a2::GAP.GapObj, a3::GAP.GapObj, a4::GAP.GapObj)
    @ GAP ~/.julia/packages/GAP/SPegz/src/ccalls.jl:310
  [5] hom(G::PermGroup, H::FPGroup, gensG::Vector{PermGroupElem}, imgs::Vector{FPGroupElem}; check::Bool)
    @ Oscar ~/software/polymake/julia/Oscar.jl/src/Groups/homomorphisms.jl:124
  [6] hom(G::PermGroup, H::FPGroup, gensG::Vector{PermGroupElem}, imgs::Vector{FPGroupElem})
    @ Oscar ~/software/polymake/julia/Oscar.jl/src/Groups/homomorphisms.jl:120
  [7] fp_group_with_isomorphism(C::GModule{PermGroup, FinGenAbGroup})
    @ Oscar.GrpCoh ~/software/polymake/julia/Oscar.jl/experimental/GModule/Cohomology.jl:189
  [8] H_two(C::GModule{PermGroup, FinGenAbGroup}; force_rws::Bool, redo::Bool, lazy::Bool)
    @ Oscar.GrpCoh ~/software/polymake/julia/Oscar.jl/experimental/GModule/Cohomology.jl:1080
  [9] H_two
    @ ~/software/polymake/julia/Oscar.jl/experimental/GModule/Cohomology.jl:1068 [inlined]
 [10] #cohomology_group#237
    @ ~/software/polymake/julia/Oscar.jl/experimental/GModule/Cohomology.jl:1733 [inlined]
 [11] cohomology_group(C::GModule{PermGroup, FinGenAbGroup}, i::Int64)
    @ Oscar.GrpCoh ~/software/polymake/julia/Oscar.jl/experimental/GModule/Cohomology.jl:1719
 [12] is_coboundary(c::Oscar.GrpCoh.CoChain{2, PermGroupElem, Oscar.GrpCoh.MultGrpElem{AbsSimpleNumFieldElem}})
    @ Oscar.GaloisCohomology_Mod ~/software/polymake/julia/Oscar.jl/experimental/GModule/GaloisCohomology.jl:220
 [13] macro expansion
    @ ~/software/polymake/julia/Hecke.jl/src/Hecke.jl:497 [inlined]
 [14] _two_cocycle(mA::AbstractAlgebra.Generic.CompositeMap{…}, C::GModule{…}; do_error::Bool, two_cycle::Bool)
    @ Oscar.GModuleFromGap ~/software/polymake/julia/Oscar.jl/experimental/GModule/GModule.jl:931
 [15] gmodule_over(em::NumFieldHom{…}, C::GModule{…}; do_error::Bool)
    @ Oscar.GModuleFromGap ~/software/polymake/julia/Oscar.jl/experimental/GModule/GModule.jl:790
 [16] _minimize(V::GModule{MatrixGroup{FqFieldElem, FqMatrix}, AbstractAlgebra.Generic.FreeModule{AbsSimpleNumFieldElem}})
    @ Oscar.GModuleFromGap ~/software/polymake/julia/Oscar.jl/experimental/GModule/GModule.jl:484
 [17] gmodule_minimal_field(C::GModule{MatrixGroup{…}, AbstractAlgebra.Generic.FreeModule{…}})
    @ Oscar.GModuleFromGap ~/software/polymake/julia/Oscar.jl/experimental/GModule/GModule.jl:718
 [18] top-level scope
    @ REPL[13]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

cc: @ThomasBreuer @fingolfin

### PR DESCRIPTION
**Pull request by ThomasBreuer**
resolves #3583

### CODE REVIEW

**Comment by ThomasBreuer** [comment]
`test (1.11-nightly, long, ubuntu-latest)`  failed with a segmentation fault, I have restarted it.

File: experimental/GModule/Cohomology.jl [hunk 1]
```diff
@@ -184,11 +184,12 @@ end
 function fp_group_with_isomorphism(C::GModule)
   #TODO: better for PcGroup!!!
   if !isdefined(C, :F)
-    if (!isa(group(C), FPGroup)) && is_trivial(group(C))
+    G = group(C)
+    if (!isa(group(C), FPGroup)) && is_trivial(G)
```
Comment (fieker) [inline experimental/GModule/Cohomology.jl]: Why are you not using `G` here and in the next lines? Is it true that
 - G always has no gens OR
 - any hom G->X can be defeined using no gens?

File: experimental/GModule/Cohomology.jl [hunk 2]
```diff
@@ -184,11 +184,12 @@ end
...
       C.F = free_group(0)
-      C.mF = hom(group(C), C.F, gens(group(C)), elem_type(C.F)[])
+      C.mF = hom(group(C), C.F, elem_type(G)[], elem_type(C.F)[])
```
Comment (fingolfin) [inline experimental/GModule/Cohomology.jl]: This line does not seem to be exercised by any tests, perhaps we can add one to verify it works (related to @fieker's question about this...)

File: experimental/GModule/Cohomology.jl (hunk 1 above)
Comment (fingolfin) [inline experimental/GModule/Cohomology.jl]:
```suggestion
    if !isa(G, FPGroup) && is_trivial(G)
```

Comment (ThomasBreuer) [reply experimental/GModule/Cohomology.jl]: If G is trivial then there is exactly one homomorphism from G to another group, and `hom` creates it when we give it two empty lists, independent of how many generators G actually has.
In fact using `gens(C)` caused a problem, because it might be nonempty.

(And yes, `G` should be used instead of `group(C)`; I do not understand how this got lost, the idea was that `group(C)` was now called too often.)

File: experimental/GModule/Cohomology.jl (hunk 2 above)
Comment (ThomasBreuer) [reply experimental/GModule/Cohomology.jl]: O.k.

**Review by fingolfin — APPROVED** [review]
