### PR TITLE
SubdivisionOfPoints: reject duplicate points

### LINKED ISSUE #4684: Visualizing subdivisions of points with repeated points sometimes crashes Julia session
**Describe the bug**
Trying to visualize a regular subdivision with repeated points sometimes crashes the current Julia session.

**To Reproduce**
```
using Oscar
julia> using Oscar
julia> pts = [[0, 0], [1, 0], [0, 1], [1, 1], [2, 1], [3, 1], [2, 2], [3, 2], [2, 0], [3, 0], [2, 1], [3, 1]]
12-element Vector{Vector{Int64}}:
 [0, 0]
 [1, 0]
 [0, 1]
 [1, 1]
 [2, 1]
 [3, 1]
 [2, 2]
 [3, 2]
 [2, 0]
 [3, 0]
 [2, 1]
 [3, 1]
julia> wts = [(2), (2), (2), (2), (0), (0), (0), (0), (1), (1), (1), (1)]
12-element Vector{Int64}:
 2
 2
 2
 2
 0
 0
 0
 0
 1
 1
 1
 1
julia> sop = subdivision_of_points(pts, wts)
Subdivision of points in ambient dimension 2

julia> visualize(sop)
```
However, there are examples where points are repeated and the visualization works.
**Expected behavior**
I expect repeated points to be allowed, and the regular subdivision should be computed by adding the weights of coincident points together (this is standard when computing mixed subdivisions, see e.g. Triangulations by de Loera et al.)

In the worst case, an error message that repeated points are not allowed also works.

**System:**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.2.2
  combining:
    AbstractAlgebra.jl   v0.43.12
    GAP.jl               v0.12.3
    Hecke.jl             v0.34.9
    Nemo.jl              v0.47.5
    Polymake.jl          v0.11.25
    Singular.jl          v0.23.10
  building on:
    FLINT_jll               v300.100.301+0
    GAP_jll                 v400.1300.102+2
    Singular_jll            v404.0.711+0
    libpolymake_julia_jll   v0.13.1+0
    libsingular_julia_jll   v0.46.1+0
    polymake_jll            v400.1300.2+0
See `]st -m` for a full list of dependencies.

Julia Version 1.11.3
Commit d63adeda50d (2025-01-21 19:42 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 10 × Apple M2 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m2)
Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
Official https://julialang.org/ release

```

**Additional context**
This problem arose when trying to compute mixed subdivisions.

### PR DESCRIPTION
**Pull request by benlorenz**
- less splatting and recursion during matrix conversion and type detection
- reject duplicate points in `subdivision_of_points` (closes #4684)
- fix embed_at_height_one for polymake sparse matrices

### CODE REVIEW

File: src/PolyhedralGeometry/SubdivisionOfPoints/constructors.jl [hunk 1]
```diff
@@ -62,11 +62,13 @@ function subdivision_of_points(
   f::scalar_type_or_field, points::AbstractCollection[PointVector], cells::IncidenceMatrix
 )
   @req size(points)[1] == ncols(cells) "Number of points must be the same as columns of IncidenceMatrix"
+  hpts = homogenized_matrix(points, 1)
+  @req length(unique(eachrow(hpts))) == nrows(hpts) "Points must be unique"
```
Comment (lgoettgens) [inline src/PolyhedralGeometry/SubdivisionOfPoints/constructors.jl]:
```suggestion
  @req allunique(eachrow(hpts)) "Points must be unique"
```

File: src/PolyhedralGeometry/SubdivisionOfPoints/constructors.jl [hunk 2]
```diff
@@ -103,10 +105,12 @@ function subdivision_of_points(
   f::scalar_type_or_field, points::AbstractCollection[PointVector], weights::AbstractVector
 )
   @req size(points)[1] == length(weights) "Number of points must equal number of weights"
+  hpts = homogenized_matrix(points, 1)
+  @req length(unique(eachrow(hpts))) == nrows(hpts) "Points must be unique"
```
Comment (lgoettgens) [inline src/PolyhedralGeometry/SubdivisionOfPoints/constructors.jl]:
```suggestion
  @req allunique(eachrow(hpts)) "Points must be unique"
```

**Review by lkastner — APPROVED** [review]
