### PR TITLE
Fix worldage problems in docs build

### LINKED ISSUE #5817: Errors when building documentation
**Describe the bug**
When trying to build the Oscar docs, we get two different kinds of errors:
1. some weird "world prior to its definition world" things
2. Key "AGM20" not found

Nevertheless, the documentation build succeeds.

**To Reproduce**
```
julia> using Documenter; Oscar.build_doc()
[...]
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
WARNING: Detected access to binding `Main.BuildDoc` in a world prior to its definition world.
  Julia 1.12 has introduced more strict world age semantics for global bindings.
  !!! This code may malfunction under Revise.
  !!! This code will error in future versions of Julia.
Hint: Add an appropriate `invokelatest` around the access to this binding.
To make this warning an error, and hence obtain a stack trace, use `julia --depwarn=error`.
WARNING: Detected access to binding `BuildDoc.doit` in a world prior to its definition world.
  Julia 1.12 has introduced more strict world age semantics for global bindings.
  !!! This code may malfunction under Revise.
  !!! This code will error in future versions of Julia.
Hint: Add an appropriate `invokelatest` around the access to this binding.
To make this warning an error, and hence obtain a stack trace, use `julia --depwarn=error`.
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: skipped.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CollectCitations
┌ Error: Key "AGM20" not found in entries from /home/janika/git/Oscar.jl/docs/oscar_references.bib
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/FhKhO/src/collect_citations.jl:92
[ Info: ExpandBibliography: expanding `@bibliography` blocks.
[ Info: ExpandCitations
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
[ Info: Automatic `version="1.8.0-DEV"` for inventory from ../Project.toml
[ Info: Patching search index.
```

**Expected behavior**
no errors

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.8.0-DEV - #master, 10f1eab0f1 -- 2026-02-28 16:19:40 +0000
  combining:
    AbstractAlgebra.jl   v0.48.4
    GAP.jl               v0.16.4
    Hecke.jl             v0.39.13
    Nemo.jl              v0.54.1
    Polymake.jl          v0.13.9
    Singular.jl          v0.28.7
  building on:
    FLINT_jll                  v301.400.1+0
    GAP_jll                    v400.1500.100+1
    GAP_lib_jll                v400.1500.100+0
    Singular_jll               v404.101.503+0
    libpolymake_julia_jll      v0.14.6+1
    libsingular_julia_jll      v0.47.10+0
    polymake_jll               v400.1500.2+0
    polymake_oscarnumber_jll   v0.3.16+0
See `]st -m` for a full list of dependencies.

Julia Version 1.12.5
Commit 5fe89b8ddc1 (2026-02-09 16:05 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5825U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver3)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_EDITOR = code
Official https://julialang.org release
```

**Additional context**

### PR DESCRIPTION
**Pull request by lgoettgens**
by using `@invokelatest` to also apply the `invokelatest` to all `getproperty` and `setproperty` calls.

Resolves https://github.com/oscar-system/Oscar.jl/issues/5817.

### CODE REVIEW

**Comment by fingolfin** [comment]
I really wish we weren't doing this kind of hacking anymore; no "fiddle with Pkg and stuff to workaround the dependency system and evaluate things in Main etc.".

Can't we replace `Oscar.build_doc` by a macro `Oscar.@build_doc` which basically is called the same same but "legally" does its work in the REPL in `Main`?

**Review by fingolfin — APPROVED** [review]

File: test/book/test.jl [hunk 1]
```diff
@@ -139,7 +139,7 @@ isdefined(Main, :FakeTerminals) || include(joinpath(pkgdir(REPL),"test","FakeTer
       mockdule = Module(sym)
       # make it accessible from Main
       @eval Main global $sym::Module
-      invokelatest(setproperty!, Main, sym, mockdule)
+      @invokelatest Main.sym = mockdule
```
Comment (lgoettgens) [inline test/book/test.jl]:
```suggestion
      invokelatest(setproperty!, Main, sym, mockdule)
```
does not work, so revert

**Comment by lgoettgens** [comment]
> I really wish we weren't doing this kind of hacking anymore; no "fiddle with Pkg and stuff to workaround the dependency system and evaluate things in Main etc.".
> 
> Can't we replace `Oscar.build_doc` by a macro `Oscar.@build_doc` which basically is called the same same but "legally" does its work in the REPL in `Main`?

Sounds like a good idea. Could you open an issue so we don't forget? I will continue with merging this, as it immediately patches a symptom, and the "nice rewrite" will need some time.
