### PR TITLE
use `unhomogenized_matrix` for construction of `Cone` and `PolyhedralFan`

### LINKED ISSUE #2305: Problems with `PolyhedralFan` constructor, when lineality information is passed as `SubObjectIterator{RayVector{QQFieldElem}}`
The constructor for `PolyhedralFan` works fine in the following example:
```
fanRay = matrix(QQ,[0 -1 0; 0 0 -1])
fanLineality = matrix(QQ,[1 0 0; 0 1 1])
fanIncidences = IncidenceMatrix([[1],[2]])
Sigma = PolyhedralFan(fanRay,fanLineality,fanIncidences)
rays_modulo_lineality(Sigma)
```

However, when I pass `fanLineality` as `SubObjectIterator{RayVector{QQFieldElem}}`:
```
fanRay = matrix(QQ,[0 -1 0; 0 0 -1])
sigma = cone_from_inequalities([[0,1,-1]])
fanLineality = lineality_space(sigma)
fanIncidences = IncidenceMatrix([[1],[2]])
Sigma = PolyhedralFan(fanRay,fanLineality,fanIncidences)
rays_modulo_lineality(Sigma)
```

I get following error when trying to compute `rays_modulo_lineality` in the final line:
```
polymake:  WARNING: rule RAYS, MAXIMAL_CONES, LINEALITY_SPACE : INPUT_RAYS, INPUT_CONES, FAN_AMBIENT_DIM failed: initial check failed: dimension mismatch between INPUT_LINEALITY and CONE_AMBIENT_DIM
ERROR: Exception occured at Polymake side:
no more rules available to compute 'N_RAYS'
```

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.12.0-DEV - #yr/groebnerFan, e8f757587a -- 2023-04-18 09:19:09 +0100
  combining:
    AbstractAlgebra.jl   v0.29.2
    GAP.jl               v0.9.4
    Hecke.jl             v0.18.8
    Nemo.jl              v0.33.7
    Polymake.jl          v0.9.0
    Singular.jl          v0.18.1
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.5+0
    GAP_jll                 v400.1200.200+0
    Singular_jll            v403.101.500+0
    libpolymake_julia_jll   v0.9.0+0
    libsingular_julia_jll   v0.29.0+0
    polymake_jll            v400.900.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Official https://julialang.org/ release
```

### PR DESCRIPTION
**Pull request by alexej-jordan**
This PR solves #2305 by using `unhomogenized_matrix` during the construction of `PolyhedralFan` objects. The reported error could also appear for `Cone`s and for rays given as `SubObjectIterator`, which is also fixed here. Some small tests were added to check for this specific case.

### CODE REVIEW

File: test/PolyhedralGeometry/extended.jl [hunk 1]
```diff
@@ -197,6 +197,12 @@
         @test_throws ArgumentError convex_hull(collect(rays(Pos_poly)))
         @test_throws ArgumentError convex_hull(vertices(Pos_poly), collect(vertices(Pos_poly)))
         @test_throws ArgumentError positive_hull(collect(vertices(Pos_poly)))
+
+	IM = IncidenceMatrix([[1]])
+	lincone = Cone([1 0 0], [0 1 0])
+
+	@test Cone(rays_modulo_lineality(lincone)...) == lincone
+	@test ambient_dim(PolyhedralFan(rays_modulo_lineality(lincone)..., IM)) == 3
```
Comment (benlorenz) [inline test/PolyhedralGeometry/extended.jl]:
```suggestion
        @test_throws ArgumentError positive_hull(collect(vertices(Pos_poly)))

        IM = IncidenceMatrix([[1]])
        lincone = Cone([1 0 0], [0 1 0])

        @test Cone(rays_modulo_lineality(lincone)...) == lincone
        @test ambient_dim(PolyhedralFan(rays_modulo_lineality(lincone)..., IM)) == 3
```

**Review by benlorenz — APPROVED** [review]
