### PR TITLE
Stabilize `singular_loci`'s refined Tate fiber type computation (Monte Carlo) with fixed seed

### LINKED ISSUE #4593: rare tate-models error: Singular loci split vs non-split
This happened in our CI here https://github.com/oscar-system/Oscar.jl/actions/runs/13306594007/job/37158890795?pr=4588#step:11:10734 (julia 1.11, ubuntu) and disappeared after a re-run:
```
      From worker 5:	Singular loci of global Tate models over generic base space: Test Failed at /home/oscarci-tester/oscar-runners/runner-11/_work/Oscar.jl/Oscar.jl/experimental/FTheoryTools/test/tate_models.jl:249
      From worker 5:	  Expression: [k[2:3] for k = singular_loci(t_ivstar_ns)] == [((0, 0, 1), "I_1"), ((3, 4, 8), "Non-split IV^*")]
      From worker 5:	   Evaluated: [((0, 0, 1), "I_1"), ((3, 4, 8), "Split IV^*")] == [((0, 0, 1), "I_1"), ((3, 4, 8), "Non-split IV^*")]
```
This is the first time I have seen this error, unfortunately I don't know how to reproduce this. 

Is there any randomness involved?

PS: This was on https://github.com/oscar-system/Oscar.jl/pull/4588/commits/b2d105886deca51ba371f0042adb90189d315699 which is basically master except for some reordered exports in `GModule`.

### PR DESCRIPTION
**Pull request by HereAround**
Aims to close https://github.com/oscar-system/Oscar.jl/issues/4593. (~~Might need rebasing should https://github.com/oscar-system/Oscar.jl/pull/5154 be merged first.~~)

### CODE REVIEW

File: experimental/FTheoryTools/src/auxiliary.jl [hunk 1]
```diff
@@ -198,12 +198,13 @@ function _kodaira_type(id::MPolyIdeal{<:MPolyRingElem}, ords::Tuple{Int64, Int64
     # five times and see if we get agreement among all of the results
     num_gens = ngens(parent(f))
     gauge2s, f2s, g2s, d2s = [], [], [], []
+    rng = MersenneTwister()
```
Comment (HereAround) [inline experimental/FTheoryTools/src/auxiliary.jl]: @benlorenz This is the first thing which @apturner and I could think of. But not sure if this is the best choice. Maybe you have thoughts?

In any case, this should be one of the key changes you were asking for.

File: experimental/FTheoryTools/test/hypersurface_models.jl [hunk 2]
```diff
@@ -2,6 +2,8 @@
 # 1: Hypersurface models over concrete bases
 #############################################################
 
+rand_seed = 1234
```
Comment (HereAround) [inline experimental/FTheoryTools/test/hypersurface_models.jl]: And this is another key change - fixing one `rand_seed` in each test file and then passing this seed to the calls of `singular_loci`.

I tried to repeat this for all relevant test files and doc tests. Hopefully I found them all.

(Of course, not yet clear if this simple seed passes the tests...)

File: experimental/FTheoryTools/src/auxiliary.jl (hunk 1 above)
Comment (benlorenz) [reply experimental/FTheoryTools/src/auxiliary.jl]: I would recommend changing the keyword argument to use an RNG object instead of passing a seed, e.g. `rng::AbstractRNG = Random.default_rng()`. This allows some more flexibility and doesn't hardcode the RNG type.
Then you don't need the `!= nothing` and `seed!` block.

And `rand_seed = 1234` in the tests could become `rng = Random.Xoshiro(1234)`.

Strictly speaking this might not be fully stable for all (future) julia versions (the same holds for `MersenneTwister` which was the default RNG in older julia versions).
If a fully stable rng is needed (I don't think so) we would need to use something like `StableRNGs.jl`.

File: experimental/FTheoryTools/test/hypersurface_models.jl (hunk 2 above)
Comment (benlorenz) [reply experimental/FTheoryTools/test/hypersurface_models.jl]: This would need to be adjusted to the rng object mentioned at the other line.

(And the probability is quite high that this seed passes the tests?)

File: experimental/FTheoryTools/src/auxiliary.jl (hunk 1 above)
Comment (HereAround) [reply experimental/FTheoryTools/src/auxiliary.jl]: Thank you. Just adjusted accordingly.

File: experimental/FTheoryTools/test/hypersurface_models.jl (hunk 2 above)
Comment (HereAround) [reply experimental/FTheoryTools/test/hypersurface_models.jl]: Thank you. Just done.

File: experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl [hunk 3]
```diff
@@ -336,11 +336,12 @@ end
 
 
 @doc raw"""
-    singular_loci(h::HypersurfaceModel)
+    singular_loci(h::HypersurfaceModel; rand_seed::AbstractRNG = Random.default_rng())
 
 Return the singular loci of the Weierstrass model equivalent to the given hypersurface model,
 along with the order of vanishing of ``(f, g, \Delta)`` at each locus and the corresponding
-refined Tate fiber type. See [singular_loci(w::WeierstrassModel)](@ref) for more details.
+refined Tate fiber type. See [singular_loci(w::WeierstrassModel; rand_seed::AbstractRNG = Random.default_rng())](@ref)
```
Comment (lgoettgens) [inline experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl]:
```suggestion
refined Tate fiber type. See [`singular_loci(w::WeierstrassModel)`](@ref)
```
this is missing backticks.
and also you can drop all kwargs from references, as they are not used in dispatch (thus reducing the diff and making the docs more future-proof (wrong kwargs are even worse for readers of the md))

(applicable in more places in this PR)

File: experimental/FTheoryTools/docs/src/hypersurface.md [hunk 4]
```diff
@@ -139,7 +139,7 @@ More informative than the discriminant itself is its **decomposition** into irre
 corresponds to a locus where the fiber exhibits a distinct singularity structure. These can be classified using:
 
 ```@docs
-singular_loci(h::HypersurfaceModel)
+singular_loci(h::HypersurfaceModel; rand_seed::AbstractRNG = Random.default_rng())
```
Comment (lgoettgens) [inline experimental/FTheoryTools/docs/src/hypersurface.md]:
```suggestion
singular_loci(h::HypersurfaceModel)
```
with the same reasoning, kwargs can be dropped from `@docs` blocks. Again, reducing the PR diff. (applicable in more places in this PR)

File: experimental/FTheoryTools/src/LiteratureModels/constructors.jl [hunk 5]
```diff
@@ -81,7 +81,7 @@ Construction over concrete base may lead to singularity enhancement. Consider co
 
 Weierstrass model over a concrete base -- U(1) Weierstrass model based on arXiv paper 1208.2695 Eq. (B.19)
 
-julia> length(singular_loci(w))
+julia> length(singular_loci(w; rand_seed = Random.Xoshiro(1234)1234))
```
Comment (lgoettgens) [inline experimental/FTheoryTools/src/LiteratureModels/constructors.jl]:
```suggestion
julia> length(singular_loci(w; rand_seed = Random.Xoshiro(1234)))
```
typo

File: experimental/FTheoryTools/src/auxiliary.jl [hunk 6]
```diff
@@ -114,7 +114,7 @@ _count_factors(poly::QQMPolyRingElem) = mapreduce(p -> p[end], +, absolute_prima
 
 _string_from_factor_count(poly::QQMPolyRingElem, string_list::Vector{String}) = string_list[_count_factors(poly)]
 
-function _kodaira_type(id::MPolyIdeal{<:MPolyRingElem}, ords::Tuple{Int64, Int64, Int64}, w::WeierstrassModel; rand_seed::Union{Int64, Nothing} = nothing)
+function _kodaira_type(id::MPolyIdeal{<:MPolyRingElem}, ords::Tuple{Int64, Int64, Int64}, w::WeierstrassModel; rand_seed::AbstractRNG = Random.default_rng())
```
Comment (lgoettgens) [inline experimental/FTheoryTools/src/auxiliary.jl]:
```suggestion
function _kodaira_type(id::MPolyIdeal{<:MPolyRingElem}, ords::Tuple{Int64, Int64, Int64}, w::WeierstrassModel; rng::AbstractRNG = Random.default_rng())
```
it's a bit weird to have a variable named `rand_seed` that does not contain a random seed, but instead a random number generator. Better name this `rng` then (here and basically everywhere else in this PR)

File: experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl (hunk 3 above)
Comment (HereAround) [reply experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl]: Thank you. Fixed.

File: experimental/FTheoryTools/docs/src/hypersurface.md (hunk 4 above)
Comment (HereAround) [reply experimental/FTheoryTools/docs/src/hypersurface.md]: Thank you. Fixed.

File: experimental/FTheoryTools/src/LiteratureModels/constructors.jl (hunk 5 above)
Comment (HereAround) [reply experimental/FTheoryTools/src/LiteratureModels/constructors.jl]: Thank you. Fixed.

File: experimental/FTheoryTools/src/auxiliary.jl (hunk 6 above)
Comment (HereAround) [reply experimental/FTheoryTools/src/auxiliary.jl]: Sure. Is done.

**Comment by HereAround** [comment]
@benlorenz When you find the time, please take a look at this. Thank you!

File: experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl [hunk 7]
```diff
@@ -297,6 +297,7 @@ model (see [BMT25](@cite BMT25) for background), in order to demonstrate this fu
 !!! warning
     The classification of singularities is performed using a Monte Carlo algorithm, involving randomized sampling.
     While reliable in practice, this probabilistic method may occasionally yield non-deterministic results.
+    The random seed can be set with the optional argument `rng`.
```
Comment (benlorenz) [inline experimental/FTheoryTools/src/HypersurfaceModels/attributes.jl]:
```suggestion
    The random source can be set with the optional argument `rng`.
```
The argument is an RNG object so I would use `random source` instead of `random seed`.

File: experimental/FTheoryTools/src/TateModels/attributes.jl [hunk 8]
```diff
@@ -320,11 +320,12 @@ end
 
 Return the singular loci of the Weierstrass model equivalent to the given Tate model,
 along with the order of vanishing of ``(f, g, \Delta)`` at each locus and the corresponding
-refined Tate fiber type. See [singular_loci(w::WeierstrassModel)](@ref) for more details.
+refined Tate fiber type. See [`singular_loci(w::WeierstrassModel)`](@ref) for more details.
 
 !!! warning
     The classification of singularities is performed using a Monte Carlo algorithm, involving randomized sampling.
     While reliable in practice, this probabilistic method may occasionally yield non-deterministic results.
+    The random seed can be set with the optional argument `rng`.
```
Comment (benlorenz) [inline experimental/FTheoryTools/src/TateModels/attributes.jl]:
```suggestion
    The random source can be set with the optional argument `rng`.
```

File: experimental/FTheoryTools/src/WeierstrassModels/attributes.jl [hunk 9]
```diff
@@ -178,18 +178,21 @@ Advanced technical details are available in [BMT25](@cite BMT25).
 
 !!! warning
     The classification of singularities is based on a Monte Carlo algorithm, which involves random sampling.
-    While extensively tested and highly reliable, the method’s probabilistic nature may lead to non-deterministic results in rare cases.
+    While reliable in practice, this probabilistic method may occasionally yield non-deterministic results.
+    The random seed can be set with the optional argument `rng`.
```
Comment (benlorenz) [inline experimental/FTheoryTools/src/WeierstrassModels/attributes.jl]:
```suggestion
    The random source can be set with the optional argument `rng`.
```

File: experimental/FTheoryTools/src/auxiliary.jl [hunk 10]
```diff
@@ -198,12 +198,10 @@ function _kodaira_type(id::MPolyIdeal{<:MPolyRingElem}, ords::Tuple{Int64, Int64
     # five times and see if we get agreement among all of the results
     num_gens = ngens(parent(f))
     gauge2s, f2s, g2s, d2s = [], [], [], []
-    if rand_seed != nothing
-      Random.seed!(rand_seed)
-    end
+    rng = MersenneTwister()
```
Comment (benlorenz) [inline experimental/FTheoryTools/src/auxiliary.jl]:
```suggestion
```
This line should be removed as it replaces the one passed in the argument.

**Comment by HereAround** [comment]
Thank you @benlorenz , have just applied your suggestions. Is this PR now ready to be merged? Please take another look.

**Review by benlorenz — APPROVED** [review]

**Comment by lgoettgens** [comment]
Reminder: This has a "release notes: to be added" label, but the initial comment does not have a copy-pasteable block of release notes. Please either choose a different label or add the release notes here.
