### PR TITLE
Make `isomorphism(PcGroup, A)` for infinite abelian `A` work

### LINKED ISSUE #4318: Error converting infinite abelian group to `PcGroup`
```
julia> G = abelian_group(3, 0)
Z/3 x Z

julia> isomorphism(PcGroup, G)
ERROR: Error thrown by GAP: Error, no method found! For debugging hints type ?Recovery from NoMethodFound
```

### PR DESCRIPTION
**Pull request by ThomasBreuer**
The documentation claimed that this is not supported, but in fact GAP's pcp groups can deal with this case.

The code looks horrible,
due to the fact that GAP supports the decomposition of elements in abelian groups w.r.t. independent generators only for special such generating sets.
(This happens for abelian permutation groups.)

Note that this is generic code.
Perhaps we should add special methods for the case that we ask for a `FPGroup` or a `PcGroup`, then also the functions for computing (pre)images can be more efficient.

resolves #4318

### CODE REVIEW

File: src/Groups/homomorphisms.jl [hunk 1]
```diff
@@ -729,15 +729,16 @@ function isomorphism(::Type{T}, A::FinGenAbGroup) where T <: GAPGroup
...
      # Create an isomorphic GAP group whose `GAPWrap.GeneratorsOfGroup`
      # consists of independent elements of the orders in `exponents`.
-     # (We cannot guarantee that these generators form a pcgs in the case
-     # `T == PcGroup`, hence we cannot call `abelian_group(T, exponents)`.)
      if T == PcGroup
+       # We cannot guarantee that these generators form a pcgs in the case
+       # `T == PcGroup`, hence we cannot call `abelian_group(T, exponents)`.
        if 0 in exponents
          GapG = GAP.Globals.AbelianPcpGroup(length(exponents), GapObj(exponents; recursive = true))
+         G = PcGroup(GapG)
```
Comment (fingolfin) [inline src/Groups/homomorphisms.jl:737]: For `Pcp` groups the given exponents actually do correspond 1-1 to the given exponent vector.

On the other hand `IndependentGeneratorsOfAbelianGroup` output looks horrible:
```gap
gap> G:=AbelianPcpGroup([3,0,3,9,15]);
Pcp-group with orders [ 3, 0, 3, 9, 15 ]
gap> gens:=GeneratorsOfGroup(G);
[ g1, g2, g3, g4, g5 ]
gap> List(gens, Order);
[ 3, infinity, 3, 9, 15 ]
gap> IndependentGeneratorsOfAbelianGroup(G);
[ g2*g3^2*g4, g1, g3*g5^5, g4^6*g5^10, g5^6, g4^5*g5^10 ]
```

So I think we should avoid `IndependentGeneratorsOfAbelianGroup` and `IndependentGeneratorExponents` for pcp groups.

Comment (ThomasBreuer) [reply src/Groups/homomorphisms.jl:737]: That is what I meant when I wrote that special methods for `FPGroup` and `PcGroup` would make sense.

**Review by fingolfin — APPROVED** [review]
