### PR TITLE
Fix for dual matroids #1284

### LINKED ISSUE #1284: Matroid code error
There is an error in the Matroid code: https://github.com/oscar-system/Oscar.jl/runs/6191061211?check_suite_focus=true#step:5:178

pinging @bschroter
since there is a polymake warning, pinging also @benlorenz

_Originally posted by @thofma in https://github.com/oscar-system/Oscar.jl/issues/1281#issuecomment-1110839907_

### PR DESCRIPTION
**Pull request by bschroter**
Here is a fix for #1284  that ensures that the dual matroid  is a proper object.

### CODE REVIEW

**Comment by benlorenz** [comment]
It would be good to add a testcase to avoid regressions, something like this:
```julia
m = dual_matroid(fano_matroid())
GC.gc()
@test bases(m) isa Vector
```

File: test/Combinatorics/Matroids/Matroids.jl [hunk 1]
```diff
@@ -137,8 +137,9 @@
 
         mg5 = dual_matroid(mg1)
```
Comment (benlorenz) [inline test/Combinatorics/Matroids/Matroids.jl:138]:
```suggestion
        mg5 = dual_matroid(cycle_matroid(g1))
```
The test needs that the input for the `dual_matroid` is allowed to be garbage-collected, e.g when it is a temporary object or when the input variable is reassigned `mg1 = nothing`. Maybe add a comment about this as well.
(Otherwise the test won't fail without this changeset)

Comment (bschroter) [reply test/Combinatorics/Matroids/Matroids.jl:138]: That makes perfect sense. I preferred the reassigning, and added a comment.

**Review by benlorenz — APPROVED** [review]

**Review by benlorenz — APPROVED** [review]

**Comment by benlorenz** [comment]
github still asks for another review at the top (`fingolfin requested your review on this pull request.`) and says `Awaiting review` on the right, I also did get 4 emails about that for some reason.

Edit: three approvals were enough to get that check-mark on the right ....

**Review by benlorenz — APPROVED** [review]
