### PR TITLE
Fix wrong result of `isomorphism(FPGroup, G, on_gens = true)` for trivial `G` with more than 0 generators

### LINKED ISSUE #4377: `isomorphism(FPGroup, G; on_gens=true)` incorrect when `G` is trivial
Reported by @fieker:
```
julia> S = symmetric_group(1)
Permutation group of degree 1 and order 1

julia> s = sub(S, [one(S), one(S)])[1]
Permutation group of degree 1

julia> ngens(s)
2

julia> phi = isomorphism(FPGroup, s, on_gens = true)
Group homomorphism
  from permutation group of degree 1 and order 1
  to free group

julia> ngens(domain(phi))
2

julia> ngens(codomain(phi))
0
```

The final output should be 2, not 0.

This is caused by the code starting in `src/Groups/homomorphisms.jl:569`:
```
function isomorphism(::Type{FPGroup}, G::GAPGroup; on_gens::Bool=false)
   # Known isomorphisms are cached in the attribute `:isomorphisms`.
   isos = get_attribute!(Dict{Tuple{Type, Bool}, Any}, G, :isomorphisms)::Dict{Tuple{Type, Bool}, Any}
   return get!(isos, (FPGroup, on_gens)) do
     if is_trivial(G)
# TODO: remove this special treatment as soon as the change from
#       https://github.com/gap-system/gap/pull/5700 is available in Oscar
#       (not yet in GAP 4.13.0)
       f = GAP.Globals.GroupHomomorphismByImages(GapObj(G), GAP.Globals.FreeGroup(0), GAP.Obj([]), GAP.Obj([]))
       GAP.Globals.SetIsBijective(f, true)
     elseif on_gens
...
```

The case of trivial `G` is handled separately for now but doesn't take `on_gens` into account.

The comment makes it sound as if this might be released with GAP 4.14.0 (which I hope to release today). But of course (a) that will take some more time to arrive (need to run tests, updated GAP.jl). But (b) it is not clear to me this particular issue will *really* be fixed by this.

@ThomasBreuer could you please look into this

### PR DESCRIPTION
**Pull request by ThomasBreuer**
for trivial `G` with more than 0 generators

resolves #4377

### CODE REVIEW

**Review by fieker — APPROVED** [review]
if it helps... I am never sure about the gap side, in particular in view of the TODO

File: src/Groups/homomorphisms.jl [hunk 1]
```diff
@@ -570,7 +570,7 @@ function isomorphism(::Type{FPGroup}, G::GAPGroup; on_gens::Bool=false)
    # Known isomorphisms are cached in the attribute `:isomorphisms`.
    isos = get_attribute!(Dict{Tuple{Type, Bool}, Any}, G, :isomorphisms)::Dict{Tuple{Type, Bool}, Any}
    return get!(isos, (FPGroup, on_gens)) do
-     if is_trivial(G)
+     if is_trivial(G) && ngens(G) == 0
 # TODO: remove this special treatment as soon as the change from
 #       https://github.com/gap-system/gap/pull/5700 is available in Oscar
 #       (not yet in GAP 4.13.0)
```
Comment (lgoettgens) [inline src/Groups/homomorphisms.jl]: https://github.com/gap-system/gap/pull/5700 was backported to gap 4.13.1 which is available in Oscar right now, so you could remove this special case altogether if I am not mistaken here

Comment (fingolfin) [reply src/Groups/homomorphisms.jl]: Indeed, that seems to work. I just pushed a corresponding commit. It works locally, let's see if it also passes CI.
