### PR TITLE
fix `has_gens` for certain matrix groups

### LINKED ISSUE #5661: `has_gens` errors because generators are not known
**Describe the bug**
`has_gens` sometimes throws an Error if gnerators are not known instead of returning `false`

**To Reproduce**
```
julia> s = SL(5, QQ)
SL(5,QQ)

julia> has_gens(s)
ERROR: no generators are known for the matrix group of type SL over Rational field
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:44
 [2] assign_from_description(G::MatrixGroup{QQFieldElem, QQMatrix})
   @ Oscar ~/.julia/packages/Oscar/eTXAp/src/Groups/matrices/MatGrp.jl:245
 [3] GapObj_internal(G::MatrixGroup{QQFieldElem, QQMatrix}, cache::Nothing, ::Val{false})
   @ Oscar ~/.julia/packages/Oscar/eTXAp/src/Groups/matrices/MatGrp.jl:315
 [4] GapObj(x::MatrixGroup{QQFieldElem, QQMatrix}; recursive::Bool)
   @ GAP ~/.julia/packages/GAP/4O4Af/src/julia_to_gap.jl:79
 [5] GapObj
   @ ~/.julia/packages/GAP/4O4Af/src/julia_to_gap.jl:79 [inlined]
 [6] has_gens(G::MatrixGroup{QQFieldElem, QQMatrix})
   @ Oscar ~/.julia/packages/Oscar/eTXAp/src/Groups/GAPGroups.jl:642
 [7] top-level scope
   @ REPL[5]:1
```

**Expected behavior**
return false

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.6.0
  combining:
    AbstractAlgebra.jl   v0.47.6
    GAP.jl               v0.16.2
    Hecke.jl             v0.39.3
    Nemo.jl              v0.52.4
    Polymake.jl          v0.13.4
    Singular.jl          v0.28.2
  building on:
    FLINT_jll                  v301.300.102+0
    GAP_jll                    v400.1500.100+1
    GAP_lib_jll                v400.1500.100+0
    Singular_jll               v404.101.502+0
    libpolymake_julia_jll      v0.14.3+1
    libsingular_julia_jll      v0.47.9+0
    polymake_jll               v400.1500.0+0
    polymake_oscarnumber_jll   v0.3.12+1
See `]st -m` for a full list of dependencies.

Julia Version 1.12.3
Commit 966d0af0fdf (2025-12-15 11:20 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5825U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver3)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_EDITOR = code
Official https://julialang.org release
```

### PR DESCRIPTION
**Pull request by ThomasBreuer**
Be careful if the matrix group is not suported by GAP.

resolves #5661

### CODE REVIEW

File: test/Groups/matrixgroups.jl [hunk 1]
```diff
@@ -339,6 +339,16 @@ end
    setfield!(G,:descr,:GX)
    @test isdefined(G,:descr)
    @test_throws ErrorException GapObj(G)
+
+   G = GL(2, 3)
+   @test !has_gens(G)
+   GapObj(G)
+   @test has_gens(G)
```
Comment (lgoettgens) [inline test/Groups/matrixgroups.jl:346]: This kind of violates against the groups conformance tests (cf https://github.com/Nemocas/AbstractAlgebra.jl/blob/fccef26d4c7d226ed8a141d5dbe55e9c415b0b3e/ext/TestExt/Groups-conformance-tests.jl#L61-L73) as there it is tested that `gens` throws if `has_gens` returns false. For `GL(2, 3)` that would not be the case

File: src/Groups/matrices/MatGrp.jl [hunk 2]
```diff
@@ -125,6 +125,13 @@ function _as_subgroup_bare(G::MatrixGroup, H::GapObj)
   return H1
 end
 
+# We may store generators on the Oscar side or on the GAP side.
+function has_gens(G::MatrixGroup)
+  isdefined(G,:gens) && return true
+  isdefined(G, :X) || return false
+  return GAP.Globals.HasGeneratorsOfGroup(GapObj(G))::Bool
+end
```
Comment (lgoettgens) [inline src/Groups/matrices/MatGrp.jl]:
```suggestion
function has_gens(G::MatrixGroup)
  isdefined(G, :gens) && return true
  F = codomain(_ring_iso(G))
  GAP.Globals.IsBaseRingSupportedForClassicalMatrixGroup(F, GapObj(G.descr)) || return false
  return GAP.Globals.HasGeneratorsOfGroup(GapObj(G))::Bool
end
```
what about something like this?

**Comment by ThomasBreuer** [comment]
> This kind of violates against the groups conformance tests [...] as there it is tested that `gens` throws if `has_gens` returns false.

Hmm, all `has_something` functions that are related to GAP objects have the meaning "is the `something` value already stored".
The value may change in the sense that first no `something` is stored and later it gets stored, typically by explicitly calling `something`.

There are two docstrings for `has_gens(::Group)`, and both of them seem to fit to this interpretation.

**Comment by ThomasBreuer** [comment]
@lgoettgens @fingolfin

The question seems to be what we want:

If `has_gens` shall express that "calling `gens(G)` will be successful (if and) only if `has_gens(G)` returns `true`" then we will have to change the documentation and the implementation.

But is this really what we want?
What about situations with finitely presented groups where certain subgroups initially do not know generators?
Asking GAP for generators of the subgroup will cause a coset enumeration --if this is successful then generators can be constructed.
Here is an example.

```
gap> F:= FreeGroup( 2 );;
gap> G:= F / [ F.1^2, F.2^3, (F.1*F.2)^6 ];
<fp group on the generators [ f1, f2 ]>
gap> U:= DerivedSubgroup( G );
Group(<fp, no generators known>)
gap> HasGeneratorsOfGroup( U );
false
gap> GeneratorsOfGroup( U );
[ f2*f1*f2^-1*f1^-1, f2^-1*f1*f2*f1^-1 ]
```

File: test/Groups/matrixgroups.jl (hunk 1 above)
Comment (fingolfin) [reply test/Groups/matrixgroups.jl:346]: IMHO, the group conformance tests are simply wrong and need to be adjusted. This part has to be removed:
```julia
          else
              # TODO: throw something more specific
              @test_throws ErrorException gens(G)
              @test_throws ErrorException ngens(G)
```
Because it contradicts the `has_gens` documentation, which says:
>   Note that the result of this function when applied to a specific group instance can change over time, as side
>  effect of a generating set becoming available for the group.

In particular, one of the function which may have this side effect is `gens`, another is `ngens`.

This is *not* to say we shouldn't *also* adjust this PR, though.

Comment (fingolfin) [reply test/Groups/matrixgroups.jl:346]: See https://github.com/Nemocas/AbstractAlgebra.jl/pull/2275

File: src/Groups/matrices/MatGrp.jl [hunk 3]
```diff
@@ -125,6 +125,23 @@ function _as_subgroup_bare(G::MatGroup, H::GapObj)
   return H1
 end
 
+# `has_gens` shall be `true` if the `gens` value is cheap to compute.
+# For matrix groups, generators may be stored on the Oscar side
+# or on the GAP side.
+# If no `GapObj` of the matrix group has been computed yet,
+# we regard it as cheap to create this `GapObj` if this is makes sense,
+# and then to check whether the `GapObj` stores generators.
+function has_gens(G::MatrixGroup)
```
Comment (ThomasBreuer) [inline src/Groups/matrices/MatGrp.jl]:
```suggestion
function has_gens(G::MatGroup)
```

**Review by fingolfin — APPROVED** [review]
Looks good to me, thanks!

@lgoettgens if you agree, please merge

**Review by lgoettgens — APPROVED** [review]
