### PR TITLE
Hotfix Oscar.build()

### LINKED ISSUE #5421: `Oscar.build()` is broken
**Describe the bug**
`Oscar.build()` fails for me in multiple places.

First, it fails in `experimental/LieAlgebras/DynkinDiagram-test.jl`.
I don't know where exactly it fails, as the error message is `ERROR: LoadError: LoadError: ArgumentError: Package CodecZlib not found in current path` and I don't understand how the `DynkinDiagram-test.jl` test actually works. 
I've attached a copy of the stacktrace, (CodecZlib.stacktrace) just in case it's helpful.

This is fine though, as I can get the build to continue by adding the missing package to `system/Build.jl`: 
```
diff --git a/system/Build.jl b/system/Build.jl
index 68c74bf7e..3171cf961 100644
--- a/system/Build.jl
+++ b/system/Build.jl
@@ -6,6 +6,7 @@ Pkg.develop(path="$(oscarpath)")
 using Oscar
 Pkg.add("PackageCompiler")
 Pkg.add("Libdl")
+Pkg.add("CodecZlib")

 using PackageCompiler, Libdl
```

Once this is done, a new issue appears: `ERROR: LoadError: UndefVarError: `tf_unicode` not defined in `PrettyTables`

The stack trace (attached as `tf_unicode.stacktrace`) claims that `test/runtests.jl:182` is the problem, which looks harmless to me:
``` 
177  if haskey(ENV, "GITHUB_STEP_SUMMARY")
178    open(ENV["GITHUB_STEP_SUMMARY"], "a") do io
179      print_stats(io, stats; fmt=PrettyTables.tf_markdown)
180    end
181  else
182    print_stats(stdout, stats; max=10)
183  end
184
185  cd(oldWorkingDirectory)
```

I noticed that `PrettyTables` is a few years out of date, but there's also been a breaking API change since the version in `Manifest.toml` and as far as I can tell the `tf_unicode` symbol is defined in that version.
I'm not intimately familiar with Julia but I guess that maybe when `system/precompile.jl` adds `PrettyTables` in the `Oscar.build()` tmpdir it doesn't see the `Manifest.toml` of the root project and instead pulls the latest, incompatible, version.

I haven't tested this (yet) but I wonder if it could be 'fixed' by specifying the version of `PrettyTables` to import in `system/precompile.jl`.
I guess it could also be 'fixed' by updating `test/runtests.jl` to the latest version of `PrettyTables` but that's no fun :).

**To Reproduce**
```
import Pkg; Pkg.add("Oscar")
using Oscar

Oscar.build()
```

I can also reproduce the failure with
```
$ git clone https://github.com/oscar-system/oscar.jl && cd oscar
$ julia
pkg> activate oscarenv; dev .
julia> using Oscar; Oscar.build()
```
(I had to do this to get `dev .` working, which I guess is because Oscar is installed in my global environment and Julia isn't happy about having two different versions of `Oscar`.)

**Expected behavior**
I expect the build to finish successfully.

I was able to successfully build by commenting out the `include(<...>, "runtests.jl")` line of `system/precompile.jl` which skips all tests, and I wonder if that is a workable solution here.
I guess it might be since I don't think that `Oscar.build()` is intended for CI but rather intended for compiling a sysimage for faster startup (which is my intent as well).

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.6.0-DEV - #master, d934864259 -- 2025-10-06 22:08:00 +0000
  combining:
    AbstractAlgebra.jl   v0.47.3
    GAP.jl               v0.15.3
    Hecke.jl             v0.38.6
    Nemo.jl              v0.52.1
    Polymake.jl          v0.13.2
    Singular.jl          v0.26.0
  building on:
    FLINT_jll                  v301.300.102+0
    GAP_jll                    v400.1401.5+0
    GAP_lib_jll                v400.1400.5+0
    Singular_jll               v404.100.301+0
    libpolymake_julia_jll      v0.14.2+0
    libsingular_julia_jll      v0.47.6+0
    polymake_jll               v400.1500.0+0
    polymake_oscarnumber_jll   v0.3.11+0
See `]st -m` for a full list of dependencies.

Julia Version 1.11.7
Commit f2b3dbda30a (2025-09-08 12:10 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 12 × Apple M3 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m2)
Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
Environment:
  JULIA_DEPOT_PATH = /Users/james/.local/toolchains/julia
Official https://julialang.org/ release
```

[CodecZlib.txt](https://github.com/user-attachments/files/22734941/CodecZlib.txt)
[tf_unicode.txt](https://github.com/user-attachments/files/22734942/tf_unicode.txt)

### PR DESCRIPTION
**Pull request by aaruni96**
Fixes #5421 for now.

John wrote in the issue

> I note that in triage there were some significant-sounding comments from @lgoettgens and from @benlorenz about why a redesign might be needed.

I would love to hear from @lgoettgens and @benlorenz about a better design. My attitude towards `Oscar.build()` has just been to patch things until it works without really thinking about it too much.

### CODE REVIEW

File: system/Build.jl [hunk 1]
```diff
@@ -2,6 +2,10 @@ oscarpath = dirname(@__DIR__)
 
 using Pkg
 Pkg.activate(temp=true)
+target = Pkg.project().path
+source = source = "$(Oscar.oscardir)/test/Project.toml"
```
Comment (benlorenz) [inline system/Build.jl]:
```suggestion
source = joinpath(oscarpath, "test", "Project.toml")
```

File: system/Build.jl
Comment (benlorenz) [inline system/Build.jl:23]: Which project is this block running in? It either needs the test-dependencies as well or it doesn't need the `develop` command if it uses the project from above?

**Review by benlorenz — COMMENTED** [review]
My comment at the meeting was just mentioning that we need to add the dependencies from test-project with the compat entries, instead of just adding the dependencies again in the jl file. So this should be fine, I haven't tested it though.

File: system/Build.jl
Comment (aaruni96) [reply system/Build.jl:23]: You are right, the system image still builds if you remove these.

**Review by benlorenz — APPROVED** [review]
