### PR TITLE
Start of discrete_log algorithm.

### LINKED ISSUE #1205: Wanted: discrete logarithm for finite field elements
It'd be good to have a function `disc_log` or `discrete_logarithm` or whatever. For my purposes the inputs would be elements of a finite field. Of course the case where logarithm does not exist should be covered. E.g. by returning `nothing` or throwing an exception or returning two values (either `true, the_log` or `false, 0` or something like that).

Don't worry about doing the world best implementation. This is what you need to beat (for all finite fields):
```julia
# TODO very bold discrete log, waiting for a better one. Don't try with large fields!!
# return g such that a^g = b
function _disc_log(a,b)
   for g in 0:order(parent(a))
      if a^g==b
         return g
      end
   end
   error("Second element is not a power of the first one")
end
```

### PR DESCRIPTION
**Pull request by danielrademacher**
Closes #1205.

### CODE REVIEW

File: experimental/DiscreteLog/DiscreteLog.jl [hunk 1]
```diff
@@ -0,0 +1,24 @@
+module DiscreteLog
+
+  using GAP
```
Comment (fingolfin) [inline experimental/DiscreteLog/DiscreteLog.jl]: Why GAP?

Anyway, I don't think we need to put this into experimental, it can go straight into the main part. Perhaps into `src/NumberTheory/NmbThy.jl` ?

File: experimental/DiscreteLog/DiscreteLog.jl [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+#        the same finite field
+# Output: Integer s such that b^s = x
+#         If no such x exists, an error is thrown
+# Example:
+# julia> F = GF(3,4);
+# julia> a = gen(F)^21;
+# julia> Oscar.DiscreteLog.disc_log(gen(F), a)
+# > 21
+#
+function disc_log(b::T, x::T) where {T <: FinFieldElem}
```
Comment (fingolfin) [inline experimental/DiscreteLog/DiscreteLog.jl]: ideally also replace the hackish `_disc_log` referenced in several files by this

**Review by fingolfin — COMMENTED** [review]
nice, thanks :-)

File: src/Groups/matrices/transform_form.jl [hunk 3]
```diff
@@ -212,7 +212,7 @@ function _to_standard_form(B::MatElem{T}, _type::Symbol)  where T <: FinFieldEle
       # turn the elements on the main diagonal into 1
       for i in 1:n
          if A[i,i]!=0
-            lambda = _disc_log(w^(q+1),A[i,i])
+            lambda = disc_log(w^(q+1),A[i,i])
             Z[i,i] = w^-lambda
```
Comment (fingolfin) [inline src/Groups/matrices/transform_form.jl:216]: If I read this code correctly, what it really does is compute inverse of the `q+1`st root of `A[i,i]`, right? So I think it should perhaps not use `disc_log` at all.

Alas, this would only work if `root` (or something like that) worked for finite field elements, which doesn't seem to be the case, so this is more a remark for future work

File: src/NumberTheory/NmbThy.jl [hunk 4]
```diff
@@ -203,3 +203,20 @@ function factorisations(a::NfAbsOrdElem{AnticNumberField,nf_elem})
...
+# Input: b::T and x::T where {T <: FinFieldElem} and b and x are elements from
+#        the same finite field
+# Output: Integer s such that b^s = x
+#         If no such x exists, an error is thrown
+# Example:
+# julia> F = GF(3,4);
+# julia> a = gen(F)^21;
+# julia> Oscar.DiscreteLog.disc_log(gen(F), a)
+# > 21
+#
```
Comment (fingolfin) [inline src/NumberTheory/NmbThy.jl]: It would be good to turn this into a docstring comment, so that it can be accessed via `?disc_log` from the REPL, and can be inserted into the manual. Something like this:
````suggestion
@doc Markdown.doc"""
    disc_log(b::T, x::T) where {T <: FinFieldElem}

Return an integer `s` such that $b^s = x$.
If no such `x` exists, an exception is thrown.

# Examples
```jldoctest
julia> F = GF(3,4); a = gen(F)^21;

julia> Oscar.DiscreteLog.disc_log(gen(F), a)
21
```
````

File: test/Groups/operations.jl [hunk 5]
```diff
@@ -141,8 +141,8 @@ end
    F = GF(17, 1)
    a = F(3)
    b = F(13)
-   @test a^Oscar._disc_log(a,b)==b
-   @test_throws ErrorException Oscar._disc_log(b,a)
-   @test Oscar._disc_log(F(16),F(1))==0
-   @test_throws ErrorException Oscar._disc_log(b,F(0))
+   @test a^Oscar.disc_log(a,b)==b
+   @test_throws String Oscar.disc_log(b,a)
```
Comment (fingolfin) [inline test/Groups/operations.jl:145]: Wait, it throws strings? Ugh, indeed. That's a "bug" (IMHO) in the upstream code. Ah well, I'll submit a PR to Hecke for this

**Review by fingolfin — COMMENTED** [review]
Looks good to me except for the docstring. Thank you!

File: src/NumberTheory/NmbThy.jl [hunk 6]
```diff
@@ -203,3 +203,24 @@ function factorisations(a::NfAbsOrdElem{AnticNumberField,nf_elem})
...
 end
+
+
+################################################################################
+#
+#   disc_log
+#
+@doc Markdown.doc"""
+    disc_log(b::T, x::T) where {T <: FinFieldElem}
+Return an integer `s` such that $b^s = x$.
```
Comment (fingolfin) [inline src/NumberTheory/NmbThy.jl:215]:
```suggestion

Return an integer `s` such that $b^s = x$.
```

File: src/NumberTheory/NmbThy.jl [hunk 7]
```diff
@@ -203,3 +203,24 @@ function factorisations(a::NfAbsOrdElem{AnticNumberField,nf_elem})
...
+If no such `x` exists, an exception is thrown.
+# Examples (jldoctest)
+```
```
Comment (fingolfin) [inline src/NumberTheory/NmbThy.jl]:
````suggestion

# Examples
```jldoctest
````

File: src/NumberTheory/NmbThy.jl [hunk 8]
```diff
@@ -203,3 +203,24 @@ function factorisations(a::NfAbsOrdElem{AnticNumberField,nf_elem})
...
+julia> F = GF(3,4); a = gen(F)^21;
+julia> disc_log(gen(F), a)
```
Comment (fingolfin) [inline src/NumberTheory/NmbThy.jl:222]:
```suggestion

julia> disc_log(gen(F), a)
```
