### PR TITLE
Fix `sum` of `SubQuoModule`s when one summand is trivial

### LINKED ISSUE #5722: `sum(M::SubquoModule, N::SubquoModule)` throws an error for zero module
**Describe the bug**
`sum(M::SubquoModule{T},N::SubquoModule{T})` throws an error, if either `M` or `N` has no generators, i.e., is the zero module. 
This happens because of a forgotten type cast for the empty array of images of the generators when trying to create the inclusion morphism.

**To Reproduce**
```
using Oscar

R, (x,y) = QQ[:x,:y]
F = free_module(R,2)
M = SubquoModule(F, [x*F[1], y*F[2]])
O = SubquoModule(F, elem_type(F)[])
M + O
```

Here is the output:
```
julia> R, (x,y) = QQ[:x,:y]
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x, y])

julia> F = free_module(R,2)
Free module of rank 2 over R

julia> M = SubquoModule(F, [x*F[1], y*F[2]])
Submodule with 2 generators
  1: x*e[1]
  2: y*e[2]
represented as subquotient with no relations

julia> O = SubquoModule(F, elem_type(F)[])
Submodule with 0 generators
represented as subquotient with no relations

julia> M + O
ERROR: MethodError: no method matching SubQuoHom(::SubquoModule{QQMPolyRingElem}, ::SubquoModule{QQMPolyRingElem}, ::Vector{Any}; check::Bool)
The type `SubQuoHom` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  SubQuoHom(::SubquoModule, ::ModuleFP{T}, ::Vector{<:ModuleFPElem{T}}; check) where T
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules/SubQuoHom.jl:11
  SubQuoHom(::SubquoModule, ::ModuleFP{T}, ::Vector{<:ModuleFPElem{T}}, ::RingMapType; check) where {T, RingMapType}
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules/SubQuoHom.jl:12
  SubQuoHom(::SubquoModule, ::ModuleFP{T}, ::MatElem{T}; check) where T
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules/SubQuoHom.jl:20
  ...

Stacktrace:
 [1] sum(M::SubquoModule{QQMPolyRingElem}, N::SubquoModule{QQMPolyRingElem})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules/SubquoModule.jl:1319
 [2] +(M::SubquoModule{QQMPolyRingElem}, N::SubquoModule{QQMPolyRingElem})
   @ Oscar ~/Oscar.jl/src/Modules/UngradedModules/SubquoModule.jl:1426
 [3] top-level scope
   @ REPL[56]:1
```

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.7.0-DEV - #master, 4a1fb29c4c -- 2026-01-26 10:48:17 +0100
  combining:
    AbstractAlgebra.jl   v0.48.2
    GAP.jl               v0.16.3
    Hecke.jl             v0.39.10
    Nemo.jl              v0.54.0
    Polymake.jl          v0.13.6
    Singular.jl          v0.28.7
  building on:
    FLINT_jll                  v301.400.1+0
    GAP_jll                    v400.1500.100+1
    GAP_lib_jll                v400.1500.100+0
    Singular_jll               v404.101.503+0
    libpolymake_julia_jll      v0.14.4+0
    libsingular_julia_jll      v0.47.10+0
    polymake_jll               v400.1500.2+0
    polymake_oscarnumber_jll   v0.3.13+0
See `]st -m` for a full list of dependencies.

Julia Version 1.12.4
Commit 01a2eadb047 (2026-01-06 16:56 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 5500U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver2)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 12 virtual cores)
Official https://julialang.org release
...
```

**Additional context**
PR #5723 fixes this issue.

### PR DESCRIPTION
**Pull request by Syz-MS**
Fixes #5722, by adding the missing type cast for the empty array in the case of no generators.

### CODE REVIEW

File: test/Modules/UngradedModules.jl [hunk 1]
```diff
@@ -1944,3 +1944,14 @@ end
...
+@testset "Issue #5722" begin
+  R, (x,y) = QQ[:x,:y]
+  F = free_module(R,2)
+  M = SubquoModule(F, [x*F[1], y*F[2]])
+  O = SubquoModule(F, elem_type(F)[])
+
+  @test O + O == O
+  @test O + M != O
+  @test M + O == M
+end
```
Comment (lgoettgens) [inline test/Modules/UngradedModules.jl]:
```suggestion
end

```

**Review by HechtiDerLachs — APPROVED** [review]
Looks good. Thank you!
