### PR TITLE
Fix length of EnumerativeCombinatorics iterators

### LINKED ISSUE #5543: `Int` vs `BigInt` for `length` of combinatorial iterators
We have some iterators in `EnumerativeCombinatorics` that return a `BigInt` as their length, and a PR review brought up the question of whether this is useful / necessary.

These numbers can get quite large, for example `binomial(40,20)` is ~ 2^37.

Is an `Int` always 64 big in Julia or is it sometimes 32 bit depending on the system? And how reasonable is it to work with these iterators? We can collect `combinations(30,15)` (about 2^27 objects) in about 200 seconds, but about 95% of that is garbage collection time, we can iterate over it in 3 seconds with `inplace=true`.

### PR DESCRIPTION
**Pull request by mjrodgers**
Closes #5543

### CODE REVIEW

File: src/Combinatorics/EnumerativeCombinatorics/combinations.jl [hunk 1]
```diff
@@ -88,7 +88,14 @@ function number_of_combinations(n::IntegerUnion, k::IntegerUnion)
   return binomial(ZZ(n), ZZ(k))
 end
 
-Base.length(C::Combinations) = BigInt(number_of_combinations(C.n, C.k))
+function Base.length(C::Combinations)
+  try
+    return Int(number_of_combinations(Int(C.n), Int(C.k)))
+  catch e
+    print("Length is too large, use `number_of_combinations` instead\n")
+    rethrow(e)
```
Comment (fingolfin) [inline src/Combinatorics/EnumerativeCombinatorics/combinations.jl:96]: Hmm, should we perhaps check `e` to see if that's really due to a the length being too large, and in that case throw a new error? Like this (untested)
```suggestion
  catch e
    e isa InexactError && error("Length is too large, use `number_of_combinations` instead")
    rethrow(e)
```

**Comment by fingolfin** [comment]
Regarding PR labels: does this warrant a changelog entry? In that case the title should be tweaked to be a bit nicer. But I think it'd also be fine to omit it?

Perhaps triage can decide that, and also talk about what is done in this PR is fine as is, or if my suggestion regarding how the overflow is handled should be followed, or perhaps a third alternative comes up

**Comment by mjrodgers** [comment]
I agree personally, as did triage; we shouldn't give this message for every error (there are other possible errors that could occur). I'll commit your suggestion (and fix the other instances).

**Review by fingolfin — APPROVED** [review]
