### PR TITLE
Make the `@perm` macro more powerful by supporting more argument variants and increased consistency

### LINKED ISSUE #3010: Bug / missing feature in `@perm` macro
I wanted to enter two permutations in cycle notation and got an unexpected error:
```
julia> pis = [@perm (1,2), @perm (1,2)]
ERROR: MethodError: no method matching cperm(::Vector{Any})

Closest candidates are:
  cperm(::Array{Vector{T}, 1}) where T<:Union{Integer, ZZRingElem}
   @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Groups/perm.jl:306
  cperm(::AbstractVector{T}...) where T<:Union{Integer, ZZRingElem}
   @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Groups/perm.jl:284
  cperm(::PermGroup, ::Array{Vector{T}, 1}) where T<:Union{Integer, ZZRingElem}
   @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Groups/perm.jl:310
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[112]:1
```
I think OSCAR should accept this code, or at least give a more helpful error.

Ideally it would behave like this variant in which I used braces to enclose the macro arguments:
```
julia> pis = [@perm((1,2)), @perm((1,2))]
2-element Vector{PermGroupElem}:
 (1,2)
 (1,2)
```

I think the problem is that the expression is not over after  `(1,2)` because next comes a comma. A potential way to solve this might be to teach the macro to only handle the expressions it can, and then output any additional expressions verbatim as they came in.

However, I don't know how hard it'll be to actually pull this off...

### PR DESCRIPTION
**Pull request by lgoettgens**
Resolves https://github.com/oscar-system/Oscar.jl/issues/3010.

- `@perm n+1 [....]` works now; the docstring always stated it would, but some macro hygiene thing messed up the use of local variables inside the degree expression.
- `@perm G [(1,2,3,4)]` creates a list of perms with fixed parent `G`.
- `[@perm (1,2), @perm(3,4)]` and similar constructions (where julia infers weird scopes of things) now raise an explicit error.
- Complete feature parity for different versions. There are now 9 combinations based on the parent group (detect parent / given group / given degree of symmetric group) and the expression (single permutation, non-empty vector, non-empty tuple). The only ambiguity would be with the empty tuple, so we explicitly restrict vectors and tuple to be non-empty.

The release notes could include a compressed version of this list.

### CODE REVIEW

**Comment by lgoettgens** [comment]
> Right now we do support `@perm 6 [(1,2), (3,4), (5,6)]`
> 
> Perhaps we could also support
> 
> * `@perm [(1,2), (3,4), (5,6)]` returning a `Vector`
> * `@perm ((1,2), (3,4), (5,6))` returning a tuple
> 
> all while "guessing" the degree?

this is now the only thing missing from #3010, see https://github.com/oscar-system/Oscar.jl/issues/3010#issuecomment-2605164474 for my current problem.

**Comment by lgoettgens** [comment]
@fingolfin this now includes everything we discussed this afternoon

File: test/Groups/Permutations.jl [hunk 1]
```diff
@@ -37,13 +33,251 @@
...
+      ps = @perm [(1,4)(2,3)(6,5)]
+      @test ps isa Vector{PermGroupElem}
+      G = parent(ps[1])
+      @test degree(G) == 6
+      @test is_natural_symmetric_group(G)
+      @test ps == [@perm(G, (1,4)(2,3)(6,5))]
+      
+      ps = @perm [(1,2,3)(4,5), (6,2,3,1), (), (2,)(1,4)]
+      @test ps isa Vector{PermGroupElem}
+      @test allequal(parent, ps)
```
Comment (fingolfin) [inline test/Groups/Permutations.jl:138]: `allequal` requires Julia >= 1.8 and we still run some of these tests in Julia 1.6.

Perhaps we should provide an `allequal` implementation for older Julia versions?

File: src/Groups/perm.jl [hunk 2]
```diff
@@ -772,15 +779,36 @@ end
...
+
+If a group `G` is provided, the permutations are created as elements of `G`. This will
+raise an error if the permutations are not elements of `G`.
+
+If an integer `n` is provided, the permutations are created as elements of the
+symmetric group of degree `n`, i.e., `symmetric_group(n)`.
+
+Input a list of permutations in cycle notation, created as elements of the
+symmetric group of degree `n`, i.e., `symmetric_group(n)`, by invoking
+[`cperm`](@ref) suitably.
```
Comment (fingolfin) [inline src/Groups/perm.jl]: I am confused by this paragraph. Is this meant to suggest an alternative? Then make that explicit:
```suggestion
As an alternative to the `@perm` macro, the [`cperm`](@ref) function
also allows creating permutations as a product of cycles.
```

I would also move it to the end?

File: src/Groups/perm.jl [hunk 3]
```diff
@@ -772,15 +779,36 @@ end
...
+
+In the remaining case, the parent group is inferred to be the symmetric group
+with a degree of the highest integer referenced in `expr`. This may result in
+evalutating the expressions in the cycle entries multiple times, so it is
```
Comment (fingolfin) [inline src/Groups/perm.jl]:
```suggestion
evaluating the expressions in the cycle entries multiple times, so it is
```
OK for now, but we could avoid that, couldn't we? By storing the result of the evaluation immediately as vectors (of vectors), and then later e.g. passing those to `cperm`

File: src/Groups/perm.jl (hunk 2 above)
Comment (fingolfin) [reply src/Groups/perm.jl]: I just see that the example now also shows `cperm` and `perm`. OK, then perhaps this text should also mention (and ref) `perm` as an alternative to `@perm`?

**Review by fingolfin — APPROVED** [review]
Great! Some minor comments. Overall looks good.

File: src/Groups/perm.jl (hunk 3 above)
Comment (lgoettgens) [reply src/Groups/perm.jl]: We can only avoid it for the case of a single permutation, and indeed the previous code did. I removed that for the time being to reduce Tha number of case distinctions.
For the vector and tuple cases, we cannot let the cperm dispatch handle the detection. Consider e.g. `@perm [(1, 2), (3,4)]`. if we would delegate that to `cperm([1, 2])` and `cperm([3,4])`, then the parents would differ (`Sym(2)` vs. `Sym(4)`.

I have some ideas on how to avoid the double evaluation, but I need to think a bit more about it and test if it regressed performance for the case of just ints in all entries. Thus, I would like to move that to a follow-up PR

File: src/Groups/perm.jl (hunk 2 above)
Comment (lgoettgens) [reply src/Groups/perm.jl]: This was left from the previous docstring. I removed that and instead added a mention to `perm` and `cperm`.

File: test/Groups/Permutations.jl (hunk 1 above)
Comment (lgoettgens) [reply test/Groups/Permutations.jl:138]: Isn't this what `Compat.jl` is for? We already have it in the environment as a dependency of GAP.jl anyway. For the time being, I just import this one function in older julia versions.

(I don't understand why the 1.10 job succeeded, as the `allequal` dispatch with predicate was only added right before the 1.11 feature freeze)

Comment (benlorenz) [reply test/Groups/Permutations.jl:138]: > (I don't understand why the 1.10 job succeeded, as the `allequal` dispatch with predicate was only added right before the 1.11 feature freeze)

1.6 does not have `allequal` at all and fails, 1.10 does have it and since we load `Compat.jl` it adds that version to the existing function:
```julia
julia> allequal(
allequal(f, xs::Tuple) @ Compat ~/.julia/packages/Compat/gd6AI/src/Compat.jl:790
allequal(f, xs) @ Compat ~/.julia/packages/Compat/gd6AI/src/Compat.jl:789
allequal(r::AbstractRange) @ Base set.jl:537
allequal(c::Union{AbstractDict, AbstractSet}) @ Base set.jl:535
allequal(itr) @ Base set.jl:533
```
(this is julia 1.10 with Oscar master)

Comment (lgoettgens) [reply test/Groups/Permutations.jl:138]: Thanks for reminding me of https://github.com/JuliaLang/Compat.jl/issues/814. This indeed resolves my confusion.
