### PR TITLE
handles "+" and "*" for ideals on the Oscar side

### LINKED ISSUE #1495: Addition of ideals fails eventually when doing stuff with different orderings
Consider the following code:
```julia
R, (x,y) = QQ["x", "y"]
I = ideal(R, [x^2, y^2])
o = degrevlex([x])*degrevlex([y])
G = groebner_basis(I, ordering=o)
J = ideal(R, [x^7])
I + J   # This will complain
```

So what happens: The singular side of the ideal `I` is filled out with a Singular ring with the ordering `o`. But this is not the default ordering for `R` and for `J` the default ordering `degrevlex` will be chosen when filling out the singular side. Now for some reason, addition of ideals is implemented using the singular side and there it finds incompatible rings in the last line.

### PR DESCRIPTION
**Pull request by ederc**
This also fixes #1495 .

### CODE REVIEW

File: src/Rings/mpoly-ideals.jl [hunk 1]
```diff
@@ -112,9 +112,11 @@ ideal(x, y, z^2)
...
 """
 function Base.:+(I::MPolyIdeal{T}, J::MPolyIdeal{T}) where T
-  singular_assure(I)
-  singular_assure(J)
-  return MPolyIdeal(base_ring(I), I.gens.S + J.gens.S)
+  if base_ring(I) == base_ring(J)
+    return MPolyIdeal(unique(vcat(I.gens.O,J.gens.O)))
+  else
+    error("Not possible due to different base rings.")
+  end
```
Comment (tthsqe12) [inline src/Rings/mpoly-ideals.jl]: can you make a helper function `check_base_rings(I::MPolyIdeal{T}, J::MPolyIdeal{T}))` so this code can be written more cleanly as the following. This will help in the other functions that also require base ring checks.
```
  check_base_rings(I, J)
  return MPolyIdeal(unique(vcat(I.gens.O,J.gens.O)))
```

**Comment by tthsqe12** [comment]
Interesting test failures!

File: src/Rings/mpoly-ideals.jl [hunk 2]
```diff
@@ -112,9 +112,11 @@ ideal(x, y, z^2)
 ```
 """
 function Base.:+(I::MPolyIdeal{T}, J::MPolyIdeal{T}) where T
-  singular_assure(I)
-  singular_assure(J)
-  return MPolyIdeal(base_ring(I), I.gens.S + J.gens.S)
+  if base_ring(I) == base_ring(J)
+    return MPolyIdeal(unique(vcat(I.gens.O,J.gens.O)))
```
Comment (thofma) [inline src/Rings/mpoly-ideals.jl]:
```suggestion
    return MPolyIdeal(unique!(vcat(I.gens.O,J.gens.O)))
```

**Comment by thofma** [comment]
In the test:
```
I.gens.O = AbstractAlgebra.Generic.MPoly{QQAbElem{nf_elem}}[#undef, #undef]
```
:-(

File: src/Rings/mpoly-ideals.jl (hunk 1 above)
Comment (ederc) [reply src/Rings/mpoly-ideals.jl]: Will do so once I fixed the other problems.

**Comment by ederc** [comment]
@thofma There are even more things broken, that's a "Fass ohne Boden". Will take care of this later.

**Comment by ederc** [comment]
So `oscar_assure` for ideals was broken as it was still used with the deprecated gb interface. I disabled the generation of the Oscar side of corresponding gbs since this might have a bad impact on performance/memory. One should then call `oscar_assure` for the corresponding gb needed on the `BiPolyArray`,`IdealGens`, whatever this will be called in the (hopefully near) future. This is stuff I need to handle later on when `msolve` will provide more functionality and when we implement heuristics also depending on monomial orderings (see also #1487).

We remove zero generators from ideals iff the ideal is not the zero ideal itself.

We have now also a checker function testing if two ideals have the same base ring as @tthsqe12 requested.

Let's see what's now broken ;)

**Comment by ederc** [comment]
I have no idea why `PolyhedralGeometry/timing.jl` tests fail, and why only in two of the checks. I do not see the connection to the changes made in this PR.

**Comment by thofma** [comment]
The test took too long (this is what is tested). I have seen this fail before locally.

@lkastner @benlorenz Can we ignore this?

**Comment by tthsqe12** [comment]
This looks good to me.
