### PR TITLE
Remove broken tropical Groebner basis shortcut for binomial ideals

### LINKED ISSUE #4686: Initial ideal computed incorrectly?
I have run into cases where `initial(I::MPolyIdeal, nu::TropicalSemiringMap, w::Vector)` appears to give an incorrect output (for a homogeneous `I`). Specifically, in these cases there is a polynomial `p` in `I` whose initial form with respect to the same weight does not lie in the computed initial ideal. Below is an example, it is not very small because I've only encountered this in nontrivial (and randomly generated) cases. The code
```
R, x = graded_polynomial_ring(QQ, "x" => (1:5))
I = ideal(R,  x[1]*x[3]^2 - x[2]*x[4]^2, x[2]^6 - x[3]*x[4]^3*x[5]^2, x[1]*x[2]^5*x[3] - x[4]^5*x[5]^2)
p = x[4]^15*x[5]^2 - x[1]^6*x[3]^11 
p in I
```
outputs `true` but subsequently running
```
w = [1, 2, 0, 1, 1]
inI = initial(I, tropical_semiring_map(QQ, max), w)
initial(p, tropical_semiring_map(QQ, max), w) in inI
```
outputs `false` which does not make sense. The initial form `initial(p, tropical_semiring_map(QQ, max), w) ` is computed correctly as `x[4]^15*x[5]^2` so that's not the issue here. FWIW, the `I` in question is the homogeneous toric ideal defined by the point tuple `[[1, 5], [1, 1], [0, 0], [0, 2], [3, 0]]`, this helps visualizing the situation. 

This happens in Oscar 1.3.0 as well as older versions.

### PR DESCRIPTION
**Pull request by YueRen**
This broken shortcut was originally added in a joint project with Henriksson and Helminck.  The idea was that groebner_basis should not do anything for binomial ideals if the weight vector lies on the tropicalization (the weight vector test was missing).  While this is mathematically correct, it is on second thought not a good idea if groebner_basis for binomial ideals behaves differently than for general ideals, so I am taking this out.

The commit takes out the one-line shortcut and adjusts documentation and tests accordingly

Fixes https://github.com/oscar-system/Oscar.jl/issues/4686

### CODE REVIEW

**Comment by fingolfin** [comment]
@YueRen 
Thank you for this PR! Could you please have a look at https://docs.oscar-system.org/dev/DeveloperDocumentation/changelog/ and based on that set labels (if you have the permission) resp. post a comment indicating whether you think this should be mentioned in the release notes / changelog for the next OSCAR release, and in which section. If it should appear then please also edit the title to a format as suggested there.

**Comment by YueRen** [comment]
@fingolfin It is done, thanks for the reminder!

File: src/TropicalGeometry/groebner_basis.jl [hunk 1]
```diff
@@ -373,15 +373,15 @@ julia> w = [0,0];
...
- x^3 - 5*x^2*y
  -2*x^2*y + 3*y^3
+ 2*x^3 - 2*x^2*y - 12*y^3
 
 ```
 """
 function groebner_basis(I::MPolyIdeal, nu::TropicalSemiringMap, w::AbstractVector{<:Union{QQFieldElem,ZZRingElem,Rational,Integer}})
     G = gens(I)
     # Principal and binomial ideal shortcut, return G
-    if isone(length(G)) || all(isequal(2),length.(G))
```
Comment (joschmitt) [inline src/TropicalGeometry/groebner_basis.jl:384]: The comment on top of this line should also be adjusted, I think.

**Comment by joschmitt** [comment]
Maybe triage can find someone to review this (or just merge it).

File: src/TropicalGeometry/groebner_basis.jl [hunk 2]
```diff
@@ -373,15 +373,15 @@ julia> w = [0,0];
...
 2-element Vector{QQMPolyRingElem}:
- x^3 - 5*x^2*y
  -2*x^2*y + 3*y^3
+ 2*x^3 - 2*x^2*y - 12*y^3
 
 ```
 """
 function groebner_basis(I::MPolyIdeal, nu::TropicalSemiringMap, w::AbstractVector{<:Union{QQFieldElem,ZZRingElem,Rational,Integer}})
     G = gens(I)
     # Principal and binomial ideal shortcut, return G
```
Comment (fingolfin) [inline src/TropicalGeometry/groebner_basis.jl]:
```suggestion
    # Principal ideal shortcut, return G
```

**Review by fingolfin — APPROVED** [review]
Triage thinks this should be OK to merge.
