### PR TITLE
Fix `radical` for ideals in polynomial rings over the integers

### LINKED ISSUE #5175: Radical in ZZ[x1,x2] gives wrong output
**Describe the bug**
The following computation of the radical of an ideal gives the wrong result.

**To Reproduce**
Steps to reproduce the behavior, please provide a code snippet that triggers
the bug.
```
using Oscar
julia> R,(x,y) = polynomial_ring(ZZ,2)
(Multivariate polynomial ring in 2 variables over ZZ, ZZMPolyRingElem[x1, x2])

julia> radical(ideal(R,[y,2*x-1]))
Ideal generated by
  1
  x2
  2*x1 - 1
```

**Expected behavior**
The answer should be the ideal generated by x2 and 2x1-1 as 1 is not in the radical of this ideal.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.4.1
  combining:
    AbstractAlgebra.jl   v0.45.3
    GAP.jl               v0.13.4
    Hecke.jl             v0.36.2
    Nemo.jl              v0.50.4
    Polymake.jl          v0.12.2
    Singular.jl          v0.25.7
  building on:
    FLINT_jll                  v301.300.101+0
    GAP_jll                    v400.1400.5+2
    GAP_lib_jll                v400.1400.4+0
    Singular_jll               v404.100.109+0
    libpolymake_julia_jll      v0.13.5+0
    libsingular_julia_jll      v0.47.5+1
    polymake_jll               v400.1300.4+0
    polymake_oscarnumber_jll   v0.3.8+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.2
Commit bd47eca2c8* (2024-03-01 10:14 UTC)
Build Info:
  Built by Homebrew (v1.10.2)

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: macOS (x86_64-apple-darwin22.6.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, westmere)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Built by Homebrew (v1.10.2)
...
```

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
Resolves #5175.

### CODE REVIEW

**Comment by thofma** [comment]
It seems that doctests need to be adjusted.

File: src/Rings/mpolyquo-localizations.jl [hunk 1]
```diff
@@ -1600,7 +1600,14 @@ function simplify(L::MPolyLocRing{<:Any, <:Any, <:Any, <:Any, <:MPolyPowersOfEle
   return Lnew, hom(L, Lnew, f), hom(Lnew, L, finv, check=false)
 end
 
+# The `simplify` routine uses Singular's "elimpart". This does not work
```
Comment (fingolfin) [inline src/Rings/mpolyquo-localizations.jl:1603]: I think this comment should be attached to the *next* method, as the method it documents right now does not call into Singular at all?

**Comment by fingolfin** [comment]
Looks plausible to me but someone from geometry should review & approve :-)

**Comment by wdecker** [comment]
I cannot (yet) see, why the proposed change causes the changes in the doctest example which makes the tests fails. The difference is, that now some redundant generators are removed. @HechtiDerLachs?

**Comment by thofma** [comment]
I think they just got reordered?

**Comment by wdecker** [comment]
> I think they just got reordered?

Yes, you are right. But still, what caused this reordering?

**Comment by HechtiDerLachs** [comment]
> what caused this reordering?

Before, we were using a preprocessing step which attempted to eliminate variables where applicable. This apparently does not work over the integers, so it has been cut off, leading to different results as the radical is now tentatively computed in a different ring.

**Comment by wdecker** [comment]
> > what caused this reordering?
> 
> Before, we were using a preprocessing step which attempted to eliminate variables where applicable. This apparently does not work over the integers, so it has been cut off, leading to different results as the radical is now tentatively computed in a different ring.

Not quite. The difference arises from how we define the identity map as shown in the example below:
```julia_repl
julia> R, (x,y) = polynomial_ring(ZZ, [:x, :y]);

julia> I = ideal(R, [x^2,y^2]);

julia> L, _ = quo(R, I);

julia> f = identity_map(L);

julia> f(x^2)
x^2

julia> g = hom(L, L, [x, y]);

julia> g(x^2)
0

julia> g == f
true
```
@thofma Any comment?

**Comment by HechtiDerLachs** [comment]
> Not quite. The difference arises from how we define the identity map as shown in the example below:

I do not understand the concern. Both versions of the identity map are correct. The difference observed in your example stems from different selections of the representative used for printing. I suspect `f` to not be of type `MPolyAnyMap` and use a different dispatch for mapping elements. Yet, I do not see anything that's wrong with this. 

The given generators for the radical ideal in one of the doctests appear in different order compared to the earlier version. What's wrong with that? What is the issue? What is the concern? 

As far as I can see, we do not even get a mathematically different result in the doctest's examples. While the example provided in the issue now works correctly.

**Comment by thofma** [comment]
I agree with @HechtiDerLachs. Everything is mathematically correct now, so we should get this in sooner than later.

The thing  with `identity_map(L)` doing funny things is one of the complaints in https://github.com/oscar-system/Oscar.jl/issues/5188. It is actually not constructing the object you would expect (try asking `kernel` of it).

**Review by wdecker — APPROVED** [review]
I did not want to hold up things, but wanted to be sure that there is no hidden problem. I understand now.

**Comment by thofma** [comment]
Thanks @HechtiDerLachs
