### PR TITLE
Make `print_constraints` use ASCII as default

### LINKED ISSUE #2820: `facets` uses unicode symbols
**Describe the bug**
Output of `facets` uses unicode symbols.

**To Reproduce**

```julia
julia> c = cube(3)
Polyhedron in ambient dimension 3

julia> facets(c)
6-element SubObjectIterator{AffineHalfspace{QQFieldElem}} over the Halfspaces of R^3 described by:
-x₁ ≦ 1
x₁ ≦ 1
-x₂ ≦ 1
x₂ ≦ 1
-x₃ ≦ 1
x₃ ≦ 1
```

**Expected behavior**
Unicode should be avoided as per https://docs.oscar-system.org/dev/DeveloperDocumentation/styleguide/#Unicode

**System (please complete the following information):**

```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.13.1-DEV
  combining:
    AbstractAlgebra.jl   v0.31.1
    GAP.jl               v0.9.8
    Hecke.jl             v0.20.3
    Nemo.jl              v0.35.3
    Polymake.jl          v0.11.5
    Singular.jl          v0.18.14
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.7+0
    GAP_jll                 v400.1200.200+6
    Singular_jll            v403.208.800+0
    libpolymake_julia_jll   v0.10.4+0
    libsingular_julia_jll   v0.40.2+0
    polymake_jll            v400.1000.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = :/usr/local/lib:/usr/local/lib
Official https://julialang.org/ release
```

**Additional context**
https://docs.oscar-system.org/dev/DeveloperDocumentation/styleguide/#Printing-in-Oscar
This is probably the printing of `AffineHalfspace` or something similar that needs to be modified.

### PR DESCRIPTION
**Pull request by alexej-jordan**
Following the conventions on printing in Oscar, `print_constraints`, which was used in several different contexts, now uses ASCII as long as `Oscar.is_unicode_allowed() == false`, and uses Unicode otherwise.

Docstrings have been adjusted/extended accordingly.

`_constraint_string(x::FieldElem) = string("(", x, ")")` also places parentheses around single `FieldElem`s. This is because e.g. an `EmbeddedElem{nf_elem}` as a factor of `x_1` should print as `(-1//2*sqrt(5) - 1//2)*x_1` instead of `-1//2*sqrt(5) - 1//2*x_1`. This behaviour can be refined in the future, e.g. for specific `FieldElem` types or probably even specific instances.

This PR resolves #2820

### CODE REVIEW

File: src/PolyhedralGeometry/Polyhedron/properties.jl [hunk 1]
```diff
@@ -1246,93 +1246,107 @@ function support_function(P::Polyhedron{T}; convention = :max) where T<:scalar_t
...
-                end
-                first = false
-            end
-        end
-        if first
-            if b[i] >= 0 && !trivial
-                continue
-            end
-            terms[1] = "0"
+function print_constraints(A::AnyVecOrMat, b::AbstractVector; trivial::Bool = false, numbered::Bool = false, io::IO = stdout, cmp::Symbol = :lte)
```
Comment (lgoettgens) [inline src/PolyhedralGeometry/Polyhedron/properties.jl]: The julia style guide states that `IO` arguments come first (see https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base). I don't know if we should follow that here

Comment (alexej-jordan) [reply src/PolyhedralGeometry/Polyhedron/properties.jl]: This looks applicable here, thank you for bringing that up!

**Review by benlorenz — APPROVED** [review]
