### PR TITLE
Serialize `:cyclo` attribute for `AbsSimpleNumField`

### LINKED ISSUE #5466: Cyclotomic fields forget that they are cyclotomic during serialization
Consider this:
```
julia> K, a = cyclotomic_field(3, :a);

julia> L, b = cyclotomic_field(12, :b);

julia> L(a) # One can cast elements of K in L because they are "compatible" cyclotomic fields
b^2 - 1

julia> save("K", K)

julia> save("L", L)
```
Now load both fields in a new session:
```
julia> K = load("K")
Number field with defining polynomial _$^2 + _$ + 1
  over rational field

julia> L = load("L")
Number field with defining polynomial _$^4 - _$^2 + 1
  over rational field

julia> L(gen(K))
ERROR: no coercion possible
[...]
```
The information that `L` and `K` are cyclotomic is lost during serialization.

In the end, one only needs to make sure that the attribute `:cyclo` is serialized, so one can do
```
@register_serialization_type AbsSimpleNumField uses_id [:cyclo]
```
(The serialized fields will still not print like "proper" cyclotomic fields, but that's just a cosmetic issue.)

My question is: Could this be the default `@register_serialization_type` for number fields? Or is there some policy to not serialize any not-strictly-necessary attributes by default?

### PR DESCRIPTION
**Pull request by joschmitt**
Since so far there was no big outcry, this implements the solution I proposed in #5466 .
~Unfortunately, I don't see how this can be tested; if one saves and loads a cyclotomic field *in the same session* then the "cyclotomic-ness" is remembered also without this pull request.~

### CODE REVIEW

**Comment by benlorenz** [comment]
You should be able to test this by calling `Oscar.Serialization.reset_global_serializer_state()` before loading the files again. It should behave the same way as opening a new session, e.g. with current master:
```julia
julia> K, a = cyclotomic_field(3, :a);

julia> L, b = cyclotomic_field(12, :b);

julia> L(a) # One can cast elements of K in L because they are "compatible" cyclotomic fields
b^2 - 1

julia> b^2 - 1
b^2 - 1

julia> save("K", K)

julia> save("L", L)

julia> Oscar.Serialization.reset_global_serializer_state()
Dict{Base.UUID, Any}()

julia> K = load("K")
Number field with defining polynomial _$^2 + _$ + 1
  over rational field

julia> L = load("L")
Number field with defining polynomial _$^4 - _$^2 + 1
  over rational field

julia> L(gen(K))
ERROR: no coercion possible
Stacktrace:
 [1] error(s::String)
```
(Without the reset the field is recognized by the uuid that is generated during save and then not loaded at all, the reset will clear this uuid cache)

**Comment by antonydellavecchia** [comment]
But do you mean tested as in inside one of our tests? you can pass a check_func to test_save_load_roundtrip that can check for example if your field knows it's cyclotomic after being loaded into a fresh session

**Comment by joschmitt** [comment]
Thank you @benlorenz and @antonydellavecchia !
I added a test now. I'm not really sure this is the "right" way to do it though.

(I tried to add another `func(loaded)` into `test_save_load_roundtrip` around here https://github.com/oscar-system/Oscar.jl/blob/d9282d2243b763abbd08a950fe1fcc7c13512efd/test/Serialization/setup_tests.jl#L61 , but this made a lot of unrelated tests fail, so I assume that's not the way it is "supposed" to be used.)

File: test/Serialization/Fields.jl [hunk 1]
```diff
@@ -39,5 +39,12 @@
         @test loaded isa QQBarField
       end
     end
+
+    @testset "Cyclotomic fields" begin
+      K, _ = cyclotomic_field(3)
+      test_save_load_roundtrip(path, K, check_func = x -> Hecke.is_cyclotomic_type(x)[1]) do loaded
+        @test Hecke.is_cyclotomic_type(loaded)[1]
```
Comment (antonydellavecchia) [inline test/Serialization/Fields.jl]: this test is checking in the same session, so we aren't really testing anything here, only the `check_func` is testing on a new session

**Review by antonydellavecchia — APPROVED** [review]

File: test/Serialization/Fields.jl (hunk 1 above)
Comment (joschmitt) [reply test/Serialization/Fields.jl]: Okay, I changed the "second function" to just check equality, to make sure there is no confusion.

File: test/Serialization/Fields.jl [hunk 2]
```diff
@@ -39,5 +39,12 @@
         @test loaded isa QQBarField
       end
     end
+
+    @testset "Cyclotomic fields" begin
+      K, _ = cyclotomic_field(3)
+      test_save_load_roundtrip(path, K, check_func = x -> Hecke.is_cyclotomic_type(x)[1]) do loaded
```
Comment (antonydellavecchia) [inline test/Serialization/Fields.jl]: Don't we need a semi colon here for kwargs?
```suggestion
      test_save_load_roundtrip(path, K; check_func = x -> Hecke.is_cyclotomic_type(x)[1]) do loaded
```

Comment (joschmitt) [reply test/Serialization/Fields.jl]: I don't think it is needed, but let's put it :)
