### PR TITLE
1719 serialization problems with cyclotomic fields

### LINKED ISSUE #1719: Serialization problems with cyclotomic fields
1. The functions save/load do not save correctly if the ground field was a cyclotomic field.

```
julia> K,ζ=cyclotomic_field(6)
(Cyclotomic field of order 6, z_6)

julia> x=ζ+1
z_6 + 1

julia> save("varx.jl",x)
2117

julia> y=load("varx.jl")
z_6 + 1

julia> parent(x)
Cyclotomic field of order 6

julia> parent(y)
Number field over Rational Field with defining polynomial _$^2 - _$ + 1

julia> z=load("varx.jl",typeof(x))
z_6 + 1

julia> parent(z)
Number field over Rational Field with defining polynomial _$^2 - _$ + 1
```

2. Furthermore specifying a parent with matrices does not seem to be supported right now. 

```
julia> K,ζ=cyclotomic_field(6)
(Cyclotomic field of order 6, z_6)

julia> T=matrix(K,2,2,[1 ζ; ζ ζ^2])
[  1       z_6]
[z_6   z_6 - 1]

julia> parent(T)
Matrix Space of 2 rows and 2 columns over K

julia> save("testsave.jl",T)
4036

julia> TT=load("testsave.jl")
[  1       z_6]
[z_6   z_6 - 1]

julia> parent(TT)
Matrix Space of 2 rows and 2 columns over Number field over Rational Field with defining polynomial _$^2 - _$ + 1

julia> T*TT
[    z_6   z_6 - 1]
[z_6 - 1        -1]

julia> TT[1,2]*T[1,2]
ERROR: no common parent known
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] force_op(::typeof(*), ::Type{Val{true}}, ::nf_elem, ::Vararg{nf_elem, N} where N)
   @ Hecke ~/.julia/packages/Hecke/KyG8x/src/NumField/NfAbs/NfAbs.jl:1224
 [3] force_op
   @ ~/.julia/packages/AbstractAlgebra/ZmWFo/src/AbstractAlgebra.jl:318 [inlined]
 [4] *(a::nf_elem, b::nf_elem)
   @ Nemo ~/.julia/packages/Nemo/syxmO/src/antic/nf_elem.jl:337
 [5] top-level scope
   @ REPL[60]:1

julia> TTT=load("testsave.jl",parent=parent(T))
ERROR: MethodError: no method matching load_internal_with_parent(::Oscar.DeserializerState, ::Type{MatElem}, ::Dict{Symbol, Any}, ::AbstractAlgebra.Generic.MatSpace{nf_elem})
Closest candidates are:
  load_internal_with_parent(::Oscar.DeserializerState, ::Type{Vector{T} where T}, ::Dict, ::Any) at /home/rogel/.julia/packages/Oscar/W7C5G/src/Serialization/containers.jl:35
  load_internal_with_parent(::Oscar.DeserializerState, ::Type{Vector{T}}, ::Dict, ::Any) where T at /home/rogel/.julia/packages/Oscar/W7C5G/src/Serialization/containers.jl:20
  load_internal_with_parent(::Oscar.DeserializerState, ::Type{var"#s262"} where var"#s262"<:Union{fmpz_laurent_series, Union{AbstractAlgebra.Generic.LaurentSeriesFieldElem{T}, AbstractAlgebra.Generic.LaurentSeriesRingElem{T}} where T<:RingElement}, ::Dict, ::Any) at /home/rogel/.julia/packages/Oscar/W7C5G/src/Serialization/Rings.jl:457
  ...
Stacktrace:
 [1] load_type_dispatch(s::Oscar.DeserializerState, ::Type{MatElem}, dict::Dict{Symbol, Any}; parent::AbstractAlgebra.Generic.MatSpace{nf_elem})
   @ Oscar ~/.julia/packages/Oscar/W7C5G/src/Serialization/main.jl:150
 [2] load_unknown_type(s::Oscar.DeserializerState, dict::Dict{Symbol, Any}; parent::AbstractAlgebra.Generic.MatSpace{nf_elem}, check_namespace::Bool)
   @ Oscar ~/.julia/packages/Oscar/W7C5G/src/Serialization/main.jl:181
 [3] load(io::IOStream; parent::AbstractAlgebra.Generic.MatSpace{nf_elem})
   @ Oscar ~/.julia/packages/Oscar/W7C5G/src/Serialization/main.jl:264
 [4] #3417
   @ ~/.julia/packages/Oscar/W7C5G/src/Serialization/main.jl:269 [inlined]
 [5] open(f::Oscar.var"#3417#3418"{AbstractAlgebra.Generic.MatSpace{nf_elem}}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Base ./io.jl:330
 [6] open
   @ ./io.jl:328 [inlined]
 [7] #load#3416
   @ ~/.julia/packages/Oscar/W7C5G/src/Serialization/main.jl:268 [inlined]
 [8] top-level scope
   @ REPL[61]:1

```

Here it is notable, that multiplication of T and TT does work, but multiplication of the entries does not work.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.11.0
  combining:
    AbstractAlgebra.jl   v0.27.6
    GAP.jl               v0.8.5
    Hecke.jl             v0.15.8
    Nemo.jl              v0.32.4
    Polymake.jl          v0.8.2
    Singular.jl          v0.14.0
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.1+0
    GAP_jll                 v400.1192.2+1
    Singular_jll            v403.101.400+0
    libpolymake_julia_jll   v0.8.3+0
    libsingular_julia_jll   v0.27.0+0
    polymake_jll            v400.700.1+1
See `]st -m` for a full list of dependencies.

Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Official https://julialang.org/ release

...
```

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Fixes for loading matrices in parent ring
resolves #1719

### CODE REVIEW

File: src/Serialization/main.jl [hunk 1]
```diff
@@ -240,11 +240,13 @@ function save(filename::String, obj::Any)
...
 """
-    load(io::IO)
-    load(filename::String)
+    load(io::IO; parent::Any = nothing)
+    load(filename::String; parent::Any = nothing)
 
 Load the object stored in the given io stream
 respectively in the file `filename`.
+An optional parameter `parent` can be passed, this will 
+load the file as an element of the parent.
```
Comment (fingolfin) [inline src/Serialization/main.jl]: So, what are the rules: the JSON file must contain a single object at the top level, for which `parent` will be used as the parent? So if I have a `Vector` of ring elements, then this doesn't work, right? (Because we have no "parent" for `Vector` instances)

File: src/Serialization/main.jl [hunk 2]
```diff
@@ -255,6 +257,21 @@ julia> save("/tmp/fourtitwo.json", 42);
...
+julia> p = x^2 - x + 1
+x^2 - x + 1
+
+julia> save("/tmp/p.json", p)
+1204
+
+julia> p_loaded = load("/tmp/p.json", parent=R)
+x^2 - x + 1
+
+julia> p_loaded == p
```
Comment (fingolfin) [inline src/Serialization/main.jl]: Perhaps instead or in addition test `parent(p_loaded) === R` ?

File: src/Serialization/Rings.jl [hunk 3]
```diff
@@ -239,6 +239,14 @@ function load_internal(s::DeserializerState,
     return matrix(entries_ring, mat)
 end
 
+function load_internal_with_parent(s::DeserializerState,
```
Comment (fingolfin) [inline src/Serialization/Rings.jl:237]: Can we also get a test for this new function, to verify it now works as desired? 

Also, does this PR resolve issue #1719? If so, please add `resolves #1719` to the PR description, then it'll automatically close that issue once it gets merged :-)

File: src/Serialization/main.jl [hunk 4]
```diff
@@ -240,11 +240,15 @@ function save(filename::String, obj::Any)
...
-    load(io::IO)
-    load(filename::String)
+    load(io::IO; parent::Any = nothing)
+    load(filename::String; parent::Any = nothing)
 
 Load the object stored in the given io stream
 respectively in the file `filename`.
+An optional parameter `parent` can be passed. This will
+load the file as an element of the parent, or for container types
+such as Vector and Tuple it will load the entries as elements of the
```
Comment (fingolfin) [inline src/Serialization/main.jl]:
```suggestion
such as `Vector` and `Tuple` it will load the entries as elements of the
```

Comment (fingolfin) [reply src/Serialization/main.jl]: That's really cool, I wasn't aware -- so it's great this is mentioned. Perhaps we can also add an example for that?

Comment (fingolfin) [reply src/Serialization/main.jl]: Note that `load(io::IO, T::Type; parent=nothing)` also supports the `parent` keyword argument, but its docstring doesn't mention that. This should be fixed -- but I guess it's fine to refer here "for details".

Alternatively (and perhaps preferably?) the two docstrings could be merged. Then the type argument could be presented as an optional argument that, if given, is used to select the correct type for the result (and if that's not possible, then presumably an error is thrown?)

**Review by fingolfin — CHANGES_REQUESTED** [review]
Thank you, this goes in the right direction; but a test case for the new `MatElm` support would be good, plus some more remarks on the docstring.

File: src/Serialization/main.jl (hunk 4 above)
Comment (antonydellavecchia) [reply src/Serialization/main.jl:250]: throw an error? or maybe we just default to the unknown type case and throw a warning?

File: src/Serialization/Rings.jl [hunk 5]
```diff
@@ -226,19 +226,31 @@ end
 @registerSerializationType(nmod_mat)
 
 function save_internal(s::SerializerState, m::MatrixElem)
+    m_base_ring = save_type_dispatch(s, base_ring(parent(m)))
     return Dict(
         :matrix => save_type_dispatch(s, Array(m)),
+        :base_ring => m_base_ring
```
Comment (fingolfin) [inline src/Serialization/Rings.jl]:
```suggestion
    return Dict(
        :base_ring => save_type_dispatch(s, base_ring(parent(m))),
        :matrix => save_type_dispatch(s, Array(m)),
```

File: src/Serialization/Rings.jl [hunk 6]
```diff
@@ -226,19 +226,31 @@ end
...
-    entries_ring = parent(mat[1])
+
     return matrix(entries_ring, mat)
 end
 
+function load_internal_with_parent(s::DeserializerState,
+                                   ::Type{<: MatElem},
+                                   dict::Dict,
+                                   parent_ring::T) where T <: MatSpace
+    _ = load_unknown_type(s, dict[:base_ring])
```
Comment (fingolfin) [inline src/Serialization/Rings.jl]: Why do we even load the ring here, when we don't intend to use it?

File: src/Serialization/main.jl [hunk 7]
```diff
@@ -240,11 +240,17 @@ function save(filename::String, obj::Any)
 end
 
 """
-    load(io::IO)
-    load(filename::String)
+    load(io::IO; parent::Any = nothing, T::Type = nothing)
+    load(filename::String; parent::Any = nothing, T::Type =  nothing)
```
Comment (fingolfin) [inline src/Serialization/main.jl]: Perhaps `type` would be a better name than `T` ?

File: src/Serialization/main.jl [hunk 8]
```diff
@@ -240,11 +240,17 @@ function save(filename::String, obj::Any)
...
 
 Load the object stored in the given io stream
 respectively in the file `filename`.
+The optional parameter `parent` can be passed. This will
+load the file as an element of the parent, or for container types
+such as `Vector` and `Tuple` it will load the entries as elements of the
+passed `parent`.
```
Comment (fingolfin) [inline src/Serialization/main.jl]: That a parameter can be passed seems rather self-evident ;-). Also, the source
may not be a file. Perhaps:
```suggestion

If `parent` is specified, then the root object of the loaded data
either will have this as its parent, or it is a container such as
`Vector` and `Tuple`, then the parent of the entries will be set to `parent`.
```

File: src/Serialization/main.jl [hunk 9]
```diff
@@ -240,11 +240,17 @@ function save(filename::String, obj::Any)
...
+The optional parameter T can be passed. This will attempt to load the file as
+the passed type, and otherwise throw an error.
```
Comment (fingolfin) [inline src/Serialization/main.jl]:
```suggestion

If a type `T` is given then attempt to load the root object of the data
being loaded with this type; if this fails, an error is thrown.
```

File: src/Serialization/Rings.jl (hunk 5 above)
Comment (antonydellavecchia) [reply src/Serialization/Rings.jl]: the reason i run save_type_dispatch outside is so that it runs first, running it inside Dict does not guarantee the order, and it is important for backref purposes to have the base_ring outside

File: src/Serialization/Rings.jl (hunk 6 above)
Comment (antonydellavecchia) [reply src/Serialization/Rings.jl]: this is similar to other methods where I load a parent or a base and don't use it. It happens when loading with a given parent, and it is due to certain backrefs being stored in the base and or parent. I'll add comment so this is clearer, and I make sure there are comment where it happens else where as well.

File: src/Serialization/main.jl (hunk 8 above)
Comment (antonydellavecchia) [reply src/Serialization/main.jl]: yikes, sorry, that's embarrassing, thanks!

File: src/Serialization/Rings.jl (hunk 3 above)
Comment (antonydellavecchia) [reply src/Serialization/Rings.jl:237]: The matrix tests cover these lines now, I don't know why the warning is still here?

File: src/Serialization/Fields.jl [hunk 10]
```diff
@@ -510,10 +513,11 @@ function load_internal_with_parent(s::DeserializerState,
...
     rational_rep = load_type_dispatch(s, fmpq, dict[:rational_rep])
-    parent_field = load_type_dispatch(s, FlintPadicField, dict[:parent])
+    elem_precision = load_type_dispatch(s, Int64, dict[:precision])
 
-    # padic num precision is 1 higher than the field it lies in
-    if precision(parent_field) > precision(parent)
+    # this test should be moved in future ideally higher in the tree and possibly
+    # for all types that have precision
+    if elem_precision + 1 > precision(parent)
         @warn("Precision Warning: given parent is less precise than serialized parent",
```
Comment (fingolfin) [inline src/Serialization/Fields.jl]: Is this warning even accurate, though? In `elem_precision` we stored the precision of the original value `n`, which may already back then have been different than the precision of its parent. The precision in the parent is only the *default* precision of a q-adic, AFAIK

File: src/Serialization/Rings.jl (hunk 5 above)
Comment (fingolfin) [reply src/Serialization/Rings.jl]: You are not running it "in" the dict, but rather in the argument list of the function `Dict`. While it is true that the order of key-value pairs in a dictionary is arbitrary, the evaluation order of function argument is still fixed and fully deterministic.

Comment (antonydellavecchia) [reply src/Serialization/Rings.jl]: Ah I see, I didn't realise the order of execution is bottom up, so I just assumed it was arbitrary.

File: src/Serialization/Fields.jl (hunk 10 above)
Comment (antonydellavecchia) [reply src/Serialization/Fields.jl]: yes, the element can actually be more precise than it's parent. So we never actually lose information from the file. So I'll just remove warning.

**Review by fingolfin — APPROVED** [review]
