### PR TITLE
Change `root_of_unity(K::QQAbField, n::Int)` to return always the root corresponding to $\exp(2\pi i/n)$

### LINKED ISSUE #5069: `root_of_unity` is inconsistent for the abelian and algebraic closure of `QQ`
**Describe the bug**
The `root_of_unity` function returns false results when applied to the abelian closure of the rational numbers.

**To Reproduce**

```
julia> K,z=abelian_closure(QQ)
(Abelian closure of rational field, Generator of abelian closure of rational field)

julia> root_of_unity(K, 6)
-zeta(3)

```

**Expected behavior**
In the above case I would be fine with `root_of_unity(K, 6)` returning either of the following: `zeta(6)`, `-zeta(3)^2`, `zeta(3) + 1`.

**System (please complete the following information):**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.4.1
  combining:
    AbstractAlgebra.jl   v0.45.2
    GAP.jl               v0.13.4
    Hecke.jl             v0.36.1
    Nemo.jl              v0.50.3
    Polymake.jl          v0.12.1
    Singular.jl          v0.25.5
  building on:
    FLINT_jll                  v301.300.100+0
    GAP_jll                    v400.1400.5+1
    GAP_lib_jll                v400.1400.4+0
    Singular_jll               v404.100.108+0
    libpolymake_julia_jll      v0.13.4+1
    libsingular_julia_jll      v0.47.4+1
    polymake_jll               v400.1300.4+0
    polymake_oscarnumber_jll   v0.3.7+1
See `]st -m` for a full list of dependencies.

Julia Version 1.11.5
Commit 760b2e5b739 (2025-04-14 06:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Opteron(tm) Processor 6380
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, bdver1)
Threads: 1 default, 0 interactive, 1 GC (on 32 virtual cores)
Official https://julialang.org/ release
```

**Additional context**

Just for reference this is what happens for the algebraic closure of the rational numbers:
```
julia> F=algebraic_closure(QQ)
Algebraic closure of rational field

julia> root_of_unity(F, 6)
Root 0.500000 + 0.866025*im of x^2 - x + 1

julia> root_of_unity(F, 6) == root_of_unity(F, 3) + 1
true

julia> root_of_unity(F, 6) == -root_of_unity(F, 3)^2
true

julia> root_of_unity(F, 6) == -root_of_unity(F, 3)
false

```

### PR DESCRIPTION
**Pull request by ThomasBreuer**
The result shall correspond to $\exp(2\pi i/n)$, also if `mod(n, 4) = 2` holds, in order to be consistent with roots in the algebraic closure of `QQ`.

This change is breaking in the sense that `root_of_unity` (and `z`) return different elements than before.

resolves #5069

As far as I understand, the idea of the old code was to create the `n`-th root in the minimal possible cyclotomic field,
which is the `n/2`-th cyclotomic field if `mod(n, 4) = 2` holds. (This idea is kept also in the current pull request.)
Under this assumption, one has to compute some power in order to get the root that corresponds to $\exp(2\pi i/n)$;
perhaps the idea was to avoid this powering; in order to get *some* primitive `n`-th root of unity, it is enough to negate a given primitive `n/2`-th root of unity.

### CODE REVIEW

File: src/Rings/AbelianClosure.jl [hunk 1]
```diff
@@ -233,40 +236,51 @@ Hecke.data(a::QQAbFieldElem) = a.data
...
-    return QQAbFieldElem{AbsSimpleNumFieldElem}(z, c)
-  else
-    return QQAbFieldElem{AbsSimpleNumFieldElem}(-z, c)
+  if c != n
+    z = -z^div(c+1, 2)
   end
+  return QQAbFieldElem{AbsSimpleNumFieldElem}(z, c)
 end
 
 function root_of_unity(K::QQAbField{AbsNonSimpleNumField}, n::Int)
```
Comment (fingolfin) [inline src/Rings/AbelianClosure.jl]: Isn't this function identical to the preceding one except for the type parameter? Can't we do this
```suggestion
function root_of_unity(K::QQAbField{T}, n::Int) where T
```
and then just modify the return statement to use `T` to get a single function?

**Review by fingolfin — APPROVED** [review]

**Comment by fingolfin** [comment]
Removed the `breaking` label (which prevents merging): while this is breaking in so far as it might affect existing code which relied on `root_of_unity` returning specific values, it is not `breaking` in the more strict sense we consider for our decisions on what we can and can not include in a release: we did not promise any particular root being returned so code relying on us doing so was in error. In so far this change is an enhancement: it (a) aligns the behaviour of several `root_of_unity` methods to match, and (b) adds a guarantee to these return values.

Nevertheless, in the release notes it would be good to "highlight" this as a a change users may need to adapt to: "If your code is using `root_of_unity` for `QQAbField`, be advised that ..."

@lgoettgens @aaruni96 @benlorenz it seems to me we need some refinement for the release notes labels:
- is this an `enhancement`? It seems more like a "clarification" or "general change"...
- is the current handling of `breaking` as "can not be merged" useful? Should we perhaps repurpose it to what I describe above? Or should we perhaps add a new label for that, say `requires user attention` or so... to be listed in a section "If you are coming from an older OSCAR version, watch out for the following ..."
