### PR TITLE
Fixes bug with loading vectorof Fields

### LINKED ISSUE #3531: Serialization (loading) failing for Vector
We can serialize/deserialize `AbsSimpleNumField` but not `Vector{AbsSimpleNumField}`.

```julia
julia> using Oscar

julia> K, a = quadratic_field(2);

julia> io = IOBuffer(); Oscar.save(io, K); seekstart(io); Oscar.load(io) === K
true

julia> typeof([K, K])
Vector{AbsSimpleNumField} (alias for Array{AbsSimpleNumField, 1})

julia> io = IOBuffer(); Oscar.save(io, [K, K]); seekstart(io); Oscar.load(io)
┌ Warning: Attempting to load file stored using a DEV version with commit 693a3e47a1610cac7e7ca94979bf42740bd133d2
└ @ Oscar ~/s/Oscar/src/Serialization/main.jl:610
ERROR: MethodError: no method matching load_ref(::Oscar.DeserializerState, ::String)

Closest candidates are:
  load_ref(::Oscar.DeserializerState)
   @ Oscar ~/s/Oscar/src/Serialization/serializers.jl:143

Stacktrace:
  [1] (::Oscar.var"#5799#5800"{Oscar.DeserializerState, DataType})(v::JSON3.Array{String, Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}})
    @ Oscar ~/s/Oscar/src/Serialization/containers.jl:54
  [2] load_node(f::Oscar.var"#5799#5800"{Oscar.DeserializerState, DataType}, s::Oscar.DeserializerState, key::Nothing)
    @ Oscar ~/s/Oscar/src/Serialization/serializers.jl:176
  [3] load_node(f::Function, s::Oscar.DeserializerState)
    @ Oscar ~/s/Oscar/src/Serialization/serializers.jl:168
  [4] load_object(s::Oscar.DeserializerState, ::Type{Vector}, params::Type)
    @ Oscar ~/s/Oscar/src/Serialization/containers.jl:52
  [5] (::Oscar.var"#5774#5777"{Oscar.DeserializerState, UnionAll})(::JSON3.Array{String, Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}})
    @ Oscar ~/s/Oscar/src/Serialization/main.jl:218
  [6] load_node(f::Oscar.var"#5774#5777"{Oscar.DeserializerState, UnionAll}, s::Oscar.DeserializerState, key::Symbol)
    @ Oscar ~/s/Oscar/src/Serialization/serializers.jl:176
  [7] load_typed_object(s::Oscar.DeserializerState; override_params::Nothing)
    @ Oscar ~/s/Oscar/src/Serialization/main.jl:217
  [8] load(io::IOBuffer; params::Nothing, type::Nothing, serializer_type::Type)
    @ Oscar ~/s/Oscar/src/Serialization/main.jl:597
  [9] load(io::IOBuffer)
    @ Oscar ~/s/Oscar/src/Serialization/main.jl:525
 [10] top-level scope
    @ REPL[10]:1
```

```julia
julia> Oscar.versioninfo(full = true)
OSCAR version 1.1.0-DEV - #master, 693a3e47a1 -- 2024-03-20 08:42:22 +0100
  combining:
    AbstractAlgebra.jl   v0.40.2
    GAP.jl               v0.10.3
    Hecke.jl             v0.30.1 - #th/rankdep, d855c3a361 -- 2024-03-20 07:47:37 +0100
    Nemo.jl              v0.43.1
    Polymake.jl          v0.11.15
    Singular.jl          v0.22.4
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.9+0
    GAP_jll                 v400.1200.200+9
    Singular_jll            v403.214.1400+0
    libpolymake_julia_jll   v0.11.4+0
    libsingular_julia_jll   v0.43.0+0
    polymake_jll            v400.1100.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_DEPOT_PATH = /s
Official https://julialang.org/ release
```

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Adds fix for loading vectors of types that are serialized with ids.

### CODE REVIEW

File: src/Serialization/containers.jl [hunk 1]
```diff
@@ -65,7 +67,9 @@ end
 function load_object(s::DeserializerState, ::Type{<: Vector{params}}) where params
   load_node(s) do v
     if serialize_with_id(params)
-      loaded_v = params[load_ref(s, x) for x in v]
+      loaded_v = load_array_node(s) do _
```
Comment (antonydellavecchia) [inline src/Serialization/containers.jl]:
```suggestion
      loaded_v::Vector{params} = load_array_node(s) do _
```

**Comment by thofma** [comment]
Merci!

**Review by thofma — APPROVED** [review]
Don't know about the internals, but it fixes the issue.
