### PR TITLE
TropicalGeometry: fix tropical_variety_prime_singular

### LINKED ISSUE #5392: `tropical_variety` not working for Gr(2,5)
If I'm reading the [documentation](https://docs.oscar-system.org/v1/TropicalGeometry/tropicalization/#tropical_variety-Tuple{MPolyIdeal,%20TropicalSemiringMap}) correctly, `tropical_variety` should now work for primary ideals in polynomial rings over the rationals with a trivial valuation. This would include the Plücker ideal of Gr(2,5), but running
```
I = grassmann_pluecker_ideal(2, 5)
tropical_variety(I)
```
returns an 
<details><summary>error</summary>
<p>

```
ERROR: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
Stacktrace:
  [1] reduce_empty(op::Base.MappingRF{Polymake.var"#91#92", typeof(max)}, ::Type{Vector{Int64}})
    @ Base ./reduce.jl:361
  [2] reduce_empty_iter
    @ ./reduce.jl:384 [inlined]
  [3] mapreduce_empty_iter(f::Function, op::Function, itr::Vector{Vector{Int64}}, ItrEltype::Base.HasEltype)
    @ Base ./reduce.jl:380
  [4] _mapreduce(f::Polymake.var"#91#92", op::typeof(max), ::IndexLinear, A::Vector{Vector{Int64}})
    @ Base ./reduce.jl:432
  [5] _mapreduce_dim
    @ ./reducedim.jl:367 [inlined]
  [6] mapreduce/
    @ ./reducedim.jl:359 [inlined]
  [7] _maximum
    @ ./reducedim.jl:1017 [inlined]
  [8] maximum
    @ ./reducedim.jl:1013 [inlined]
  [9] IncidenceMatrix
    @ ~/.julia/packages/Polymake/3ALS3/src/incidencematrix.jl:70 [inlined]
 [10] IncidenceMatrix
    @ ~/.julia/packages/Polymake/3ALS3/src/incidencematrix.jl:75 [inlined]
 [11] gfan_fan_string_to_oscar_complex(input_string::String, negateFan::Bool, dehomogenizeFan::Bool)
    @ Oscar ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety_prime.jl:122
 [12] tropical_variety_prime_singular(I::MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}, nu::TropicalSemiringMap{QQField, Nothing, typeof(min)}; weighted_polyhedral_complex_only::Bool)
    @ Oscar ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety_prime.jl:32
 [13] tropical_variety_prime_singular
    @ ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety_prime.jl:23 [inlined]
 [14] tropical_variety_prime(I::MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}, nu::TropicalSemiringMap{QQField, Nothing, typeof(min)}; weighted_polyhedral_complex_only::Bool)
    @ Oscar ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety_prime.jl:14
 [15] tropical_variety_prime
    @ ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety_prime.jl:9 [inlined]
 [16] tropical_variety_dispatch(I::MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}, nu::TropicalSemiringMap{QQField, Nothing, typeof(min)}; weighted_polyhedral_complex_only::Bool)
    @ Oscar ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety.jl:271
 [17] tropical_variety_dispatch
    @ ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety.jl:256 [inlined]
 [18] #7910
    @ ./none:0 [inlined]
 [19] iterate
    @ ./generator.jl:47 [inlined]
 [20] collect(itr::Base.Generator{Vector{Tuple{MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}, MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}}}, Oscar.var"#7910#7911"{Bool, TropicalSemiringMap{QQField, Nothing, typeof(min)}}})
    @ Base ./array.jl:834
 [21] tropical_variety(I::MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}}, nu::TropicalSemiringMap{QQField, Nothing, typeof(min)}; weighted_polyhedral_complex_only::Bool, skip_saturation::Bool, skip_decomposition::Bool)
    @ Oscar ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety.jl:244
 [22] tropical_variety
    @ ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety.jl:223 [inlined]
 [23] tropical_variety(I::MPolyIdeal{MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}})
    @ Oscar ~/.julia/packages/Oscar/6oHzG/src/TropicalGeometry/variety.jl:223
 [24] top-level scope
    @ REPL[5]:1

```

</p>
</details> 

(note that `grassmann_pluecker_ideal` uses `QQ` as the base field by default). This happens in both OSCAR 1.4 and 1.5, so probably not version-specific.

### PR DESCRIPTION
**Pull request by YueRen**
added function to make variable names singular compatible. fixes https://github.com/oscar-system/Oscar.jl/issues/5392

### CODE REVIEW

File: src/TropicalGeometry/variety_prime.jl [hunk 1]
```diff
@@ -19,8 +19,23 @@ function tropical_variety_prime(I::MPolyIdeal, nu::TropicalSemiringMap; weighted
...
+# that are substrings of other variable names.
+function make_variable_names_singular_compatible(I::MPolyIdeal)
+    R = base_ring(I)
+    n = nvars(R)
+    l = ndigits(n)
+
+    newVarNames = [ "x" * lpad(string(i),l,'0') for i in 1:n ]
+    S,x = polynomial_ring(base_ring(R), newVarNames)
+    changeVarNames = hom(R,S,x)
+    return changeVarNames(I)
```
Comment (fieker) [inline src/TropicalGeometry/variety_prime.jl]: I'd rather return the map: in other situations you might need to reinterpret the Singular result and relate them back to the original ring.

**Comment by fieker** [comment]
apart from this working, this is still a cludge

File: src/TropicalGeometry/variety_prime.jl (hunk 1 above)
Comment (YueRen) [reply src/TropicalGeometry/variety_prime.jl]: Hm, true.  I'll change the code accordingly later.

**Comment by benlorenz** [comment]
Can you add the example from the issue as a testcase?

**Comment by YueRen** [comment]
> Can you add the example from the issue as a testcase?

Is done!

File: src/TropicalGeometry/variety_prime.jl (hunk 1 above)
Comment (YueRen) [reply src/TropicalGeometry/variety_prime.jl]: The function is now takes a multivariate polynomial ring and returns the homomorphism.

File: src/TropicalGeometry/variety_prime.jl [hunk 2]
```diff
@@ -19,8 +19,23 @@ function tropical_variety_prime(I::MPolyIdeal, nu::TropicalSemiringMap; weighted
...
 
+# Given a polynomial ring S, return a map into an isomorphic polynomial ring S->R
+# but with variables renamed to be Singular compatible.
+# The new names are x1, ..., xn if nvars(R)<10, x01, ..., x10 if nvar(R)<100, etc.
+# zero padding is necessary because Singular interpreter does not like variable names
+# that are substrings of other variable names.
+function hom_rename_variables_singular_compatible(S::MPolyRing)
+    n = nvars(S)
+    l = ndigits(n)
+    newVarNames = [ "x" * lpad(string(i),l,'0') for i in 1:n ]
```
Comment (lgoettgens) [inline src/TropicalGeometry/variety_prime.jl]:
```suggestion
    newVarNames = [Symbol(:x, lpad(string(i), l, '0')) for i in 1:n]
```
This should avoid some allocations

**Comment by YueRen** [comment]
I've now replaced the original dirty hack with the suggestion by @fingolfin.  No conversion of an OSCAR ideal to a Singular string necessary anymore, but the need to call the Singular interpreter and the conversion of a Singular fan string to an OSCAR polyhedral complex remain.

File: src/TropicalGeometry/variety_prime.jl [hunk 3]
```diff
@@ -40,6 +43,8 @@ end
 
 # p-adic valuation
 function tropical_variety_prime_singular(I::MPolyIdeal, nu::TropicalSemiringMap{QQField,ZZRingElem,<:Union{typeof(min),typeof(max)}}; weighted_polyhedral_complex_only::Bool=false)
+    phi = hom_rename_variables_singular_compatible(base_ring(I))
+    I = phi(I)
```
Comment (fingolfin) [inline src/TropicalGeometry/variety_prime.jl]: Can this be removed again now?
```suggestion
```

File: src/TropicalGeometry/variety_prime.jl [hunk 4]
```diff
@@ -40,6 +43,8 @@ end
...
     R = base_ring(I)
     singularCommand = join(["ring r=0,("*join(string.(symbols(R)),",")*"),dp;",
```
Comment (fingolfin) [inline src/TropicalGeometry/variety_prime.jl]: Shouldn't the code here be treated similarly?

Comment (YueRen) [reply src/TropicalGeometry/variety_prime.jl]: Oops, forgot that there was more than one of them.  Fixing it now.

File: src/TropicalGeometry/variety_prime.jl [hunk 5]
```diff
@@ -19,16 +19,19 @@ function tropical_variety_prime(I::MPolyIdeal, nu::TropicalSemiringMap; weighted
...
-    TropIString = Singular.lookup_library_symbol("Top", "TropIString")
+
+    name = "tropicalVariety_as_string"
+    sI = Oscar.singular_generators(I)
+    arguments = Any[ Singular.prepare_argument(sI)[1] ]
+    return_value = Singular.libSingular.call_singular_library_procedure(name, base_ring(sI).ptr, arguments);
+    if Singular.libSingular.have_error()
+        error(Singular.libSingular.get_and_clear_error())
+    end
+    TropIString = Singular.convert_return(return_value, ring)
```
Comment (fingolfin) [inline src/TropicalGeometry/variety_prime.jl]: I think this should also work, as the first "libname" argument to `Singular.low_level_caller` is only used to ensure that library is loaded (which is the case here anyway, so it basically does nothing), and then the lookup of the second argument (funcname) ignores the library name.
```suggestion
    sI = Oscar.singular_generators(I)
    TropIString = Singular.low_level_caller("tropical", "tropicalVariety_as_string", sI)
```

However, I did not test it. But if it works, it is clearly preferable :-)

Comment (YueRen) [reply src/TropicalGeometry/variety_prime.jl]: Seems to be working.

Comment (YueRen) [reply src/TropicalGeometry/variety_prime.jl]: @fingolfin do you happen to know how to call the following Singular function using `Singular.low_level_caller` for two inputs, the ideal `sI` and an integer `2`:

```
Singular.call_interpreter("proc tropicalVariety_as_string(ideal I, list #) { if(size(#)==0) { return(string(tropicalVariety(I))); }; return(string(tropicalVariety(I,#[1]))); }")
```

For the old version using `Singular.libSingular.call_singular_library_procedure` the following arguments worked:
```
arguments = Any[ Singular.prepare_argument(sI)[1], Singular.prepare_argument(Int(p))[1] ]
```

Comment (YueRen) [reply src/TropicalGeometry/variety_prime.jl]: Nvm, I take back my comment that `arguments` above worked.  It works for a dummy function:

```
julia> Singular.call_interpreter("proc foo2(ideal I, list #) { print(#[1]); }") # function to call
4-element Vector{Any}:
 false
      ""
      ""
      ""

julia> I = grassmann_pluecker_ideal(2, 5); # argument 1

julia> p = ZZ(3); # argument 2

julia> sI = Oscar.singular_generators(I);

julia> sR = base_ring(sI)
Singular polynomial ring (QQ),(x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10),(dp(10),C)

julia> sp = Int(p)
3

julia> arguments = Any[ Singular.prepare_argument(sI)[1], Singular.prepare_argument(sp)[1] ]
2-element Vector{Any}:
 Any[276, Ptr{Nothing}(0x000000001176b2a0)]
 Any[420, Ptr{Nothing}(0x0000000000000003)]

julia> return_value = Singular.libSingular.call_singular_library_procedure("foo2", sR.ptr, arguments);
3

```

But somehow not for `tropicalVariety_as_string` which returns an empty string:

```
julia> Singular.libSingular.load_library("tropical.lib")
true

julia> Singular.call_interpreter("proc tropicalVariety_as_string(ideal I, list #) { if(size(#)==0) { return(string(tropicalVariety(I))); }; return(string(tropicalVariety(I,#[1]))); }") # function to call
4-element Vector{Any}:
 false
      ""
      ""
      ""

julia> I = grassmann_pluecker_ideal(2, 5); # argument 1

julia> nu = tropical_semiring_map(QQ, 3)
Map into Min tropical semiring encoding the 3-adic valuation on Rational field

julia> p = Oscar.uniformizer_ring(nu) # argument 2
3

julia> sI = Oscar.singular_generators(I);

julia> sR = base_ring(sI)
Singular polynomial ring (QQ),(x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10),(dp(10),C)

julia> sp = Int(p)
3

julia> arguments = Any[ Singular.prepare_argument(sI)[1], Singular.prepare_argument(sp)[1] ]
2-element Vector{Any}:
 Any[276, Ptr{Nothing}(0x0000000011753af8)]
 Any[420, Ptr{Nothing}(0x0000000000000003)]

julia> return_value = Singular.libSingular.call_singular_library_procedure("tropicalVariety_as_string", sR.ptr, arguments);

julia> return_value
3-element Vector{Any}:
 false
      Ptr{Nothing}(0x0000000011741750)
   511

julia> TropIString = Singular.convert_return(return_value, ring)
""

```

I will reinstate the old version for the second function, since at least it did work.

File: src/TropicalGeometry/variety_prime.jl [hunk 6]
```diff
@@ -38,8 +35,23 @@ function tropical_variety_prime_singular(I::MPolyIdeal, nu::TropicalSemiringMap{
...
+# zero padding is necessary because Singular interpreter does not like variable names
+# that are substrings of other variable names.
+function hom_rename_variables_singular_compatible(S::MPolyRing)
+    n = nvars(S)
+    l = ndigits(n)
+    newVarNames = [Symbol(:x, lpad(string(i), l, '0')) for i in 1:n]
+    R,x = polynomial_ring(base_ring(S), newVarNames)
+    return hom(S,R,x)
+end
+
```
Comment (fingolfin) [inline src/TropicalGeometry/variety_prime.jl]:
```suggestion
```

**Comment by YueRen** [comment]
@fingolfin Everything should be using `Singular.low_level_caller` now.

**Comment by fingolfin** [comment]
Thanks @YueRen this looks good. Unfortunately it seems to cause a crash :-( in CI, in the doctests:
```
page: src/TropicalGeometry/variety.jl:74-96
  0.132471 seconds (35.74 k allocations: 2.843 MiB, 56.50% compilation time)
page: src/TropicalGeometry/variety.jl:167-220
/home/runner/work/_temp/d5e2334b-f0b4-40c5-a276-f9262c06c6fc.sh: line 7:  2263 Segmentation fault      (core dumped)
```

**Review by VictoriaSchleis — APPROVED** [review]

File: src/Oscar.jl [hunk 7]
```diff
@@ -178,6 +178,19 @@ function __init__()
...
+  # see TropicalGeometry/variety_prime.jl
+  Singular.libSingular.load_library("tropical.lib")
+  Singular.call_interpreter("""
+    proc tropicalVariety_as_string(ideal I, list #) {
+      if(size(#)==0) {
+        return(string(tropicalVariety(I)));
+      };
+      return(string(tropicalVariety(I,number(#[1]))));
+    }
+    """)
```
Comment (fingolfin) [inline src/Oscar.jl:207]: @YueRen I took the liberty of reformatting this for readability :-)

(I had to edit this PR anyway to adjust for the changed `Singular.low_level_caller` arguments introduced in the latest Singular.jl

**Comment by fingolfin** [comment]
The crash is in a doctest in `src/TropicalGeometry/variety.jl`. I reproduced it locally and narrowed it down to this example:
```julia-repl
julia> K,t = rational_function_field(GF(101),:t);

julia> R,(x,y,z) = K["x","y","z"];

julia> nu_2 = tropical_semiring_map(QQ,2)
Map into Min tropical semiring encoding the 2-adic valuation on Rational field

julia> f1 = 8*x^2 + x*y + x*z + x + 8*y^2 + y*z + y + 8*z^2 + z + 8;

julia> f2 = x + 2;

julia> I = ideal([f1,f2]);

julia> TropI_2 = tropical_variety(I,nu_2; skip_saturation=true, skip_decomposition=true)

[76002] signal 11 (2): Segmentation fault: 11
in expression starting at REPL[13]:1
unknown function (ip: 0x0) at (unknown file)
Allocations: 99607851 (Pool: 99573602; Big: 34249); GC: 34
/Users/mhorn/.local/bin/j12: line 2: 76002 Segmentation fault: 11  julia +1.12 --proj=p/1.12 "$@"
```

Debugger backtrace:
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x0000000333208bd8 libSingular-4.4.1.dylib`tropicalStrategy::tropicalStrategy(sip_sideal*, snumber*, ip_sring*) + 1528
    frame #2: 0x000000033321c3d0 libSingular-4.4.1.dylib`tropicalVariety(sleftv*, sleftv*) + 1920
    frame #3: 0x0000000333166ab0 libSingular-4.4.1.dylib`iiMake_proc(idrec*, sip_package*, sleftv*) + 320
    frame #4: 0x000000033312724c libSingular-4.4.1.dylib`jjPROC(sleftv*, sleftv*, sleftv*) + 220
    frame #5: 0x000000033312edf0 libSingular-4.4.1.dylib`iiExprArith2TabIntern(sleftv*, sleftv*, int, sleftv*, int, sValCmd2 const*, int, int, sConvertTypes const*) + 2096
    frame #6: 0x000000033312f904 libSingular-4.4.1.dylib`iiExprArith2(sleftv*, sleftv*, int, sleftv*, int) + 612
    frame #7: 0x0000000333153000 libSingular-4.4.1.dylib`jjKLAMMER_PL(sleftv*, sleftv*) + 176
    frame #8: 0x00000003331323c8 libSingular-4.4.1.dylib`iiExprArithM(sleftv*, sleftv*, int) + 952
    frame #9: 0x000000033312581c libSingular-4.4.1.dylib`yyparse() + 9596
    frame #10: 0x0000000333166420 libSingular-4.4.1.dylib`iiAllStart(procinfo*, char const*, feBufferTypes, int) + 272
    frame #11: 0x00000003331667e8 libSingular-4.4.1.dylib`iiPStart(idrec*, sleftv*) + 440
    frame #12: 0x0000000333166b70 libSingular-4.4.1.dylib`iiMake_proc(idrec*, sip_package*, sleftv*) + 512
    frame #13: 0x000000033312724c libSingular-4.4.1.dylib`jjPROC(sleftv*, sleftv*, sleftv*) + 220
    frame #14: 0x000000033312edf0 libSingular-4.4.1.dylib`iiExprArith2TabIntern(sleftv*, sleftv*, int, sleftv*, int, sValCmd2 const*, int, int, sConvertTypes const*) + 2096
    frame #15: 0x000000033312f904 libSingular-4.4.1.dylib`iiExprArith2(sleftv*, sleftv*, int, sleftv*, int) + 612
    frame #16: 0x0000000333153000 libSingular-4.4.1.dylib`jjKLAMMER_PL(sleftv*, sleftv*) + 176
    frame #17: 0x00000003331323c8 libSingular-4.4.1.dylib`iiExprArithM(sleftv*, sleftv*, int) + 952
    frame #18: 0x000000033312581c libSingular-4.4.1.dylib`yyparse() + 9596
    frame #19: 0x0000000333166420 libSingular-4.4.1.dylib`iiAllStart(procinfo*, char const*, feBufferTypes, int) + 272
    frame #20: 0x00000003331667e8 libSingular-4.4.1.dylib`iiPStart(idrec*, sleftv*) + 440
    frame #21: 0x0000000333166b70 libSingular-4.4.1.dylib`iiMake_proc(idrec*, sip_package*, sleftv*) + 512
    frame #22: 0x00000003331679cc libSingular-4.4.1.dylib`ii_CallLibProcM(char const*, void**, int*, ip_sring*, int&) + 492
    frame #23: 0x0000000333e202c8 libsingular_julia.dylib`call_singular_library_procedure(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ip_sring*, jlcxx::ArrayRef<_jl_value_t*, 1>) + 280
    frame #24: 0x0000000333e249ac libsingular_julia.dylib`std::__1::__function::__func<_jl_value_t* (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ip_sring*, jlcxx::ArrayRef<_jl_value_t*, 1>), std::__1::allocator<_jl_value_t* (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ip_sring*, jlcxx::ArrayRef<_jl_value_t*, 1>)>, _jl_value_t* (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ip_sring*, jlcxx::ArrayRef<_jl_value_t*, 1>)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, ip_sring*&&, jlcxx::ArrayRef<_jl_value_t*, 1>&&) + 60
    frame #25: 0x0000000333e2481c libsingular_julia.dylib`jlcxx::detail::CallFunctor<_jl_value_t*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, ip_sring*, jlcxx::ArrayRef<_jl_value_t*, 1>>::apply(void const*, jlcxx::WrappedCppPtr, jlcxx::WrappedCppPtr, jl_array_t*) + 92
    frame #26: 0x00000003d6eb4094
    frame #27: 0x00000001016416a0 libjulia-internal.1.12.1.dylib`eval_stmt_value(stmt=<unavailable>, s=<unavailable>) at interpreter.c:194:23 [opt]
    frame #28: 0x0000000101640320 libjulia-internal.1.12.1.dylib`eval_body(stmts=<unavailable>, s=0x000000016ef84560, ip=<unavailable>, toplevel=1) at interpreter.c:689:21 [opt]
    frame #29: 0x000000010164097c libjulia-internal.1.12.1.dylib`jl_interpret_toplevel_thunk(m=0x000000011c141fb0, src=0x0000000364ce6410) at interpreter.c:898:21 [opt]
    frame #30: 0x000000010165b338 libjulia-internal.1.12.1.dylib`jl_toplevel_eval_flex(m=0x000000011c141fb0, e=<unavailable>, fast=1, expanded=1, toplevel_filename=<unavailable>, toplevel_lineno=0x000000033e40f3b0) at toplevel.c:1035:18 [opt]
    frame #31: 0x0000000113e8748c u0gqU_vMi9E.dylib`japi1___repl_entry_eval_expanded_with_loc_19063.1 at REPL.jl:301
    frame #32: 0x000000010162d0ac libjulia-internal.1.12.1.dylib`jl_apply(args=<unavailable>, nargs=5) at julia.h:2391:12 [opt] [inlined]
    frame #33: 0x000000010162d09c libjulia-internal.1.12.1.dylib`jl_f_invokelatest(F=<unavailable>, args=<unavailable>, nargs=5) at builtins.c:881:23 [opt]
    frame #34: 0x000000011171c0f0
(lldb)
```

Perhaps @hannes14 or @YueRen can make something out of this.

**Comment by fingolfin** [comment]
I would hope that @hannes14 @ederc or @YueRen might be able to look at this crash here?

(It'd also help if someone resolved the merge conflict that crept in in the meantime)

File: src/TropicalGeometry/variety_prime.jl [hunk 8]
```diff
@@ -39,15 +33,9 @@ function tropical_variety_prime_singular(I::MPolyIdeal, nu::TropicalSemiringMap{
...
-    singularCommand = join(["ring r=0,("*join(string.(symbols(R)),",")*"),dp;",
-                            "ideal I = "*join(string.(gens(I)), ",")*";",
-                            "if (!defined(tropicalVariety)) { LIB \"tropical.lib\"; };",
-                            "fan TropI = tropicalVariety(I,number("*string(uniformizer(nu))*"));",
-                            "string TropIString = string(TropI);"])
-    Singular.call_interpreter(singularCommand)
-    TropIString = Singular.lookup_library_symbol("Top", "TropIString")
+function tropical_variety_prime_singular(I::MPolyIdeal, nu::TropicalSemiringMap{QQField,ZZRingElem}; weighted_polyhedral_complex_only::Bool=false)
+    sI = Oscar.singular_generators(I)
+    TropIString = Singular.low_level_caller("tropical", "tropicalVariety_as_string", (sI, Int(uniformizer_ring(nu))))
```
Comment (benlorenz) [inline src/TropicalGeometry/variety_prime.jl]:
```suggestion
    TropIString = Singular.low_level_caller("tropical", "tropicalVariety_as_string", (sI, Int(uniformizer_in_ring(nu))))
```

**Comment by fingolfin** [comment]
To resolves this, it might help to move the definition of the helper function to Singular.

Hans told me before Christmas that the crash is caused by the interpreter "not knowing" about something... either this helper function, or (more likely I think) the polynomial ring.... This might help someone to figure this out.

I think this kind of approach followed in this PR would be very important to have working, as it opens the door for easy access to a bunch of other Singular goodies without having to write C++ code, recompile JLLs etc.

File: src/Oscar.jl [hunk 9]
```diff
@@ -184,6 +184,19 @@ function __init__()
     @warn "Project dependencies might have changed, please run `]up` or `]resolve`."
   end
 
+  # Temporary workaround to allow access to Singular's tropicalVariety command
+  # see https://github.com/oscar-system/Oscar.jl/issues/5392
+  # see TropicalGeometry/variety_prime.jl
+  Singular.libSingular.load_library("tropical.lib")
+  Singular.call_interpreter("""
+    proc tropicalVariety_as_string(ideal I, list #) {
```
Comment (HereAround) [inline src/Oscar.jl:201]: @YueRen We just touched on this PR in triage, and @jankoboehm suggested the following way forward to debug the failures:

1. Could you please try to integrate this procedure directly into Singular and try again. Does it work in Singular? If so, can you please open a correspponding PR to Singular. (Maybe you already tried this?)
2. Try out in OSCAR.

(And if that does not fix the issue, we will need to brainstorm again.)

**Comment by YueRen** [comment]
Quite embarrassing, but I noticed that the crash is caused by a problem in my docstring (weird combinations of input that shouldn't be).  If that is indeed the case, I'll try to add some guardrails to prevent users running into it accidentally.

**Comment by YueRen** [comment]
Okay, the PR is ready to be merged, maybe after a final brief review.  Here are the main changes:

- There was a problem in the `tropical_variety` documentation:  One example worked over $\mathbb{Q}(t)$ equipped with the $p$-adic valuation, which the underlying Singular code was not designed for and led to a crash.  The example is now fixed and I've put some restrictions of the input types for `tropical_variety_prime_singular` to prevent it from happening.
- Instead of passing the ideal as a string (which caused https://github.com/oscar-system/Oscar.jl/issues/5392) and running everything via `Singular.call_interpreter`, the ideal is now passed via `Oscar.singular_generators` and the function is called via `Singular.low_level_caller`.  To facilitate that, `Oscar.jl` now loads the Singular library `tropical.lib` and defines a new Singular function `tropicalVariety_as_string`.
- There was a bug in the logic of `gfan_fan_string_to_oscar_complex` that is now fixed.  The bug was in the part which takes a polyhedral fan in $\mathbb{R}^{n+1}$, intersects it with $\\{1\\}\times\mathbb{R}^n$, and makes it into a polyhedral complex in $\mathbb{R}^n$.  And the old code simply forgot to divide the rays of $\mathbb{R}^{n+1}$ that represent vertices in $\mathbb{R}^n$ by their first coordinate, leading to a wrong output of `tropical_variety`.
