### PR TITLE
fix too restrictive method installations

### LINKED ISSUE #4144: induced_automorphism does not work for (Sub)PcGroups
I tried the following and subsequently get an error:

```julia
❯ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0 (2023-12-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Oscar
  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.1.1

julia> G = small_group(2, 1)
Pc group of order 2

julia> H, f = maximal_abelian_quotient(G)
(Pc group of order 2, Hom: G -> H)

julia> A = automorphism_group(G)
Aut( <pc group of size 2 with 1 generator> )

julia> a = gen(A, 1)
[ f1 ] -> [ f1 ]

julia> induced_automorphism(f, a)
ERROR: MethodError: no method matching (::AutomorphismGroup{SubPcGroup})(::GAPGroupHomomorphism{PcGroup, PcGroup})

Closest candidates are:
  (::AutomorphismGroup{T})(::GAPGroupHomomorphism{T, T}) where T<:Oscar.GAPGroup
   @ Oscar ~/.julia/packages/Oscar/38HwK/src/Groups/homomorphisms.jl:1196
  (::AutomorphismGroup)(::GapObj)
   @ Oscar ~/.julia/packages/Oscar/38HwK/src/Groups/types.jl:541
  (::Oscar.GAPGroup)(::Oscar.BasicGAPGroupElem{T}) where T<:Oscar.GAPGroup
   @ Oscar ~/.julia/packages/Oscar/38HwK/src/Groups/GAPGroups.jl:53

Stacktrace:
 [1] induced_automorphism(f::GAPGroupHomomorphism{PcGroup, PcGroup}, mH::GAPGroupHomomorphism{PcGroup, PcGroup})
   @ Oscar ~/.julia/packages/Oscar/38HwK/src/Groups/homomorphisms.jl:1271
 [2] induced_automorphism(f::GAPGroupHomomorphism{PcGroup, PcGroup}, mH::AutomorphismGroupElem{PcGroup})
   @ Oscar ~/.julia/packages/Oscar/38HwK/src/Groups/homomorphisms.jl:1274
 [3] top-level scope
   @ REPL[10]:1
```

This appeared to work on Oscar 1.0.4 and probably no longer does because `image(f)` in `induced_automorphism(...)` now yields the newly introduced type `SubPcGroup`.

### PR DESCRIPTION
**Pull request by ThomasBreuer**
In many situations,
we cannot expect that compatible groups have the same type.

resolves #4144

### CODE REVIEW

File: src/Groups/homomorphisms.jl [hunk 1]
```diff
@@ -1351,11 +1350,11 @@ function inner_automorphism_group(A::AutomorphismGroup{T}) where T <: GAPGroup
 end
 
 """
-    is_invariant(f::GAPGroupElem{AutomorphismGroup{T}}, H::T)
+    is_invariant(f::GAPGroupElem{<: AutomorphismGroup{<: GAPGroup}}, H::GAPGroup)
 
 Return whether `f`(`H`) == `H`.
 """
-function is_invariant(f::GAPGroupElem{AutomorphismGroup{T}}, H::T) where T<:GAPGroup
+function is_invariant(f::GAPGroupElem{<: AutomorphismGroup{<: GAPGroup}}, H::GAPGroup)
```
Comment (fingolfin) [inline src/Groups/homomorphisms.jl]: I think you also need to adjust `docs/src/Groups/autgroup.md` to match

File: docs/src/Groups/autgroup.md [hunk 2]
```diff
@@ -11,8 +11,8 @@ automorphism_group(G::GAPGroup)
 
 The following functions are available for automorphisms, some of them similar to the corresponding functions for homomorphisms of groups.
 ```@docs
-is_invariant(f::GAPGroupElem{AutomorphismGroup{T}}, H::T) where T<:GAPGroup
-restrict_automorphism(f::GAPGroupElem{AutomorphismGroup{T}}, H::T, A=automorphism_group(H)) where T <: GAPGroup
+is_invariant(f::GAPGroupElem{AutomorphismGroup{T}}, H::GAPGroup) where T <: GAPGroup
```
Comment (lgoettgens) [inline docs/src/Groups/autgroup.md:14]: The T in this line is irrelevant for the first part

File: docs/src/Groups/autgroup.md [hunk 3]
```diff
@@ -11,8 +11,8 @@ automorphism_group(G::GAPGroup)
...
+restrict_automorphism(f::GAPGroupElem{AutomorphismGroup{T}}, H::GAPGroup, A=automorphism_group(H)) where T <: GAPGroup
```
Comment (lgoettgens) [inline docs/src/Groups/autgroup.md:15]: Here as well

File: docs/src/Groups/autgroup.md (hunk 2 above)
Comment (ThomasBreuer) [reply docs/src/Groups/autgroup.md:14]: Hmm, I try to put the same line into the .md file that appears in the src file, and this seems to work.
Do we have a better convention (perhaps for the section on the `docs` folder in the developer documentation)?

Comment (lgoettgens) [reply docs/src/Groups/autgroup.md:14]: This is in fact fine, I just didn't read properly. Sorry for the confusion

File: src/Groups/homomorphisms.jl [hunk 4]
```diff
@@ -1298,7 +1297,7 @@ end
 Base.:^(x::GAPGroupElem{T},f::GAPGroupElem{AutomorphismGroup{T}}) where T <: GAPGroup = apply_automorphism(f, x, true)
 #Base.:^(f::GAPGroupElem{AutomorphismGroup{T}},g::GAPGroupElem{AutomorphismGroup{T}}) where T <: GAPGroup = g^-1*f*g
 
-function (A::AutomorphismGroup{T})(f::GAPGroupHomomorphism{T,T}) where T <: GAPGroup
+function (A::AutomorphismGroup{S})(f::GAPGroupHomomorphism{T,T}) where S <: GAPGroup where T <: GAPGroup
```
Comment (lgoettgens) [inline src/Groups/homomorphisms.jl]:
```suggestion
function (A::AutomorphismGroup{S})(f::GAPGroupHomomorphism{T,T}) where {S <: GAPGroup, T <: GAPGroup}
```
a double `where` is almost never necessary.
Alternatively, you could even do
```suggestion
function (A::AutomorphismGroup{<: GAPGroup})(f::GAPGroupHomomorphism{T,T}) where T <: GAPGroup
```

File: src/Groups/libraries/smallgroups.jl [hunk 5]
```diff
@@ -83,7 +83,7 @@ Pc group of order 60
 ```
 """
 function small_group(::Type{T}, n::IntegerUnion, m::IntegerUnion) where T
-  G = _small_group(n, m)
+  G = small_group(n, m)
```
Comment (lgoettgens) [inline src/Groups/libraries/smallgroups.jl:86]: Is this change intended? I am not deep enough into the details to understand the difference

File: src/Groups/sub.jl [hunk 6]
```diff
@@ -34,7 +34,6 @@ true
 ```
 """
 function sub(G::GAPGroup, gens::AbstractVector{S}; check::Bool = true) where S <: GAPGroupElem
```
Comment (lgoettgens) [inline src/Groups/sub.jl]:
```suggestion
function sub(G::GAPGroup, gens::AbstractVector{<: GAPGroupElem}; check::Bool = true)
```
since you don't use `S` anymore inside the function

**Review by lgoettgens — APPROVED** [review]
looks good, just some minor comments

File: src/Groups/libraries/smallgroups.jl (hunk 5 above)
Comment (ThomasBreuer) [reply src/Groups/libraries/smallgroups.jl:86]: Yes. (It is also mentioned in the corresponding commit message.)

File: src/Groups/homomorphisms.jl (hunk 4 above)
Comment (ThomasBreuer) [reply src/Groups/homomorphisms.jl]: o.k.
Concerning the multiple `where`, there are lots in many code files, this is perhaps something for a pull request of its own.

File: src/Groups/sub.jl (hunk 6 above)
Comment (ThomasBreuer) [reply src/Groups/sub.jl]: o.k.
