### PR TITLE
Fix a bug in Borcherds' method. 

### LINKED ISSUE #4804: Borcherds' method for K3s errors
Computing the adjacent chamber of returns a so called S-degenerate chamber.
This should never happen, but so far I do not understand where things go wrong.

```
julia> S = integer_lattice(gram=ZZ[0 27 0; 27 6 0; 0 0 -2]);

julia> k3 = borcherds_method(S,26;max_nchambers=2)[1]
BorcherdsCtx: dim(L) = 26, rank(S) = 3, det(S) = 1458

julia> w = ZZ[-9299 -2023 -1649 315664 -1076618 2255939 3067477 -3564886 885992 874062 2590974 829387 982777 -153391 -49161 1116798 -1073654 494350 2940911 -2242571 777276 -1579935 -942594 -1084060 1675196 7446];

julia> c = chamber(k3, w)
Chamber: ZZRingElem[-9299, -2023, -1649]

julia> v = ZZ[7096 1602 17739]
[7096   1602   17739]

julia> @assert v in walls(c)
lineality_dim(P) = 0

julia> c2 = adjacent_chamber(c,v)
Chamber: ZZRingElem[-8885, -1934, -1576]

julia> walls(c2)
ERROR: AssertionError: 
```

### PR DESCRIPTION
**Pull request by simonbrandhorst**
Fix #4804. The bug should usually result in an error ... but I cannot completely exclude that it could corrupt the output of the user facing function in rare cases. So this should be backported please.

### CODE REVIEW

File: test/AlgebraicGeometry/Surfaces/K3Auto.jl [hunk 1]
```diff
@@ -196,3 +196,16 @@ end
   L,S,w = Oscar.borcherds_method_preprocessing(rescale(UE7,2),18)
   @test (w*gram_matrix(rational_span(L))*transpose(w))[1,1] == 620
 end 
+
+@testset "#4804 is fixed"
```
Comment (StevellM) [inline test/AlgebraicGeometry/Surfaces/K3Auto.jl]:
```suggestion
@testset "#4804 is fixed" begin
```

**Comment by lgoettgens** [comment]
I don't think that we will backport any things to 1.0.x and 1.1.x, but I'll let @aaruni96 and @benlorenz decide

**Review by StevellM — APPROVED** [review]
