### PR TITLE
Serialization Refactor

### LINKED ISSUE #4567: Serialization: problem while saving a list of tuples of matrices with varying sizes
**Describe the bug**
It seems that there is a bug while saving a list of tuples of matrices. In fact, it seems that saving or loading assumes wrong size of matrices which makes data unable to be loaded.

**To Reproduce**
```
using Oscar
julia> m = (matrix(QQ, 1, 1, [2]), matrix(QQ, 2, 2, [1//2 0; 0 1//2]))
([2], [1//2 0; 0 1//2])

julia> mm = [m, reverse(m)]
2-element Vector{Tuple{QQMatrix, QQMatrix}}:
 ([2], [1//2 0; 0 1//2])
 ([1//2 0; 0 1//2], [2])

julia> save("Schreibtisch/tmp.mrdi", mm)

julia> load("Schreibtisch/tmp.mrdi")
┌ Warning: Attempted loading file stored using a DEV version with commit 8fc7969f373c61cb9bab612fe608e89c9d2d7d0c
└ @ Oscar ~/.julia/dev/Oscar/src/Serialization/main.jl:712
ERROR: Expected dimension 1 x 1, got 2 x 2
Stacktrace:
  [1] _check_dim
    @ ~/.julia/packages/AbstractAlgebra/bL4Gd/src/Matrix.jl:46 [inlined]
  [2] _check_dim
    @ ~/.julia/packages/AbstractAlgebra/bL4Gd/src/Matrix.jl:44 [inlined]
  [3] (::MatSpace{QQFieldElem})(arr::Matrix{QQFieldElem})
    @ Nemo ~/.julia/packages/Nemo/E8ekQ/src/flint/fmpq_mat.jl:718
  [4] load_object(s::Oscar.DeserializerState{Oscar.JSONSerializer}, ::Type{MatElem}, parents::Vector{Union{Ring, FreeAssociativeAlgebra, MatSpace, SMatSpace}})
    @ Oscar ~/.julia/dev/Oscar/src/Serialization/Rings.jl:417
[...]
 [31] load(filename::String)
    @ Oscar ~/.julia/dev/Oscar/src/Serialization/main.jl:718
 [32] top-level scope
    @ REPL[13]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Expected behavior**
Since we know how to serialize lists, tuples and matrices, I would expect to be able to serialize a list of tuples of matrices of various sizes.

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.3.0-DEV - #main, 8fc7969f37 -- 2025-02-08 18:29:40 +0000
  combining:
    AbstractAlgebra.jl   v0.44.5
    GAP.jl               v0.13.1
    Hecke.jl             v0.35.9
    Nemo.jl              v0.48.2
    Polymake.jl          v0.11.25
    Singular.jl          v0.24.1
  building on:
    FLINT_jll               v300.100.301+0
    GAP_jll                 v400.1400.3+0
    Singular_jll            v404.1.700+0
    libpolymake_julia_jll   v0.13.1+0
    libsingular_julia_jll   v0.46.1+0
    polymake_jll            v400.1300.2+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Official https://julialang.org/ release
...
```

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Refactor serialization to use a new function called `type_params` which helps build a stack of type dependencies which will allow for serializing type information before the data.

### Release notes:
manually copy from https://github.com/oscar-system/Oscar.jl/pull/4162#issuecomment-2893356751

### CODE REVIEW

**Review by lkastner — DISMISSED** [review]

**Comment by lgoettgens** [comment]
This PR seems to have diverged a lot from current master due to other changes to the serialization code in the meantime. Could you try to resolve the conflicts / rebase this onto a more current master, so that one can more easily follow what's happening and CI runs again?

I am a bit afraid that this just continues to diverge even further in the future, which makes it harder to resolve conflicts once you want to merge it.

File: src/Combinatorics/SimplicialComplexes.jl [hunk 1]
```diff
@@ -670,7 +670,7 @@ function automorphism_group(K::SimplicialComplex; action=:on_vertices)
 end
 
 @doc raw"""
-    on_simplicial_complex(K::SimplicialComplex, g::PermGroupElem)
+    on_simplicial_complex(K::SimplicialComplex, g::PermGroupElem; action=:on_vertices)
```
Comment (lgoettgens) [inline src/Combinatorics/SimplicialComplexes.jl]: is this maybe a conflict resolution artifact? it does not match the signature of the function this docstring is attached to

File: src/Serialization/GAP.jl [hunk 2]
```diff
@@ -125,43 +143,47 @@ install_GAP_deserialization(
...
+          GapObj(names; recursive = true)
+        end
+        G = GAP.Globals.FreeGroup(wfilt, init)::GapObj
       end
-      return G
     end
+    return G
+  end)
+
+install_GAP_deserialization(
```
Comment (antonydellavecchia) [inline src/Serialization/GAP.jl:187]: @ThomasBreuer  I think I need your help here, and it also makes sense for you to understand what I am doing here anyway.

I am currently try to get the serialization refactor working for gap objects, and the first one that causes an issue is when we try and save subgroups of free groups


If you see above I have a new function called `type_params` and this handles when params need to be added to the type description for example saving a subgroup of a free group currently looks like this

```
{
  "_ns": {
    "Oscar": [
      "https://github.com/oscar-system/Oscar.jl",
      "1.3.0-DEV-0324e87a589a2c2c5b6f4b0db4634b14477250ae"
    ]
  },
  "_refs": {
    "fef8f069-d2db-4c88-9118-f2b7ba1c3999": {
      "_type": "GapObj",
      "data": {
        "GapType": "IsFreeGroup",
        "names": [
          "f1",
          "f2"
        ],
        "wfilt": "IsSyllableWordsFamily"
      }
    }
  },
  "_type": {
    "name": "GapObj",
    "params": "fef8f069-d2db-4c88-9118-f2b7ba1c3999"
  },
  "data": {
    "GapType": "IsFreeGroup",
    "gens": [
      [
        "1",
        "1"
      ]
    ]
  },
  "id": "ab56be5f-1bf6-4fec-a3d5-35cb59b6096b"
}

```

Note how there is no longer a freeGroup key in the data section and that the type information of the GapObj now has a params key.

The issue I am having now is that I need to pass the free group down, but this means I need two different function signatures. 

But I am guessing these cannot share the same namespace in GAP?

please let me know if you have any questions about some of the changes here

Comment (ThomasBreuer) [reply src/Serialization/GAP.jl:187]: @antonydellavecchia I am not sure whether I understand the aim of the proposed changes.
A subgroup of a full free group is best described in terms of generators relative to the full free group, hence the "old" approach first serializes the full free group and then the generators of the subgroup in question, and the deserialization first reconstructs the full free group and then the subgroup generators w.r.t. the full group.

The idea of the "new" approach seems to be that the function `type_params` shall describe the object(s) to be serialized together with the data of the given object.
The problem is that `type_params` for a `GapObj` has to deal with a lot of different `GapObj`s.
In the "old" serialization and deserialization of GAP objects, the approach using `install_GAP_serialization` and `install_GAP_deserialization` yields small Julia functions for different kinds of GAP objects. One could think of an analogous `install_GAP_type_params` in order to achieve this for `type_params` iin the "new" approach, but what is the advantage of using `type_params`, compared to the "old" (recursive) serialization approach?

Just for curiosity: How does the "new" approach handle objects that need more than one dependent object to be serialized?
(For example, the most natural way to serialize a map seems to be to serialize domain and codomain and information that defines the function in question.)
These dependent objects are stored in `_refs`, their keys in `_refs` shall be referenced somewhere in `_type`, but how does the deserialization code know which is which? In the "old" approach, the references to the keys in `_refs` are stored in fields inside `data` (like the `freeGroup` field), whose meanings are defined by the serialization.

Comment (antonydellavecchia) [reply src/Serialization/GAP.jl:187]: The idea is that type params will do a shallow pass through the object and obtain all necessary type information for the object. This has many benefits, the main one being that this would allow us to put all type information at the top of the file and hence we would be able to read in all params for the object before we get to the data in a linear way. 

here is another example of how a the new format looks for a MPolyAnyMap.
You can see that the params section can also have keys, i.e. we can have params that are dictionnaries if necessary
(this does not yet include the linear ordering)

```
{
  "_ns": {
    "Oscar": [
      "https://github.com/oscar-system/Oscar.jl",
      "1.3.0-DEV-98fc56d6f49a6eacecd525b01c0e543857608f58"
    ]
  },
  "_refs": {
    "bede6628-38bf-4803-88df-2ed7487fc8c8": {
      "_type": {
        "name": "MPolyRing",
        "params": {
          "_type": "QQField"
        }
      },
      "data": {
        "symbols": [
          "s",
          "t",
          "m"
        ]
      }
    },
    "fc49a9a8-91af-4b54-888b-58b4f2dd1958": {
      "_type": {
        "name": "MPolyRing",
        "params": {
          "_type": "QQField"
        }
      },
      "data": {
        "symbols": [
          "x",
          "y"
        ]
      }
    }
  },
  "_type": {
    "name": "MPolyAnyMap",
    "params": {
      "codomain": {
        "name": "MPolyRing",
        "params": "bede6628-38bf-4803-88df-2ed7487fc8c8"
      },
      "domain": {
        "name": "MPolyRing",
        "params": "fc49a9a8-91af-4b54-888b-58b4f2dd1958"
      }
    }
  },
  "data": {
    "images": [
      [
        [
          [
            "1",
            "1",
            "0"
          ],
          "1"
        ]
      ],
      [
        [
          [
            "0",
            "0",
            "1"
          ],
          "1"
        ]
      ]
    ]
  }
}
```

Comment (ThomasBreuer) [reply src/Serialization/GAP.jl:187]: Thanks @antonydellavecchia .
Thus the rule is that it is recommended (or mandatory?) to "announce" the dependent objects via `type_params`.

Then the interface for the (de)serialization for a given object type `T` (here: `GapObj`) consists of
- a `save_object` method with second argument `T`,
- a `load_object` method with two or three arguments, the second argument being `T`,
- a `type_params` method with one argument of type `T`, returning `S, X` where `X` is either `nothing` or an object of type `S` (a dictionary or a `GapObj`); in the latter case, there must be a three argument method for `load_object` that takes `X` as its third argument.

If this is correct then I propose a function `install_GAP_type_params` as sketched above for the case of `GapObj`. I can provide the code for that.

Comment (antonydellavecchia) [reply src/Serialization/GAP.jl:187]: The rule will become mandatory.

the load object third parameters will exactly be the second entry of the output from `type_params`

the output of `type_params` should be a tuple where the first entry is the type and the second entry are the params for that type, for example above type_params with return the type  
```
PolyAnyMap, Dict(:codomain => QQ[:s, :t, :m], :domain => QQ[:x, :y])
```

for a  group element g It would be some thing like 

```
GroupElem, parent(g)
```

and yes exactly, if the second output of `type_params` is nothing, then that particular load_object method only needs two parameters

**Comment by ThomasBreuer** [comment]
The tests for pc groups are still disabled. Here the problem is that `load_object(s, Vector, (Tuple, [Int, Int, [Vector, Int]]), :comm_rels)` does not work anymore.

**Comment by antonydellavecchia** [comment]
> The tests for pc groups are still disabled. Here the problem is that `load_object(s, Vector, (Tuple, [Int, Int, [Vector, Int]]), :comm_rels)` does not work anymore.

Thanks for that. I've made the loading of vectors a little more intuitive. 
Please see the changes I've just pushed to get the GAP object serialization working

**Comment by ThomasBreuer** [comment]
> Please see the changes I've just pushed to get the GAP object serialization working

Thanks @antonydellavecchia.
~~I am going to adjust the serialization for GAP pc groups.~~
Now the tests for GAP pc groups pass.

File: src/Serialization/LieTheory.jl [hunk 3]
```diff
@@ -112,36 +93,27 @@ end
 
 @register_serialization_type WeylGroup uses_id
 
+type_params(W::WeylGroup) = WeylGroup, root_system(W)
```
Comment (lgoettgens) [inline src/Serialization/LieTheory.jl]: Stupid question maybe: It seems to me that the first return value of `type_params` is always the argument type. Is this a correct observation?
If yes, wouldn't it be possible to refactor that away into the calling function, so that `type_params` loses the first return value? Imo, this could make the code a bit more readable. If there is a reason for this, I am happy to learn about it

Comment (antonydellavecchia) [reply src/Serialization/LieTheory.jl]: maybe there is a way to get a round it, but it was the only way I found I could get the new `save_type_params` to work. See main.jl

File: src/Serialization/main.jl [hunk 4]
```diff
@@ -188,57 +171,133 @@ function save_typed_object(s::SerializerState, x::T, key::Symbol) where T
...
   save_type_params(s, obj)
 end
 
-function save_attrs(s::SerializerState, obj::T) where T
-  !with_attrs(s) && return 
-  if any(attr -> has_attribute(obj, attr), attrs_list(s, T))
-    save_data_dict(s, :attrs) do
-      for attr in attrs_list(s, T)
-        has_attribute(obj, attr) && save_typed_object(s, get_attribute(obj, attr), attr)
+save_type_params(s::SerializerState, obj::Any) = save_type_params(s, type_params(obj)...)
```
Comment (lgoettgens) [inline src/Serialization/main.jl]:
```suggestion
save_type_params(s::SerializerState, obj::Any) = save_type_params(s, typeof(obj), type_params(obj)...)
```

I think this could do the trick

Comment (antonydellavecchia) [reply src/Serialization/main.jl]: yes this is probably fine

Comment (antonydellavecchia) [reply src/Serialization/main.jl]: actually, a little trickier than expected, there is an issue with the containers. 

I'll have to dig deeper, but I dont have time now

Comment (antonydellavecchia) [reply src/Serialization/main.jl]: I've pushed a fix for this now

File: src/Serialization/Groups.jl [hunk 5]
```diff
@@ -157,7 +139,7 @@ end
 
 function load_object(s::DeserializerState, ::Type{PermGroup})
   n = load_object(s, Int, :degree)
-  generators = load_object(s, Vector, (Vector{Int}, Int), :gens)
+  generators = load_object(s, Vector{Vector{Int}}, :gens)
   G = permutation_group(n, [perm(x) for x in generators])
   load_attrs(s, G)
```
Comment (lgoettgens) [inline src/Serialization/Groups.jl]:
```suggestion
```
this can go, right? And similarly the `save_attrs` 6 lines above

Comment (antonydellavecchia) [reply src/Serialization/Groups.jl]: yes

**Comment by lgoettgens** [comment]
In #4563, I encountered more instances of https://github.com/oscar-system/Oscar.jl/issues/3983. It would be great if you could have a look if the new loading code allows for an easy fix of this. (at some point in the refactor, not right now)

**Comment by antonydellavecchia** [comment]
closes #4567

File: src/Serialization/Upgrades/1.3.0.jl [hunk 6]
```diff
@@ -1,16 +1,105 @@
+function upgrade_NamedTuple(d::Dict)
```
Comment (lgoettgens) [inline src/Serialization/Upgrades/1.3.0.jl]:
```suggestion
module SerializationUpgrade-1-3-0

function upgrade_NamedTuple(d::Dict)
```
It would be good to put all of these `upgrade_*` functions into their own shbmodule to not clutter the global namespace. And the next time someone needs to write an upgrade script, it could otherwise lead to name clashes.

Comment (antonydellavecchia) [reply src/Serialization/Upgrades/1.3.0.jl]: This was only temporary because I thought that revise couldn't handle updates inside the function that got pushed into the function list.
Also, it was unsafe because I was evalutating strings from files

**Comment by antonydellavecchia** [comment]
files of all types in src that have serialization tests.
[files_to_update.zip](https://github.com/user-attachments/files/18980076/files_to_update.zip)

**Comment by lgoettgens** [comment]
Would it be possible to split this PR into two separate ones before merging? The github UI doesn't quite like >300 changed files, thus it is not possible to look at the changes that this introduces.
If I understand it correctly, it should be possible to split into the following two parts:
1. All changes to the serialization, upgrade scripts etc.
2. Upgrading everything in `data/` and the artifacts

As the upgrade scripts are contained in 1, the testsuite should even succeed in-between the two PRs. And then one would only need to look at 1 to see the "real" changes. But all of the many completely changed files that github trips over would be part of 2.

I imagine this not being too difficult, but I could be wrong.

File: src/Combinatorics/SimplicialComplexes.jl [hunk 7]
```diff
@@ -637,7 +637,7 @@ function deletion(K::SimplicialComplex, face::Union{<:AbstractSet{Int},<:Abstrac
 end
 
 @doc raw"""
-    automorphism_group(K::SimplicialComplex; action=:on_vertices)
+    automorphism_group(K::SimplicialComplex)
```
Comment (benlorenz) [inline src/Combinatorics/SimplicialComplexes.jl]:
```suggestion
    automorphism_group(K::SimplicialComplex; action=:on_vertices)
```

File: src/Combinatorics/SimplicialComplexes.jl [hunk 8]
```diff
@@ -670,7 +670,7 @@ function automorphism_group(K::SimplicialComplex; action=:on_vertices)
 end
 
 @doc raw"""
-    on_simplicial_complex(K::SimplicialComplex, g::PermGroupElem)
+    on_simplicial_complex(K::SimplicialComplex, g::PermGroupElem;)
```
Comment (benlorenz) [inline src/Combinatorics/SimplicialComplexes.jl]:
```suggestion
    on_simplicial_complex(K::SimplicialComplex, g::PermGroupElem)
```

File: src/PolyhedralGeometry/helpers.jl [hunk 9]
```diff
@@ -317,7 +317,11 @@ function (NF::Hecke.EmbeddedNumField)(x::Polymake.QuadraticExtension{Polymake.Ra
 end
 
 (F::Field)(x::Polymake.Rational) = F(QQ(x))
-(F::Field)(x::Polymake.OscarNumber) = F(Polymake.unwrap(x))
+function (F::Field)(x::Polymake.OscarNumber)
+  #println(Oscar.global_serializer_state.obj_to_id[F])
+  #println(Oscar.global_serializer_state.obj_to_id[parent(Polymake.unwrap(x))])
+  F(Polymake.unwrap(x))
+end
```
Comment (antonydellavecchia) [inline src/PolyhedralGeometry/helpers.jl]:
```suggestion
(F::Field)(x::Polymake.OscarNumber) = F(Polymake.unwrap(x))
```

Comment (benlorenz) [inline src/PolyhedralGeometry/helpers.jl]:
```suggestion
(F::Field)(x::Polymake.OscarNumber) = F(Polymake.unwrap(x))
```

File: src/Serialization/Upgrades/1.2.2.jl
Comment (benlorenz) [inline src/Serialization/Upgrades/1.2.2.jl:1]: please change this file back to 1.3.0 (filename + content) to make it consistent with the 1.3.0 release

File: src/Serialization/Upgrades/main.jl [hunk 10]
```diff
@@ -141,7 +141,8 @@ include("0.13.0.jl")
 include("0.15.0.jl")
 include("1.1.0.jl")
 include("1.2.0.jl")
-include("1.3.0.jl")
+include("1.2.2.jl")
```
Comment (benlorenz) [inline src/Serialization/Upgrades/main.jl]:
```suggestion
include("1.3.0.jl")
```

**Comment by lgoettgens** [comment]
The macos failures are probably due to https://github.com/oscar-system/Oscar.jl/issues/4714

**Review by fingolfin — APPROVED** [review]
Fine by me.

**Review by benlorenz — APPROVED** [review]

**Review by lkastner — APPROVED** [review]

**Comment by lgoettgens** [comment]
@antonydellavecchia could you please come up with approx. 2 sentences about this PR that we can put into the v1.4 release notes?

**Comment by antonydellavecchia** [comment]
Cleaner handling of type parameter serialization. This update forces entries of container types to share the same output of Oscar.type_params when serializing. Deserialization speed improvements.
