### PR TITLE
change `_common_parent_group`

### LINKED ISSUE #894: parents and degrees of PermGroup
```
julia> G = symmetric_group(2)
Sym( [ 1 .. 2 ] )

julia> degree(G)
2

julia> G = symmetric_group(1)
Group(())

julia> degree(G)
0
```
This should be 1.

The next:
```
julia> G = symmetric_group(3)
Sym( [ 1 .. 3 ] )

julia> U = sub(G, [G([1,2,3])])[1]
Group(())
julia> U^U([1,2,3])
Group(())

julia> ans([1,2,3])
ERROR: ArgumentError: the element does not embed in the group
Stacktrace:
 [1] (::PermGroup)(L::Vector{Int64})
   @ Oscar ~/.julia/dev/Oscar/src/Groups/perm.jl:162
 [2] top-level scope
   @ REPL[85]:1
```
so the conjugation looses the degree...

### PR DESCRIPTION
**Pull request by ThomasBreuer**
- define and implement the meaning for the group types,
- add tests for the supported situations

resolves #894

### CODE REVIEW

File: src/Groups/GAPGroups.jl [hunk 1]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
 
+
+# We allow arithmetic operations between two group elements with
+# *nonidentical parents*.
+# In this case, the parent of the resulting element is set according to
+# the following rules, depending on the types of the parents.
+#
+# - `PermGroup`, `PermGroup`:
+#   The operation is allowed whenever the parents have the same degree,
+#   and the parent is the symmetric group of that degree.
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl]: Maybe
```suggestion
#   then the new parent is the symmetric group of that degree.
```
or
```suggestion
#   then the parent of the result is the symmetric group of that degree.
```

File: src/Groups/GAPGroups.jl [hunk 2]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
+#
+# - `PcGroup`, `PcGroup` and
+#   `FPGroup`, `FPGroup`:
+#   The operation is allowed whenever the parents belong to the same `GapObj`
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl]: I don't understand this. When does a `PcGroup` group "belong" to a `GapObj`?

File: src/Groups/GAPGroups.jl [hunk 3]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
+# - `DirectProductGroup`, `DirectProductGroup`:
+#   The operation is allowed whenever the two groups have the same `.L`
+#   field, and the parent is the direct product of these groups.
+#
+# For other types of groups, we throw an exception if the parent groups are
+# not equal and their `GapObj`s are not equal.
+#
+# Note that we cannot guarantee that the groups objects in question are
+# *identical*, only that their `GapObj`s are *equal*:
+# On the GAP side, the same group can be created several times,
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl]: Maybe add that this applies to perm groups, but not to pc and fp groups?

File: src/Groups/GAPGroups.jl [hunk 4]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
+# the parent of the result).
+#
+function _common_parent_group(x::PermGroup, y::PermGroup)
+  x === y && return x
+  @req degree(x) == degree(y) "the groups have different degrees"
+  return symmetric_group(degree(x))
+end
+
+function _common_parent_group(x::PcGroup, y::PcGroup)
+  (x === y || GapObj(x) == GapObj(y)) && return x
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl]: Does `==` for `PcGroup` do anything besides compare identity?

If so, wouldn't this be sufficient?
```suggestion
  (GapObj(x) === GapObj(y)) && return x
```

File: src/Groups/GAPGroups.jl [hunk 5]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
+  throw(ArgumentError("the groups are not compatible"))
+end
+
+function _common_parent_group(x::FPGroup, y::FPGroup)
+  (x === y || GapObj(x) == GapObj(y)) && return x
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl]: Same questions as for `PCGroup`
```suggestion
  (GapObj(x) === GapObj(y)) && return x
```

File: src/Groups/GAPGroups.jl [hunk 6]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
+  throw(ArgumentError("the groups are not compatible"))
+end
+
+function _common_parent_group(x::SubPcGroup, y::SubPcGroup)
+  x === y && return x
+  @req x.full_group == y.full_group "the groups belong to different full groups"
+  return x.full_group
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl]: So this is not type stable then, it sometimes gives a `SubPcGroup` and sometimes a `PcGroup`. Hrm, that's annoying, but I see no immediate way to resolve it, unless we were to make the "full group" deliberately a `SubPcGroup` that is an index 1 subgroup of the `PcGroup`...

File: src/Groups/GAPGroups.jl [hunk 7]
```diff
@@ -216,27 +216,126 @@ function rand_pseudo(G::GAPGroup; radius::Int = 10)
...
+  return y
+end
+
+function _common_parent_group(x::PcGroup, y::SubPcGroup)
+  @req y.full_group == x "the groups belong to different full groups"
+  return x
+end
+
+function _common_parent_group(x::SubFPGroup, y::SubFPGroup)
+  x === y && return x
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl:319]: Same as for `PcGroup` :-/

File: src/Groups/perm.jl [hunk 8]
```diff
@@ -286,7 +286,9 @@ function cperm()
 end
 
 function cperm(L1::AbstractVector{T}, L::AbstractVector{T}...) where T <: IntegerUnion
-  return prod([PermGroupElem(symmetric_group(maximum(y)), GAPWrap.CycleFromList(GAP.Obj([Int(k) for k in y]))) for y in [L1, L...]])
+  cycles = [L1, L...]
+  n = maximum(map(maximum, cycles))
+  return prod([PermGroupElem(symmetric_group(n), GAPWrap.CycleFromList(GAP.Obj([Int(k) for k in y]))) for y in cycles])
```
Comment (fingolfin) [inline src/Groups/perm.jl:291]: Argh, this reminds me I really need to submit a PR for my rewrite of `cperm` and friends.


Also, this method is still inefficient because it creates a fresh `symmetric_group` each time. Either we cache those (see issue #129) or perhaps we should just disallow this without an explicit parent group (well, not immediately to stay compatible with 1.0, but at least we could deprecate this). Thoughts, @fieker ?

**Review by fingolfin — COMMENTED** [review]
Thank you! Some quick thoughts

File: src/Groups/GAPGroups.jl (hunk 4 above)
Comment (ThomasBreuer) [reply src/Groups/GAPGroups.jl]: The question is what we want to support.
Currently the following works.
```
julia> g = small_group(24, 12);

julia> gg = GAP.Globals.Group(GAP.Globals.GeneratorsOfGroup(GapObj(g)));

julia> newg = PcGroup(gg);

julia> newg == g
true
```
If we want to achieve that two `PcGroup`s are equal only if their `GapObj`s are identical then we have to change `PcGroup`. Likewise for `FPGroup`s. I do not expect difficulties from such a change.

File: src/Groups/GAPGroups.jl (hunk 5 above)
Comment (ThomasBreuer) [reply src/Groups/GAPGroups.jl]: (see the comment for `PcGroup`)

File: src/Groups/GAPGroups.jl (hunk 6 above)
Comment (ThomasBreuer) [reply src/Groups/GAPGroups.jl]: Taking that index 1 subgroups in `PcGroup`s occur already in many places because of these type conventions (the first member in `derived_series(G)` etc.), we can return always a `SubPcGroup`.
Currently the `SubPcGroup` stores the full `PcGroup`, thus fetching this `.full_group` is cheap, compared to wrapping a new `SubPcGroup`. Perhaps the `SubPcGroup` should store an index 1 subgroup instead?

File: src/Groups/GAPGroups.jl (hunk 3 above)
Comment (ThomasBreuer) [reply src/Groups/GAPGroups.jl]: See the code example about `PcGroup` below.

File: src/Groups/GAPGroups.jl (hunk 2 above)
Comment (ThomasBreuer) [reply src/Groups/GAPGroups.jl]: O.k., let us say "have the same `GapObj`".

File: src/Groups/GAPGroups.jl (hunk 6 above)
Comment (ThomasBreuer) [reply src/Groups/GAPGroups.jl]: Hmm, if we want that a `SubPcGroup` stores a `SubPcGroup` as its `full_group` then we have the logical problem that the `SubPcGroup` constructor takes a `GapObj` and calls `SubPcGroup` for its full group, an infinite recursion ...

File: src/Groups/GAPGroups.jl [hunk 9]
```diff
@@ -224,50 +224,64 @@ end
...
 #   `SubFPGroup`, `FPGroup` and
 #   `FPGroup`, `SubFPGroup`:
 #   The operation is allowed whenever the `full_group` of the `SubPcGroup`
-#   (`SubFPGroup`) is equal to the `PcGroup` (`FPGroup`)
-#   (in the sense of `==´), and the `PcGroup` (`FPGroup`) is taken.
+#   (`SubFPGroup`) and the `PcGroup` (`FPGroup`) have the same `GapObj`
+#   (in the sense of `===´),
+#   then the `full_group` of the `SubPcGroup` (`SubFPGroup`) is taken
+#   as the parent of the result.
+#   Note that we take a group of type `SubPcGroup` (`SubFpGroup`).
```
Comment (fingolfin) [inline src/Groups/GAPGroups.jl:251]: Perhaps we should explain why (i.e. type stability, e.g. when multiplying elements with identical parent)

**Review by fingolfin — APPROVED** [review]
