### PR TITLE
Polyhedral: rework input type handling, add support for QQBarField objects

### LINKED ISSUE #3286: Support for polytopes with (real) `QQBar` coefficients?
Our implementation of the algebraic closure of the rationals, `QQBar` / `CalciumQQBar`, is quite nice and it comes with an "automatic" real or complex embedding of its elements.

It would be quite handy if one could directly take a bunch of vectors over this field, and create polyhedra/polytopes from this. E.g. construct a convex hull and visualize it. I guess this is related to currently ongoing work for doing this for embedded number fields.

Example:
```
julia> e = one(CalciumQQBar)
Root 1.00000 of x - 1

julia> s, c = sinpi(2*e/5), cospi(2*e/5)
(Root 0.951057 of 16x^4 - 20x^2 + 5, Root 0.309017 of 4x^2 + 2x - 1)

julia> pts = [ [e, e], [s,c], [c,s] ]
3-element Vector{Vector{qqbar}}:
 [Root 1.00000 of x - 1, Root 1.00000 of x - 1]
 [Root 0.951057 of 16x^4 - 20x^2 + 5, Root 0.309017 of 4x^2 + 2x - 1]
 [Root 0.309017 of 4x^2 + 2x - 1, Root 0.951057 of 16x^4 - 20x^2 + 5]

julia> P = convex_hull(pts)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type qqbar
```

This initial error is easy to fix, just something missing in Nemo (see https://github.com/Nemocas/Nemo.jl/issues/1650).

But after adding the missing conversion method, there are more errors inside PolyhedralGeometry specific code I am not familiar with. So in particular I don't know hard it would be to do in general.

But in this case, I managed to proceed quite nicely after converting to floating point:
```
julia> Base.convert(::Type{Float64}, x::qqbar) = Float64(ArbField(64)(x))  # TODO: add to Nemo

julia> Vector{Vector{Float64}}(pts)
3-element Vector{Vector{Float64}}:
 [1.0, 1.0]
 [0.9510565162951535, 0.30901699437494745]
 [0.30901699437494745, 0.9510565162951535]

julia> P = convex_hull(Vector{Vector{Float64}}(pts))
Polyhedron in ambient dimension 2

julia> visualize(P)
```
which gave me
Screen Shot 2024-01-31 at 15 34 41

### PR DESCRIPTION
**Pull request by benlorenz**
fixes #3286:

```julia
julia> e = one(CalciumQQBar)
Root 1.00000 of x - 1

julia> s, c = sinpi(2*e/5), cospi(2*e/5)
(Root 0.951057 of 16x^4 - 20x^2 + 5, Root 0.309017 of 4x^2 + 2x - 1)

julia> pts = [ [e, e], [s,c], [c,s] ]
3-element Vector{Vector{QQBarFieldElem}}:
 [Root 1.00000 of x - 1, Root 1.00000 of x - 1]
 [Root 0.951057 of 16x^4 - 20x^2 + 5, Root 0.309017 of 4x^2 + 2x - 1]
 [Root 0.309017 of 4x^2 + 2x - 1, Root 0.951057 of 16x^4 - 20x^2 + 5]

julia> P = convex_hull(pts)
Polyhedron in ambient dimension 2 with QQBarFieldElem type coefficients

julia> facets(P)
3-element SubObjectIterator{AffineHalfspace{QQBarFieldElem}} over the Halfspaces of R^2 described by:
(Root -0.0708317 of 25x^4 + 100x^3 + 90x^2 + 20x + 1)*x_1 + x_2 <= Root 0.929168 of 25x^4 - 60x^2 + 40x - 4
-x_1 - x_2 <= Root -1.26007 of 4x^4 - 4x^3 - 6x^2 + 6x - 1
(Root 14.1180 of x^4 - 20x^3 + 90x^2 - 100x + 25)*x_1 - x_2 <= Root 13.1180 of x^4 - 16x^3 + 36x^2 + 24x - 4


julia> volume(P)
Root 0.237531 of 256x^4 - 128x^3 - 656x^2 + 408x - 59

julia> f_vector(P)
2-element Vector{ZZRingElem}:
 3
 3

julia> visualize(P)

```
triangle

### CODE REVIEW

**Comment by thofma** [comment]
(The printing of the `QQBarElem` is really awful in this application. Any suggestions to improve it are welcome.)

**Review by fingolfin — APPROVED** [review]
Awesome, thank you very much!

File: src/PolyhedralGeometry/helpers.jl [hunk 1]
```diff
@@ -407,47 +408,76 @@ function _embedded_quadratic_field(r::ZZRingElem)
...
+_find_elem_type(x::AbstractArray{<:AbstractArray}) = vcat(_find_elem_type.(x)...)
+_find_elem_type(x::MatElem) = elem_type(base_ring(x))
+
+function _guess_fieldelem_type(x...)
+  types = filter(!=(Any), vcat(_find_elem_type.(x)...))
+  T = QQFieldElem
+  for t in types
+    if t == Float64
+      return Float64
+    elseif promote_type(t, QQFieldElem) != QQFieldElem
```
Comment (benlorenz) [inline src/PolyhedralGeometry/helpers.jl]:
```suggestion
    elseif promote_type(t, T) != T
```
