### PR TITLE
Fix finite field conversion between OSCAR and GAP

### LINKED ISSUE #2027: CI tests broken, failures related to GAP code
I am seeing these warnings when loading OSCAR now (possibly since merging PR #1988 by @ThomasBreuer ?)
<s>
```
WARNING: Method definition julia_to_gap(Base.Set{T}) where {T} in module GAP at /Users/mhorn/Projekte/OSCAR/GAP.jl/src/julia_to_gap.jl:163 overwritten in module Oscar at /Users/mhorn/Projekte/OSCAR/Oscar.spielwiese/src/GAP/oscar_to_gap.jl:52.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition julia_to_gap(Base.Set{T}, Base.IdDict{Any, Any}) where {T} in module GAP at /Users/mhorn/Projekte/OSCAR/GAP.jl/src/julia_to_gap.jl:163 overwritten in module Oscar at /Users/mhorn/Projekte/OSCAR/Oscar.spielwiese/src/GAP/oscar_to_gap.jl:52.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition kwcall(Any, typeof(GAP.julia_to_gap), Base.Set{T}) where {T} in module GAP at /Users/mhorn/Projekte/OSCAR/GAP.jl/src/julia_to_gap.jl:163 overwritten in module Oscar at /Users/mhorn/Projekte/OSCAR/Oscar.spielwiese/src/GAP/oscar_to_gap.jl:52.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition kwcall(Any, typeof(GAP.julia_to_gap), Base.Set{T}, Base.IdDict{Any, Any}) where {T} in module GAP at /Users/mhorn/Projekte/OSCAR/GAP.jl/src/julia_to_gap.jl:163 overwritten in module Oscar at /Users/mhorn/Projekte/OSCAR/Oscar.spielwiese/src/GAP/oscar_to_gap.jl:52.
  ** incremental compilation may be fatally broken for this module **
```
</s>

UPDATE: sorry, those warnings came from my Oscar looking at a dev version of GAP.jl. But the CI failures are real, see e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/4379175069

### PR DESCRIPTION
**Pull request by fingolfin**
Yet another attempt to fix #2027

Closes #2028
Closes #2029

### CODE REVIEW

File: src/GAP/iso_oscar_gap.jl [hunk 1]
```diff
@@ -70,9 +70,12 @@ function _iso_oscar_gap_field_finite_functions(FO::Union{Nemo.fpField, Nemo.FpFi
    return (f, finv)
 end
 
+Nemo.lift(R::ZZRing, x::ZZRingElem) = x
+Nemo.lift(R::ZZRing, x::Integer) = ZZRingElem(x)
```
Comment (fingolfin) [inline src/GAP/iso_oscar_gap.jl]: I think having these would be useful in Nemo in general? @fieker @thofma ?

But if these are undesirable, I can revise the fix here to instead properly distinguish based on the type of `FO` (I plan to do that anyway). But this takes more time, and for now I just want to fix the CI as quickly as possible.

File: src/GAP/iso_oscar_gap.jl [hunk 2]
```diff
@@ -70,9 +70,12 @@ function _iso_oscar_gap_field_finite_functions(FO::Union{Nemo.fpField, Nemo.FpFi
...
+
 function _iso_oscar_gap_field_finite_functions(FO::Union{FqPolyRepField, FqField, fqPolyRepField}, FG::GAP.GapObj)
    p = characteristic(FO)
-   d = degree(FO)
+   d = degree(FO)::Int
```
Comment (fingolfin) [inline src/GAP/iso_oscar_gap.jl]: Somehow it wasn't able to infer the return value of `degree` here. I am looking into a proper fix now

File: src/GAP/iso_oscar_gap.jl [hunk 3]
```diff
@@ -103,7 +106,7 @@ function _iso_oscar_gap_field_finite_functions(FO::Union{FqPolyRepField, FqField
      F = FO
 
      f = function(x)
-       v = [GAP.Obj(coeff(x, i)) for i in 0:(d - 1)]
+       v = [GAP.Obj(lift(ZZ, coeff(x, i))) for i in 0:(d - 1)]
```
Comment (fingolfin) [inline src/GAP/iso_oscar_gap.jl]: Plan for later: use `Nemo._coeff` for `FqField`, and otherwise `coeff`? But does that mean `coeff` returns integers for other finite fields? Are these then also "wrong" ??

Anyway, for now this was the quickest way I saw to make this work -- well, at least locally on my machine... there is also a problem due to root/roots in Hecke, but @thofma is working on that.

File: src/GAP/iso_oscar_gap.jl (hunk 1 above)
Comment (thofma) [reply src/GAP/iso_oscar_gap.jl]: Hm, I am not a big fan. This is all just coercion, for which we do not use the word `lift`.

**Comment by fingolfin** [comment]
Seems to be working so far. The other failures are due to Hecke but @thofma is already working on a fix

**Review by thofma — APPROVED** [review]
Good assuming CI passes with the new Hecke release

**Comment by fingolfin** [comment]
I have a version of this ready which avoids `lift`, but I am waiting for the Hecke release to update the branch.
