### PR TITLE
test/PolyhedralGeometry: make sure to select correct roots / embedding

### LINKED ISSUE #4906: Nightly failure with polyhedra over embedded number fields
Failing on nightly CI: `Expression: volume(sd) == (8r) // 12 * (6pq2 + 2 * r * q)` and `Expression: _edge_length_for_test.(faces(sd, 1)) == repeat([4], 18)` (https://github.com/oscar-system/Oscar.jl/actions/runs/15125832782/job/42517587500#step:11:6439). The difference between nightly and 1.11 seems to be the ordering of roots in https://github.com/oscar-system/Oscar.jl/blob/852b6d1a33ed53581040b876a816bb33fac714aa/test/PolyhedralGeometry/scalar_types.jl#L21-L22.

This seems to be about polyhedra over embedded number fields. @benlorenz @thofma I don't know who of you is more into this, could one of you please have a look?

### PR DESCRIPTION
**Pull request by benlorenz**
To fix some more errors seen on nightly.

### CODE REVIEW

File: test/PolyhedralGeometry/scalar_types.jl [hunk 1]
```diff
@@ -15,11 +15,12 @@
...
-  L, = number_field(y^2 - (2 - r^2)//2, "q")
+  L, lq = number_field(y^2 - (2 - r^2)//2, "q")
   Lz, z = L[:z]
-  E, q = Hecke.embedded_field(L, real_embeddings(L)[2])
-  pq1 = E(roots(z^2 - (3 + 2r - r^2))[2])
-  pq2 = E(roots(z^2 - (3 - r^2))[1])
+  emb = only(filter(x -> is_positive(lq, x), real_embeddings(L)))
+  E, q = Hecke.embedded_field(L, emb)
+  pq1 = only(filter(x -> x > 0, E.(roots(z^2 - (3 + 2r - r^2)))))
+  pq2 = only(filter(x -> x > 0, E.(roots(z^2 - (3 - r^2)))))
```
Comment (lgoettgens) [inline test/PolyhedralGeometry/scalar_types.jl]:
```suggestion
  pq1 = only(filter(is_positive, E.(roots(z^2 - (3 + 2r - r^2)))))
  pq2 = only(filter(is_positive, E.(roots(z^2 - (3 - r^2)))))
```
does this work as well?
If not, maybe replace by 
```suggestion
  pq1 = only(filter(>(0), E.(roots(z^2 - (3 + 2r - r^2)))))
  pq2 = only(filter(>(0), E.(roots(z^2 - (3 - r^2)))))
```
to eliminate some anonymous functions (with extra compilation needed)

Comment (benlorenz) [reply test/PolyhedralGeometry/scalar_types.jl]: I only tried `ispositive` but `is_positive` does work. I also used it for the embeddings using `Base.Fix1` (which hopefully works on all relevant julia versions).

**Comment by lgoettgens** [comment]
`Base.ispositive` has only been added recently in https://github.com/JuliaLang/julia/pull/53677, but we should indeed make sure to alias that in recent enough julia versions

**Comment by benlorenz** [comment]
At least locally this seems to work for this testgroup, in the CI we won't know because for some reason `setup-julia` now installs a ten days old nightly version:
```
Julia Version 1.13.0-DEV.571
Commit c13ea2b4f0f (2025-05-10 14:30 UTC)
```
(both on oscarci-linux and on the github runner...)

_Edit:_ DEV.571 (`c13ea2b4f0f`) should be fine, I confused it with the version (`1.13.0-DEV.564`) used in the scheduled run here (https://github.com/oscar-system/Oscar.jl/actions/runs/15128181986/job/42524037184#step:4:10) which doesn't include the rapidhash change.

**Review by lgoettgens — APPROVED** [review]
Looks sensible, thanks

**Comment by lgoettgens** [comment]
ahh, stupid miss-click... didn't want to "update branch"...
