### PR TITLE
polyhedral: use dehomogenize from polymake

### LINKED ISSUE #4024: `relative_interior_point` returns wrong point
This bug was found together with @oskarhenriksson and @paulhelminck.

```
using Oscar

T = tropical_semiring()
R,(x,y,z) = T["x","y","z"]
g = T(3)*x + T(6)*y + T(5)*z + T(1)
TropL = tropical_hypersurface(g)

sigma = first(maximal_polyhedra(TropL))
w = relative_interior_point(sigma)
w in sigma # returns false, should be true
```

### PR DESCRIPTION
**Pull request by benlorenz**
- this is (I think) used only for polymake types anyway
- it properly takes care of the homogenization entry
- directly use vector entries for linear objective (since this is not a point/ray)
- test for dehomogenized rel_int_point with non-normalized first coordinate

fixes #4024:
```julia
julia> T = tropical_semiring()
Min tropical semiring

julia> R,(x,y,z) = T["x","y","z"]
(Multivariate polynomial ring in 3 variables over min tropical semiring, AbstractAlgebra.Generic.MPoly{TropicalSemiringElem{typeof(min)}}[x, y, z])

julia> g = T(3)*x + T(6)*y + T(5)*z + T(1)
(3)*x + (6)*y + (5)*z + (1)

julia> TropL = tropical_hypersurface(g)
Min tropical hypersurface

julia> sigma = first(maximal_polyhedra(TropL))
Polyhedron in ambient dimension 3

julia> w = relative_interior_point(sigma)
3-element PointVector{QQFieldElem}:
 -3
 -6
 -4

julia> w in sigma # returns false, should be true
true
```

### CODE REVIEW

**Review by lkastner — APPROVED** [review]

File: test/PolyhedralGeometry/polyhedron.jl [hunk 1]
```diff
@@ -236,6 +236,12 @@
     @test n_rays(Q1) == 1
     @test lineality_dim(Q2) == 1
     @test relative_interior_point(Q0) == [1//3, 1//3]
+
+    # issue #4024
+    let op = Polyhedron{T}(Polymake.polytope.Polytope(REL_INT_POINT=f.([1//3, -1, -2, -4//3])), f)
+      @test relative_interior_point(op) == f.([-3, -6, -4])
+    end
```
Comment (benlorenz) [inline test/PolyhedralGeometry/polyhedron.jl]:
```suggestion
    let op = Polyhedron{T}(Polymake.polytope.Polytope{Polymake.OscarNumber}(REL_INT_POINT=f.([1//3, -1, -2, -4//3]), CONE_AMBIENT_DIM=4), f)
      @test relative_interior_point(op) == point_vector(f, [-3,-6,-4])
    end
```

File: test/PolyhedralGeometry/polyhedron.jl [hunk 2]
```diff
@@ -236,6 +236,12 @@
     @test n_rays(Q1) == 1
     @test lineality_dim(Q2) == 1
     @test relative_interior_point(Q0) == [1//3, 1//3]
+
+    # issue #4024
+    let op = Polyhedron{T}(Polymake.polytope.Polytope{Polymake.OscarNumber}(REL_INT_POINT=f.([1//3, -1, -2, -4//3]), CONE_AMBIENT_DIM=4), f)
```
Comment (benlorenz) [inline test/PolyhedralGeometry/polyhedron.jl]:
```suggestion
    let op = Polyhedron{T}(Polymake.polytope.Polytope{Oscar._scalar_type_to_polymake(T)}(REL_INT_POINT=f.([1//3, -1, -2, -4//3]), CONE_AMBIENT_DIM=4), f)
```
