### PR TITLE
Fix for issue #4865 (Output of `groebner_walk` is not reduced)

### LINKED ISSUE #4865: Output of `groebner_walk` is not reduced
bug report

**Describe the bug**
Excepted a reduced Groebner Basis as output of groebner_walk(...,lex(PolAlg),...). 

**To Reproduce**
```
using Oscar

PolAlg, (x1,x2,x3) =  polynomial_ring(QQ,[:x1;:x2;:x3])
G = [x1 + 2*x2 + 2*x3 - 1,x1^2 - x1 + 2*x2^2 + 2*x3^2,2*x1*x2 + 2*x2*x3 - x2]
F = gens(groebner_walk(ideal(G),lex(PolAlg),wdegrevlex(PolAlg,[1,2,13]),algorithm=:standard))
println(F)
println(gens(groebner_basis(ideal(G),ordering=lex(PolAlg),complete_reduction=true)))
```

**Expected behavior**
Expected gens of ideal which are the same as the gens received from groebner_basis(...,lex(PolAlg),complete_reduction=true)

**System (please complete the following information):**
```
OSCAR version 1.4.0-DEV - #master, f0ca693f60 -- 2025-04-23 10:39:27 +0200
  combining:
    AbstractAlgebra.jl   v0.44.11
    GAP.jl               v0.13.1
    Hecke.jl             v0.35.18
    Nemo.jl              v0.49.3
    Polymake.jl          v0.11.28
    Singular.jl          v0.25.2
  building on:
    FLINT_jll                  v300.200.100+0
    GAP_jll                    v400.1400.3+0
    GAP_lib_jll                v400.1400.4+0
    Singular_jll               v404.100.104+0
    libpolymake_julia_jll      v0.13.2+0
    libsingular_julia_jll      v0.47.2+0
    polymake_jll               v400.1300.3+0
    polymake_oscarnumber_jll   v0.3.5+0
See `]st -m` for a full list of dependencies.

Julia Version 1.11.5
Commit 760b2e5b739 (2025-04-14 06:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i5-1235U
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
Official https://julialang.org/ release
```

**Additional context**
Potential Fix:
```
function standard_walk(...)
...
while current_weight != target_weight
       ......
#add after loop
G = standard_step(G,current_weight,target)
...
return G
```

this gives as output a reduced groebner_basis with respect to ordering lex

### PR DESCRIPTION
**Pull request by ooinaruhugh**
This is a small fix for issue #4865.
This will be followed by more test cases and rework for `groebner_walk`.

### CODE REVIEW

**Comment by ooinaruhugh** [comment]
Also, I can't assign labels, so this probably needs a "release notes: not needed" label

File: experimental/GroebnerWalk/test/standard_walk.jl [hunk 1]
```diff
@@ -20,5 +20,9 @@
     @test is_groebner_basis(groebner_walk(I3); ordering=lex(R1))
     #@test bounding_vectors(G3) == ZZ.([[6,0,0]])
     #@test next_weight(G3, ZZ.([1,1,1]), ZZ.([1,0,0])) == ZZ.([1,0,0])
+    
+    G = [x + 2*y + 2*z - 1, x^2 - x + 2*y^2 + 2*z^2, 2*x*y + 2*y*z - y];
```
Comment (lgoettgens) [inline experimental/GroebnerWalk/test/standard_walk.jl]:
```suggestion
    # issue #4865
    G = [x + 2*y + 2*z - 1, x^2 - x + 2*y^2 + 2*z^2, 2*x*y + 2*y*z - y];
```

File: experimental/GroebnerWalk/test/standard_walk.jl [hunk 2]
```diff
@@ -20,5 +20,10 @@
     @test is_groebner_basis(groebner_walk(I3); ordering=lex(R1))
     #@test bounding_vectors(G3) == ZZ.([[6,0,0]])
     #@test next_weight(G3, ZZ.([1,1,1]), ZZ.([1,0,0])) == ZZ.([1,0,0])
+    
+    # issue #4865
+    G = [x + 2*y + 2*z - 1, x^2 - x + 2*y^2 + 2*z^2, 2*x*y + 2*y*z - y];
+    I = ideal(G);
```
Comment (fingolfin) [inline experimental/GroebnerWalk/test/standard_walk.jl]:
```suggestion
    G = [x + 2*y + 2*z - 1, x^2 - x + 2*y^2 + 2*z^2, 2*x*y + 2*y*z - y]
    I = ideal(G)
```

**Comment by ederc** [comment]
Failing doctests are only due to different order of generators printed.

**Comment by fingolfin** [comment]
@ooinaruhugh see https://docs.oscar-system.org/dev/DeveloperDocumentation/documentation/#Automatically-repairing-jldoctests for information on how to automatically update the tests to match the new output.

**Comment by fingolfin** [comment]
since @ooinaruhugh is travelling, @ederc volunteered to fix up the tests (thanks!)

**Comment by ederc** [comment]
Fine for me to be merged.

**Review by fingolfin — APPROVED** [review]
