### PR TITLE
fix for rational function field

### LINKED ISSUE #5458: Serialization of `RationalFunctionFieldElem` is completely broken
There are two ways to create a RationalFunctionField in one indeterminate: using a univariate backend, or using a multivariate backend that just happens to know about a single variable.
When trying to load an element from a different julia session, in the former case the element loads but has wrong printing, while in the latter case loading is not possible at all.

```julia
julia> Qu, u = rational_function_field(QQ, "u")
(Rational function field over QQ, u)

julia> Qu2, (u2,) = rational_function_field(QQ, ["u"])
(Rational function field over QQ, AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQMPolyRingElem}[u])

julia> save("u.mrdi", u)

julia> save("u2.mrdi", u2)

julia> Oscar.Serialization.reset_global_serializer_state()
Dict{Base.UUID, Any}()

julia> load("u.mrdi")
["u"]

julia> load("u2.mrdi")
ERROR: MethodError: no method matching parse(::Type{Int64}, ::JSON3.Array{String, Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}})
The function `parse` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  parse(::Type{Union{}}, ::Any...; kwargs...)
   @ Base parse.jl:39
  parse(::Type{T}, ::AbstractString; kwargs...) where T<:Real
   @ Base parse.jl:394
  parse(::Type{T}, ::AbstractString; base) where T<:Integer
   @ Base parse.jl:253
  ...

Stacktrace:
  [1] (::Oscar.Serialization.var"#77#78"{Int64})(str::JSON3.Array{String, Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/basic_types.jl:72
  [2] load_node(f::Oscar.Serialization.var"#77#78"{Int64}, s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}, key::Nothing)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
  [3] load_node
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:238 [inlined]
  [4] load_object(s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}, ::Type{Int64})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/basic_types.jl:71
  [5] (::Oscar.Serialization.var"#63#64"{Oscar.Serialization.DeserializerState{…}, DataType})(::JSON3.Array{String, Base.CodeUnits{…}, SubArray{…}})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:443
  [6] load_node(f::Oscar.Serialization.var"#63#64"{Oscar.Serialization.DeserializerState{…}, DataType}, s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}, key::Int64)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
  [7] load_object
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:442 [inlined]
  [8] (::Oscar.Serialization.var"#308#312"{Oscar.Serialization.DeserializerState{…}})(::JSON3.Array{Any, Base.CodeUnits{…}, SubArray{…}})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/Rings.jl:206
  [9] load_node(f::Oscar.Serialization.var"#308#312"{Oscar.Serialization.DeserializerState{…}}, s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}, key::Int64)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
 [10] (::Oscar.Serialization.var"#307#311"{Oscar.Serialization.DeserializerState{…}, QQPolyRing})(terms::JSON3.Array{JSON3.Array, Base.CodeUnits{…}, SubArray{…}})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/Rings.jl:205
 [11] load_node(f::Oscar.Serialization.var"#307#311"{…}, s::Oscar.Serialization.DeserializerState{…}, key::Nothing)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
 [12] load_node
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:238 [inlined]
 [13] load_object(s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}, ::Type{QQPolyRingElem}, parent_ring::QQPolyRing)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/Rings.jl:198
 [14] (::Oscar.Serialization.var"#258#261"{Oscar.Serialization.DeserializerState{…}, DataType, QQPolyRing})(::JSON3.Array{JSON3.Array, Base.CodeUnits{…}, SubArray{…}})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/Fields.jl:324
 [15] load_node(f::Oscar.Serialization.var"#258#261"{…}, s::Oscar.Serialization.DeserializerState{…}, key::Int64)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
 [16] (::Oscar.Serialization.var"#257#260"{…})(::JSON3.Array{…})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/Fields.jl:323
 [17] load_node(f::Oscar.Serialization.var"#257#260"{…}, s::Oscar.Serialization.DeserializerState{…}, key::Nothing)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
 [18] load_node
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:238 [inlined]
 [19] load_object(s::Oscar.Serialization.DeserializerState{…}, ::Type{…}, parent_ring::AbstractAlgebra.Generic.RationalFunctionField{…})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/Fields.jl:322
 [20] (::Oscar.Serialization.var"#61#62"{Oscar.Serialization.DeserializerState{…}})(::JSON3.Array{JSON3.Array, Base.CodeUnits{…}, SubArray{…}})
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:435
 [21] load_node(f::Oscar.Serialization.var"#61#62"{Oscar.Serialization.DeserializerState{…}}, s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}, key::Symbol)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/serializers.jl:246
 [22] load_typed_object(s::Oscar.Serialization.DeserializerState{Oscar.Serialization.JSONSerializer}; override_params::Nothing)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:434
 [23] load(io::IOStream; params::Nothing, type::Nothing, serializer::Oscar.Serialization.JSONSerializer, with_attrs::Bool)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:819
 [24] load
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:754 [inlined]
 [25] #546
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:849 [inlined]
 [26] open(f::Oscar.Serialization.var"#546#547"{Nothing, Nothing, Oscar.Serialization.JSONSerializer}, args::String; kwargs::@Kwargs{})
    @ Base ./io.jl:410
 [27] open
    @ ./io.jl:407 [inlined]
 [28] #load#545
    @ ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:848 [inlined]
 [29] load(filename::String)
    @ Oscar.Serialization ~/.julia/packages/Oscar/6oHzG/src/Serialization/main.jl:845
 [30] top-level scope
    @ REPL[19]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.5.0
  combining:
    AbstractAlgebra.jl   v0.47.3
    GAP.jl               v0.15.3
    Hecke.jl             v0.38.7
    Nemo.jl              v0.52.1
    Polymake.jl          v0.13.3
    Singular.jl          v0.26.0
  building on:
    FLINT_jll                  v301.300.102+0
    GAP_jll                    v400.1401.5+0
    GAP_lib_jll                v400.1400.5+0
    Singular_jll               v404.100.301+0
    libpolymake_julia_jll      v0.14.2+0
    libsingular_julia_jll      v0.47.6+0
    polymake_jll               v400.1500.0+0
    polymake_oscarnumber_jll   v0.3.11+0
See `]st -m` for a full list of dependencies.

Julia Version 1.11.7
Commit f2b3dbda30a (2025-09-08 12:10 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Official https://julialang.org/ release

```

**Additional context**
I noticed this while debugging the remaining failure in https://github.com/oscar-system/Oscar.jl/pull/5451. Some internal change between JSON3 and JSON v1.0 also lets the former case error, so this issue here must be resolved before I can continue work on https://github.com/oscar-system/Oscar.jl/pull/5451.

One breadcrumb: both type param parts of the mrdi files are identical. So I don't think that the deserializer is able to distinguish the two different backends from that place. However, the data is indeed different.

### PR DESCRIPTION
**Pull request by antonydellavecchia**
closes #5458

might need an upgrade

### CODE REVIEW

File: src/Serialization/Fields.jl [hunk 1]
```diff
@@ -286,21 +286,20 @@ function save_object(s::SerializerState,
                      RF::AbstractAlgebra.Generic.RationalFunctionField)
   save_data_dict(s) do
     syms = symbols(RF)
-    save_object(s, syms, :symbols)
+
+    if isone(length(syms))
```
Comment (lgoettgens) [inline src/Serialization/Fields.jl]: this is not the correct check here, as this could also be a multivariate setting with a single indeterminant.
The correct way to distinguish the two scenarios is by the second type variable of RationalFunctionField

File: src/Serialization/Fields.jl [hunk 2]
```diff
@@ -283,24 +283,25 @@ end
...
   save_data_dict(s) do
     syms = symbols(RF)
     save_object(s, syms, :symbols)
   end
 end
 
+function save_object(s::SerializerState,
+                     RF::AbstractAlgebra.Generic.RationalFunctionField{<:FieldElem, <: PolyRingElem})
+  save_data_dict(s) do
+    save_object(s, symbols(RF)[1], :symbol)
```
Comment (lgoettgens) [inline src/Serialization/Fields.jl:296]:
```suggestion
    save_object(s, only(symbols(RF)), :symbol)
```
To notice if this returns more symbols than expected

File: src/Serialization/Upgrades/1.6.0-1.jl [hunk 3]
```diff
@@ -0,0 +1,16 @@
+push!(upgrade_scripts_set, UpgradeScript(
+  v"1.6.0-1",
+  function upgrade_1_6_0_1(s::UpgradeState, dict::Dict)
+    # recurse upgrade on containers
+    upgrade_containers(upgrade_1_6_0_1, s, dict)
+
+    # Upgrades
+    if dict[:_type] isa Dict && dict[:_type][:name] == "RationalFunctionField"
```
Comment (lgoettgens) [inline src/Serialization/Upgrades/1.6.0-1.jl:8]:
```suggestion
    if dict[:_type] isa Dict && haskey(dict[:_type], :name) && dict[:_type][:name] == "RationalFunctionField"
```
Otherwise the second part of the condition could fail

**Review by lgoettgens — APPROVED** [review]
Thanks for the quick fix, looks good in general. Two minor comments
