### PR TITLE
some bypass surgery for pmap

### LINKED ISSUE #5218: `pmap` gets stuck with Oscar worker pools
As reported on slack and as reproduced by @simonbrandhorst:
```
julia> using Revise, Oscar, Distributed
  ___   ___   ___    _    ____
 / _ \ / __\ / __\  / \  |  _ \  | Combining and extending ANTIC, GAP,
| |_| |\__ \| |__  / ^ \ |  ´ /  | Polymake and Singular
 \___/ \___/ \___//_/ \_\|_|\_\  | Type "?Oscar" for more information
o--------o-----o-----o--------o  | Documentation: https://docs.oscar-system.org/
  S Y M B O L I C   T O O L S    | 1.5.0-DEV #master 5a7f677 2025-08-12

julia> wp = oscar_worker_pool(1);

julia> Qx, x = QQ["x"];

julia> @time pmap(f -> begin; println(f); order(class_group(maximal_order(number_field(f; cached = false)[1]))[1]) end, wp, [x^2 + d for d in PrimesSet(100000, 110110)]); # this works

julia> @time pmap(f -> begin; println(f); order(class_group(maximal_order(number_field(f; cached = false)[1]))[1]) end, wp, [x^2 + d for d in PrimesSet(100000, 110110)]); # this gets stuck
```
Pinging @antonydellavecchia (thanks!)

P.S.: Full information on the system:
```
julia> Oscar.versioninfo(;full=true)
OSCAR version 1.5.0-DEV - #master, 5a7f6770ce -- 2025-08-12 13:37:36 +0200
  combining:
    AbstractAlgebra.jl   v0.46.2
    GAP.jl               v0.14.2
    Hecke.jl             v0.37.4
    Nemo.jl              v0.51.1
    Polymake.jl          v0.13.0
    Singular.jl          v0.25.7
  building on:
    FLINT_jll                  v301.300.101+0
    GAP_jll                    v400.1400.5+2
    GAP_lib_jll                v400.1400.5+0
    Singular_jll               v404.100.301+0
    libpolymake_julia_jll      v0.14.0+0
    libsingular_julia_jll      v0.47.5+1
    polymake_jll               v400.1400.0+0
    polymake_oscarnumber_jll   v0.3.9+0
See `]st -m` for a full list of dependencies.

Julia Version 1.12.0-rc1
Commit 228edd6610b (2025-07-12 20:11 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m3)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 4 virtual cores)
Official https://julialang.org release
```

Backtrace when `ctrl-c`:
```
^CERROR: InterruptException:
Stacktrace:
  [1] poptask(W::Base.IntrusiveLinkedListSynchronized{Task})
    @ Base ./task.jl:1187
  [2] wait()
    @ Base ./task.jl:1199
  [3] wait(c::Base.GenericCondition{ReentrantLock}; first::Bool)
    @ Base ./condition.jl:141
  [4] wait
    @ ./condition.jl:136 [inlined]
  [5] take_buffered(c::Channel{Any})
    @ Base ./channels.jl:532
  [6] take!(c::Channel{Any})
    @ Base ./channels.jl:526
  [7] take!(::Distributed.RemoteValue)
    @ Distributed ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/remotecall.jl:726
  [8] remotecall_fetch(::Function, ::Distributed.Worker, ::Distributed.RRID, ::Vararg{Any}; kwargs::@Kwargs{})
    @ Distributed ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/remotecall.jl:461
  [9] remotecall_fetch(::Function, ::Distributed.Worker, ::Distributed.RRID, ::Vararg{Any})
    @ Distributed ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/remotecall.jl:454
 [10] remotecall_fetch
    @ ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/remotecall.jl:492 [inlined]
 [11] call_on_owner
    @ ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/remotecall.jl:565 [inlined]
 [12] put!
    @ ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/remotecall.jl:722 [inlined]
 [13] put_type_params
    @ ~/.julia/dev/Oscar/src/Serialization/parallel.jl:35 [inlined]
 [14] put_type_params
    @ ~/.julia/dev/Oscar/src/Serialization/parallel.jl:16 [inlined]
 [15] put_type_params
    @ ~/.julia/dev/Oscar/src/Serialization/parallel.jl:37 [inlined]
 [16] remotecall_fetch(f::Function, wp::Oscar.OscarWorkerPool, args::QQPolyRingElem; kwargs::@Kwargs{})
    @ Oscar ~/.julia/dev/Oscar/experimental/Parallel/src/Parallel.jl:248
 [17] remotecall_fetch
    @ ~/.julia/dev/Oscar/experimental/Parallel/src/Parallel.jl:245 [inlined]
 [18] #remote##4
    @ ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/workerpool.jl:321 [inlined]
 [19] (::Base.var"#934#935"{Distributed.var"#remote##4#remote##5"{…}})(r::Base.RefValue{Any}, args::Tuple{QQPolyRingElem})
    @ Base ./asyncmap.jl:96
 [20] (::Base.var"#start_worker_task!##0#start_worker_task!##1"{Base.var"#934#935"{…}, Channel{…}, Nothing})()
    @ Base ./asyncmap.jl:230
Stacktrace:
  [1] (::Base.var"#maptwice##0#maptwice##1")(x::Task)
    @ Base ./asyncmap.jl:173
  [2] foreach(f::Base.var"#maptwice##0#maptwice##1", itr::Vector{Any})
    @ Base ./abstractarray.jl:3188
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::Vector{QQPolyRingElem})
    @ Base ./asyncmap.jl:173
  [4] wrap_n_exec_twice
    @ ./asyncmap.jl:149 [inlined]
  [5] #async_usemap#920
    @ ./asyncmap.jl:99 [inlined]
  [6] async_usemap
    @ ./asyncmap.jl:80 [inlined]
  [7] #asyncmap#919
    @ ./asyncmap.jl:77 [inlined]
  [8] asyncmap
    @ ./asyncmap.jl:76 [inlined]
  [9] pmap(f::Function, p::Oscar.OscarWorkerPool, c::Vector{…}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Vector{…}, retry_check::Nothing)
    @ Distributed ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/pmap.jl:126
 [10] pmap(f::Function, p::Oscar.OscarWorkerPool, c::Vector{QQPolyRingElem})
    @ Distributed ~/.julia/juliaup/julia-1.12.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.12/Distributed/src/pmap.jl:99
 [11] macro expansion
    @ ./timing.jl:645 [inlined]
 [12] top-level scope
    @ ./REPL[4]:1
```

### PR DESCRIPTION
**Pull request by antonydellavecchia**
closes #5218

### CODE REVIEW

File: experimental/Parallel/src/Parallel.jl [hunk 1]
```diff
@@ -244,6 +244,9 @@ end
 
 function remotecall_fetch(f::Any, wp::OscarWorkerPool, args...; kwargs...)
   wid = take!(wp)
+  # this is inefficient and can log up channels
```
Comment (antonydellavecchia) [inline experimental/Parallel/src/Parallel.jl]:
```suggestion
  # this is inefficient and can clog up channels
```

File: experimental/Parallel/src/Parallel.jl [hunk 2]
```diff
@@ -255,4 +258,9 @@ function remotecall_fetch(f::Any, wp::OscarWorkerPool, args...; kwargs...)
   return result
 end
 
+function pmap(f::Any, wp::OscarWorkerPool, c)
+  put_type_params(wp, c)
+  pmap(f, wp.wp, c)
+end
```
Comment (HechtiDerLachs) [inline experimental/Parallel/src/Parallel.jl:264]: Do I understand this correctly: Before, we did not overwrite `pmap` for this signature. With this new method, we send the parent objects once up front and then dispatch to `pmap` for an "ordinary" worker pool? 

Your comment suggests that the phenomenon observed was once again clogging of the buffers? Sorry, but I did not get around trying this example myself. If so, then I think we should really look into this. But for the meantime, this is a reasonable fix and improvement. Thanks!

**Review by HechtiDerLachs — APPROVED** [review]

File: experimental/Parallel/src/Parallel.jl (hunk 2 above)
Comment (antonydellavecchia) [reply experimental/Parallel/src/Parallel.jl:264]: yes exactly. The issue is in the remotecall_fetch, this is called by pmap and dispatched on the type of worker pool.
Since we wanted our remotecall_fetch to work on it's own, we send the parameters for the arguments without knowing if they are already there or not.
