### PR TITLE
hilbert series via Singular.hilbert_series_data

### LINKED ISSUE #2411: Integer overflow when computing Hilbert polynomial and degree
**Describe the bug**
When computing the degree of a graded algebra one might experience unexpected behaviour due to an integer overflow error in the computation of the Hilbert polynomial.

**To Reproduce**
```
using Oscar

A, x = graded_polynomial_ring(QQ, ["x$i" for i in 1:37])
I = ideal([2*x[11] - 2*x[17] - 2*x[24] + 2*x[32] - 111916*x[37], 2*x[4] - 2*x[8] - 2*x[26] + 2*x[34] - 41216*x[37], 2*x[2] - 2*x[9] - 2*x[20] + 2*x[35] + 37974*x[37], x[28] - x[36], x[21] - x[36], x[27] - x[28] + x[33] + x[36], x[26] - x[27] - x[33] + x[34], x[20] - x[21] + x[35] + x[36], x[15] - x[21] - x[28] + x[36], x[10] - x[36], x[25] - x[28] + x[31] + x[36], x[24] - x[25] - x[26] + x[27] - x[31] + x[32] + x[33] - x[34], -x[14] + x[15] + x[18] - x[21] + x[25] - x[28] + x[31] + x[36], x[13] - x[14] + x[18] - x[19] - 2*x[20] + 2*x[21] - x[26] + x[27] + x[33] - x[34] - 2*x[35] - 2*x[36], x[9] - x[10] + x[35] + x[36], x[6] - x[10] - x[28] + x[36], x[19] - x[21] + x[30] + x[36], -x[18] + x[19] + x[23] - x[25] - x[27] + x[28] + x[30] - x[31] - x[33] - x[36], x[17] - x[19] - x[30] + x[32], x[12] - x[14] - x[17] + x[18] - x[27] + x[28] + x[31] - x[32] - x[33] - x[36], x[8] - x[10] + x[34] + x[36], x[5] - x[6] - x[8] + x[10] - x[27] + x[28] - x[34] - x[36], x[3] - x[10] - x[21] + x[36], -x[18] + x[19] + x[20] - x[21] + x[29] + x[30] + x[35] + x[36], x[22] + x[23] + x[24] - x[25] - x[29] - x[30] - x[31] + x[32], x[16] + x[17] + x[18] - x[19] - x[22] - x[23] - x[24] + x[25], x[11] + x[12] + x[13] - x[14] - x[16] - x[17] - x[18] + x[19] + x[22] + x[23] + x[24] - x[25] + x[29] + x[30] + x[31] - x[32], x[7] + x[8] + x[9] - x[10] - x[33] + x[34] + x[35] + x[36], x[4] + x[5] + x[9] - x[10] + x[26] - x[27] + x[35] + x[36], x[2] + x[3] + x[9] - x[10] + x[20] - x[21] + x[35] + x[36], x[1] - x[3] - x[6] + x[10] - x[15] + x[21] + x[28] - x[36], -x[27]*x[36] + x[34]*x[35], -x[25]*x[36] + x[32]*x[35], x[14]*x[36] + x[19]*x[35] + x[25]*x[36] + x[27]*x[36] - x[32]*x[35] - x[34]*x[35], -x[19]*x[36] - x[25]*x[36] + x[32]*x[34] + x[32]*x[35], -x[19]*x[35] - x[19]*x[36] + x[25]*x[34] - x[25]*x[36] + x[32]*x[34] + x[32]*x[35], x[14]*x[36] - x[19]*x[35] + x[25]*x[34] + x[27]*x[32], x[14]*x[35] - x[14]*x[36] + x[19]*x[35] - x[19]*x[36] + x[25]*x[27] - x[25]*x[34] - x[27]*x[32] + x[32]*x[34], x[14]*x[34] + x[19]*x[27] - 2*x[19]*x[35] + 2*x[25]*x[34] - x[25]*x[36] + x[32]*x[35], x[14]*x[32] - 2*x[14]*x[36] + x[19]*x[25] - 2*x[19]*x[35] - x[27]*x[36] + x[34]*x[35]])
Q, _ = quo(A, I)
hilbert_polynomial(Q)
degree(Q)
```

Oscars computes the degree to be 34359738368.

**Expected behavior**
The actual degree (as confirmed by Macaulay2) is 6. Most likely there is an integer overflow in the denominator of the leading coefficient of the Hilbert polynomial as this coefficient is deg/35!.

**System:**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.11.3
  combining:
    AbstractAlgebra.jl   v0.27.10
    GAP.jl               v0.9.4
    Hecke.jl             v0.17.5
    Nemo.jl              v0.32.7
    Polymake.jl          v0.9.0
    Singular.jl          v0.16.1
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.5+0
    GAP_jll                 v400.1200.200+0
    Singular_jll            v403.101.500+0
    libpolymake_julia_jll   v0.9.0+0
    libsingular_julia_jll   v0.29.0+0
    polymake_jll            v400.900.0+0
See `]st -m` for a full list of dependencies.

Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Official https://julialang.org/ release
...
```

**Additional information**
It was pointed out by Matthias Zach that this error probably comes from Singular.

### PR DESCRIPTION
**Pull request by hannes14**
Resolves #2411

### CODE REVIEW

**Comment by lgoettgens** [comment]
Would it make sense to include the offending example from https://github.com/oscar-system/Oscar.jl/issues/2411#issue-1724096598 as a test to prevent future regressions?

File: test/Rings/hilbert.jl [hunk 1]
```diff
@@ -122,3 +122,13 @@ end
   @test_throws ArgumentError  hilbert_series(RmodI);  # weights must be non-neg
   @test_throws ArgumentError  multi_hilbert_series(RmodI); # possible infinite dimension
 end
+
+@testset "Hilbert series part 4" begin
+  A, x = graded_polynomial_ring(QQ, ["x$i" for i in 1:37])
```
Comment (fingolfin) [inline test/Rings/hilbert.jl:129]:
```suggestion
  # This test verifies that an intermediate overflow that was reported in
  # https://github.com/oscar-system/Oscar.jl/issues/2411 is fixed.
  A, x = graded_polynomial_ring(QQ, ["x$i" for i in 1:37])
```

**Review by fingolfin — APPROVED** [review]
