### PR TITLE
fix: product of polyhedra with lineality

### LINKED ISSUE #5370: *(::Polyhedron,::Polyhedron) only works for pointed polyhedra
I was trying to construct the cartesian product $\sigma \times \mathbb{R}$, where $\sigma$ is a given polyhedron, and ran into an error.  Here a MWE:

```
c = cube(2)
L = convex_hull([[0]], nothing, [[1]])
c*L # error here
```

And here the error:
```
julia> c*L
ERROR: product: input polyhedron not pointed at -e line 0.

Stacktrace:
  [1] internal_call_function(arg1::String, arg2::CxxWrap.StdLib.StdVectorAllocated{…}, arg3::Vector{…})
    @ Polymake.LibPolymake ~/.julia/packages/CxxWrap/ZPNvc/src/CxxWrap.jl:715
  [2] (::Polymake.var"#44#45"{Symbol, CxxWrap.StdLib.StdVectorAllocated{CxxWrap.StdLib.StdString}, Vector{Any}, String})()
    @ Polymake ~/.julia/packages/Polymake/3ALS3/src/call_function.jl:24
  [3] disable_sigint
    @ ./c.jl:167 [inlined]
  [4] call_function(::Type{…}, ::Symbol, ::Symbol, ::Polymake.LibPolymake.BigObjectAllocated, ::Vararg{…}; template_parameters::Vector{…}, calltype::Symbol, kwargs::@Kwargs{})
    @ Polymake ~/.julia/packages/Polymake/3ALS3/src/call_function.jl:17
  [5] call_function(::Symbol, ::Symbol, ::Polymake.LibPolymake.BigObjectAllocated, ::Vararg{…}; template_parameters::Vector{…}, kwargs::@Kwargs{})
    @ Polymake ~/.julia/packages/Polymake/3ALS3/src/call_function.jl:31
  [6] Polymake.polytope.product(::Polymake.LibPolymake.BigObjectAllocated, ::Vararg{…}; template_parameters::Vector{…}, kwargs::@Kwargs{})
    @ Polymake.polytope ~/.julia/packages/Polymake/3ALS3/src/meta.jl:296
  [7] Polymake.polytope.product(::Polymake.LibPolymake.BigObjectAllocated, ::Vararg{Polymake.LibPolymake.BigObjectAllocated})
    @ Polymake.polytope ~/.julia/packages/Polymake/3ALS3/src/meta.jl:293
  [8] product(P::Polyhedron{QQFieldElem}, Q::Polyhedron{QQFieldElem})
    @ Oscar ~/.julia/dev/Oscar/src/PolyhedralGeometry/Polyhedron/standard_constructions.jl:414
  [9] *(P::Polyhedron{QQFieldElem}, Q::Polyhedron{QQFieldElem})
    @ Oscar ~/.julia/dev/Oscar/src/PolyhedralGeometry/Polyhedron/standard_constructions.jl:435
 [10] top-level scope
    @ REPL[17]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by YueRen**
This is a quick julia-side fix for https://github.com/oscar-system/Oscar.jl/issues/5370

There are probably more efficient ways to implement it in polymake proper (especially when the polyhedra are given in H representation).

### CODE REVIEW

**Comment by YueRen** [comment]
@lkastner @benlorenz Would one of you be so kind to review it?  There are still some tests failing, but I'm not sure that's because of my changes.

**Comment by benlorenz** [comment]
I think you will need to use oscar matrices (e.g. `zero_matrix` with `coefficient_field(P)` as first argument) instead of julia matrices (`zeros` with just a type).

**Comment by YueRen** [comment]
> I think you will need to use oscar matrices (e.g. `zero_matrix` with `coefficient_field(P)` as first argument) instead of julia matrices (`zeros` with just a type).

Ah, I wasn't aware of `coefficient_field`, thanks!  It is amended now.

File: src/PolyhedralGeometry/Polyhedron/standard_constructions.jl [hunk 1]
```diff
@@ -411,8 +411,32 @@ julia> length(vertices(product(T,S)))
...
+  Pmod, LP = peel_lineality(P)
+  Qmod, LQ = peel_lineality(Q)
+  PQmod = product(Pmod, Qmod)
+  K = coefficient_field(PQmod)
+
+  # Construct the product of the linealities
+  n = ambient_dim(P)
+  m = ambient_dim(Q)
+  LPQ = vcat(Vector{elem_type(K)}[vcat(lp, zeros(elem_type(K), m)) for lp in LP],
+    Vector{elem_type(K)}[vcat(zeros(elem_type(K), n), lq) for lq in LQ])
```
Comment (benlorenz) [inline src/PolyhedralGeometry/Polyhedron/standard_constructions.jl]:
```suggestion
  LPQ = block_diagonal_matrix([matrix(K, LP), matrix(K, LQ)])
```
I think this should work.

File: src/PolyhedralGeometry/Polyhedron/standard_constructions.jl [hunk 2]
```diff
@@ -411,8 +411,31 @@ julia> length(vertices(product(T,S)))
...
+  Pmod, LP = peel_lineality(P)
+  Qmod, LQ = peel_lineality(Q)
+  PQmod = product(Pmod, Qmod)
+  K = coefficient_field(PQmod)
+
+  # Construct the product of the linealities
+  n = ambient_dim(P)
+  m = ambient_dim(Q)
+  LPQ = block_diagonal_matrix([matrix(K, LP), matrix(K, LQ)])
+  PQlin = convex_hull(zero_matrix(K, 1, n + m), zero_matrix(K, 0, n + m), LPQ)
```
Comment (benlorenz) [inline src/PolyhedralGeometry/Polyhedron/standard_constructions.jl]:
```suggestion
  PQlin = convex_hull(zero_matrix(K, 1, n + m), zero_matrix(K, 0, n + m), LPQ; non_redundant=true)
```
These should be non-redundant.

File: src/PolyhedralGeometry/Polyhedron/standard_constructions.jl [hunk 3]
```diff
@@ -411,8 +411,31 @@ julia> length(vertices(product(T,S)))
...
+
+  return PQmod + PQlin
+end
+
+function peel_lineality(P::Polyhedron)
+  V, L = minimal_faces(P)
+  R, _ = rays_modulo_lineality(P)
+  Q = convex_hull(V, R)
```
Comment (benlorenz) [inline src/PolyhedralGeometry/Polyhedron/standard_constructions.jl]:
```suggestion
  Q = convex_hull(V, R; non_redundant=true)
```
Also non-redundant.

File: test/PolyhedralGeometry/polyhedron.jl [hunk 4]
```diff
@@ -88,6 +88,7 @@
     @test intersect(Ps...) == Q0
     @test minkowski_sum(Q0, Q0) == convex_hull(f, 2 * pts)
     @test Q0 + Q0 == minkowski_sum(Q0, Q0)
+    @test Q1 * Q2 == product(Q1, Q2)
```
Comment (benlorenz) [inline test/PolyhedralGeometry/polyhedron.jl:91]: This only checks the function against itself and that `*` is defined. But it does not check the result, maybe add a few more examples and verify lineality and combinatorial dimensions.

Comment (YueRen) [reply test/PolyhedralGeometry/polyhedron.jl:91]: @benlorenz I've added the tests.  I didn't know where to put them in the existing `@testset` blocks, so I just started a new one.

**Review by benlorenz — APPROVED** [review]
