### PR TITLE
Change `is_skewsymmetric_matrix` to `is_alternating`

### LINKED ISSUE #2555: Two different skew-symmetry checks
**Describe the bug**
We have two different implementations for skew symmetry checks of a `MatElem`: 
```julia
julia> methods(is_skew_symmetric)
# 1 method for generic function "is_skew_symmetric" from AbstractAlgebra:
 [1] is_skew_symmetric(M::MatElem)
     @ ~/path/AbstractAlgebra.jl/src/Matrix.jl:2403

julia> methods(is_skewsymmetric_matrix)
# 1 method for generic function "is_skewsymmetric_matrix" from Oscar:
 [1] is_skewsymmetric_matrix(B::MatElem{T}) where T<:RingElem
     @ ~/path/Oscar.jl/src/Groups/matrices/matrix_manipulation.jl:171
```

As far as I can tell, the implementations differ in the behavior in characteristic 2, and the latter imposes a restriction on the element type of the matrices.

It would be great to have only one function doing that and not two. Similar functions would be named `is_skew_symmetric` (without `matrix`), so I would like that name here.

Can somebody with knowledge about the use-cases say a few words about the characteristic 2 stuff, so that we can decide, which version to keep? In all cases, this should probably go into AbstractAlgebra.

### PR DESCRIPTION
**Pull request by lgoettgens**
Resolves https://github.com/oscar-system/Oscar.jl/issues/2555.

I renamed `is_skewsymmetric_matrix` to `is_alternating`, and updated all uses accordingly. In one test, there was a natural place to test that this indeed differs from `is_skew_symmetric` in characteristic 2.

### CODE REVIEW

File: src/deprecations.jl [hunk 1]
```diff
@@ -394,5 +394,8 @@ function SubdivisionOfPoints{T}(obj::Polymake.BigObject) where T<:scalar_types
   return SubdivisionOfPoints{T}(obj, _detect_default_field(T, obj))
 end
 
+@deprecate is_skewsymmetric_matrix(B::MatElem{T}) where T <: RingElem is_alternating(B)
+@alias isskewsymmetric_matrix is_skewsymmetric_matrix
+
```
Comment (lgoettgens) [inline src/deprecations.jl]: Do we really want this deprecation? I find it very misleading from its name. As the next release will be breaking anyway, we could skip adding it.

Comment (fingolfin) [reply src/deprecations.jl]: I am happy with omitting it

**Review by fingolfin — APPROVED** [review]
