### PR TITLE
Fix #4039

### LINKED ISSUE #4039: `absolute_primary_decomposition` fails for unit ideals
The expected behaviour when running `absolute_primary_decomposition` for the unit ideal is to get an empty vector back, like this:

```
julia> R, (x,y) = polynomial_ring(QQ,["x","y"])
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x, y])

julia> I = ideal([R(1)])
Ideal generated by
  1

julia> absolute_primary_decomposition(I)
Tuple{MPolyIdeal{QQMPolyRingElem}, MPolyIdeal{QQMPolyRingElem}, MPolyIdeal{AbstractAlgebra.Generic.MPoly{AbsSimpleNumFieldElem}}, Int64}[] 
```

However, for many cases where you have a unit ideal that is not just defined by 1, something seems to go wrong in the interface between Julia and Singular. For instance:

```
julia> R, (x,y) = polynomial_ring(QQ,["x","y"])
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x, y])

julia> I = ideal([x+1,y+1,y])
Ideal generated by
  x + 1
  y + 1
  y

julia> absolute_primary_decomposition(I)
   skipping text from `)` error at token `)`
ERROR: `string`(@newvar) = `poly` is not supported
expected `string` = `string`
error occurred in or before primdec.lib::absPrimdecGTZ_i line 5840: `  string @newvar=@L[1][3];`
expected string-expression. type 'help string;'
leaving primdec.lib::absPrimdecGTZ_i (5835)

Stacktrace:
 [1] call_singular_library_procedure
   @ ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:624 [inlined]
 [2] low_level_caller_rng(lib::String, name::String, ring::Singular.PolyRing{…}, args::Singular.sideal{…})
   @ Singular ~/.julia/packages/Singular/A4riV/src/caller.jl:379
 [3] absPrimdecGTZ(ring::Singular.PolyRing{Singular.n_Q}, args::Singular.sideal{Singular.spoly{Singular.n_Q}})
   @ Singular.LibPrimdec ~/.julia/packages/Singular/A4riV/src/Meta.jl:45
 [4] __compute_absolute_primary_decomposition__(I::MPolyIdeal{QQMPolyRingElem})
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly-ideals.jl:906
 [5] #336
   @ ~/.julia/packages/AbstractAlgebra/tABFQ/src/Attributes.jl:357 [inlined]
 [6] get!(default::Oscar.var"#336#339"{MPolyIdeal{QQMPolyRingElem}}, h::Dict{Symbol, Any}, key::Symbol)
   @ Base ./dict.jl:479
 [7] get_attribute!
   @ ~/.julia/packages/AbstractAlgebra/tABFQ/src/Attributes.jl:230 [inlined]
 [8] absolute_primary_decomposition(I::MPolyIdeal{QQMPolyRingElem})
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly-ideals.jl:901
 [9] top-level scope
   @ REPL[17]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

More specifically, the error seems to occur in line [906](https://github.com/oscar-system/Oscar.jl/blob/a7e41881932a031ac778b6a7abc7d5999954bcd6/src/Rings/mpoly-ideals.jl#L906) of `mpoly-ideals.jl`, where `absPrimdecGTZ` is run:

```
julia> Singular.LibPrimdec.absPrimdecGTZ(Oscar.singular_polynomial_ring(I), Oscar.singular_generators(I))¨
   skipping text from `)` error at token `)`
ERROR: `string`(@newvar) = `poly` is not supported
expected `string` = `string`
error occurred in or before primdec.lib::absPrimdecGTZ_i line 5840: `  string @newvar=@L[1][3];`
expected string-expression. type 'help string;'
leaving primdec.lib::absPrimdecGTZ_i (5835)

Stacktrace:
 [1] call_singular_library_procedure
   @ ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:624 [inlined]
 [2] low_level_caller_rng(lib::String, name::String, ring::Singular.PolyRing{…}, args::Singular.sideal{…})
   @ Singular ~/.julia/packages/Singular/A4riV/src/caller.jl:379
 [3] absPrimdecGTZ(ring::Singular.PolyRing{Singular.n_Q}, args::Singular.sideal{Singular.spoly{Singular.n_Q}})
   @ Singular.LibPrimdec ~/.julia/packages/Singular/A4riV/src/Meta.jl:45
 [4] top-level scope
   @ REPL[48]:1
Some type information was truncated. Use `show(err)` to see complete types.

```

This bug was discovered together with @nachogm97.

### PR DESCRIPTION
**Pull request by joschmitt**
The fix for the Singular bug in #4039 arrived in OSCAR with the latest Singular.jll

This closes #4039 by handling the empty dictionary that is now returned by Singular in the example.

### CODE REVIEW

File: src/Rings/mpoly-ideals.jl [hunk 1]
```diff
@@ -898,19 +898,24 @@ Multivariate polynomial ring in 2 variables over number field graded by
   y -> [1]
 ```
 """
-@attr function absolute_primary_decomposition(I::MPolyIdeal{<:MPolyRingElem{QQFieldElem}})
+@attr Vector{Tuple{typeof(I), typeof(I), ideal_type(change_base_ring(rationals_as_number_field()[1], base_ring(I))[1]), Int64}} function absolute_primary_decomposition(I::MPolyIdeal{<:MPolyRingElem{QQFieldElem}})
```
Comment (joschmitt) [inline src/Rings/mpoly-ideals.jl:901]: I gave my best to get this function type stable. If anyone knows a better way to infer the return type, please speak up.

Comment (lgoettgens) [reply src/Rings/mpoly-ideals.jl:901]: Since the RK can either be `AbstractAlgebra.Generic.MPolyRing{AbsSimpleNumFieldElem}` or `MPolyDecRing{AbsSimpleNumFieldElem, AbstractAlgebra.Generic.MPolyRing{AbsSimpleNumFieldElem}}`, depending on if `base_ring(I)` is graded, this seems to be the straightforward way of resolving this. The only other idea in my head would be adding an extra dispatch for `I::MPolyIdeal{<:MPolyDecRing{QQFieldElem}}`, but this would imply a lot of code duplication

**Review by afkafkafk13 — APPROVED** [review]
I am not @hannes14 , but the bug fix covers precisely the corner cases and does the job.
