### PR TITLE
Normal form checks for msolve compatibility

### LINKED ISSUE #3665: Normal form fails for ideals in GF(2)(t)[x,y]
**Describe the bug**
Normal form throws an error

**To Reproduce**
```
julia> k = GF(2)
Prime field of characteristic 2

julia> kt,t = polynomial_ring(k,:t)
(Univariate polynomial ring in t over GF(2), t)

julia> Ft = fraction_field(kt)
Fraction field
  of univariate polynomial ring in t over GF(2)

julia> P,(x,y) = polynomial_ring(Ft,[:x,:y])
(Multivariate polynomial ring in 2 variables over fraction field, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}[x, y])

julia> I = ideal(P,[x,y])
Ideal generated by
  x
  y

julia> rational_point_coordinates(I)
ERROR: MethodError: no method matching degree(::AbstractAlgebra.Generic.FracField{FqPolyRingElem})

Closest candidates are:
  degree(::Type{Vector{Int64}}, ::MPolyDecRingElem)
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly-graded.jl:941
  degree(::Type{Vector{Int64}}, ::MPolyQuoRingElem{<:MPolyDecRingElem}; check)
   @ Oscar ~/.julia/dev/Oscar/src/Rings/MPolyQuo.jl:1390
  degree(::Type{Vector{Int64}}, ::Oscar.MPolyLocRingElem{<:Ring, <:RingElem, <:MPolyDecRing}; check)
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly-localizations.jl:2807
  ...

Stacktrace:
  [1] _convert_to_msolve(F::Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}})
    @ AlgebraicSolving ~/.julia/packages/AlgebraicSolving/mMBHd/src/interfaces/nemo.jl:21
  [2] _core_normal_form(F::Vector{…}, I::AlgebraicSolving.Ideal{…}; nr_thrds::Int64, info_level::Int64)
    @ AlgebraicSolving ~/.julia/packages/AlgebraicSolving/mMBHd/src/algorithms/normal-forms.jl:141
  [3] _core_normal_form
    @ ~/.julia/packages/AlgebraicSolving/mMBHd/src/algorithms/normal-forms.jl:102 [inlined]
  [4] #normal_form#7
    @ ~/.julia/packages/AlgebraicSolving/mMBHd/src/algorithms/normal-forms.jl:99 [inlined]
  [5] normal_form
    @ ~/.julia/packages/AlgebraicSolving/mMBHd/src/algorithms/normal-forms.jl:93 [inlined]
  [6] _normal_form_f4(A::Vector{AbstractAlgebra.Generic.MPoly{…}}, J::MPolyIdeal{AbstractAlgebra.Generic.MPoly{…}})
    @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:1116
  [7] normal_form(A::Vector{…}, J::MPolyIdeal{…}; ordering::MonomialOrdering{…})
    @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:1064
  [8] normal_form
    @ ~/.julia/dev/Oscar/src/Rings/groebner.jl:1061 [inlined]
  [9] normal_form(f::AbstractAlgebra.Generic.MPoly{…}, J::MPolyIdeal{…}; ordering::MonomialOrdering{…})
    @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:1056
 [10] normal_form(f::AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.FracFieldElem{…}}, J::MPolyIdeal{AbstractAlgebra.Generic.MPoly{…}})
    @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:1055
 [11] #7484
    @ ./none:0 [inlined]
 [12] iterate
    @ ./generator.jl:47 [inlined]
 [13] collect(itr::Base.Generator{Vector{AbstractAlgebra.Generic.MPoly{…}}, Oscar.var"#7484#7486"{MPolyIdeal{…}}})
    @ Base ./array.jl:834
 [14] rational_point_coordinates(I::MPolyIdeal{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.FracFieldElem{FqPolyRingElem}}})
    @ Oscar ~/.julia/dev/Oscar/experimental/Schemes/SpaceGerms.jl:344
 [15] top-level scope
    @ REPL[1107]:1
Some type information was truncated. Use `show(err)` to see complete types.

```

**Expected behavior**
Should compute a normal form

**System (please complete the following information):**
Please paste the output of `Oscar.versioninfo(full=true)` below. If this does
not work, please paste the output of Julia's `versioninfo()` and your Oscar
version.
```
julia> Oscar.versioninfo(full=true)
OSCAR version 1.1.0-DEV - #sb/elliptic_surface_tests, fbf2b2e87b -- 2024-04-30 17:03:38 +0200
  combining:
    AbstractAlgebra.jl   v0.40.9
    GAP.jl               v0.10.3
    Hecke.jl             v0.30.10 - #master, 80487317d2 -- 2024-04-23 22:14:48 +0200
    Nemo.jl              v0.43.3
    Polymake.jl          v0.11.15
    Singular.jl          v0.22.6
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.9+0
    GAP_jll                 v400.1200.200+9
    Singular_jll            v403.216.1602+0
    libpolymake_julia_jll   v0.11.4+0
    libsingular_julia_jll   v0.44.2+0
    polymake_jll            v400.1100.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 13th Gen Intel(R) Core(TM) i7-1370P
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 15 default, 0 interactive, 1 GC (on 20 virtual cores)
Environment:
  JULIA_NUM_GC_THREADS = 1
  JULIA_NUM_THREADS = 15
Official https://julialang.org/ release

...
```

@ederc  @afkafkafk13

### PR DESCRIPTION
**Pull request by ederc**
Fixes checks in `normal_form` when `msolve` is applicable.

This fixes #3665.

### CODE REVIEW

File: src/Rings/groebner.jl [hunk 1]
```diff
@@ -1060,7 +1060,7 @@ end
 
 function normal_form(A::Vector{T}, J::MPolyIdeal; ordering::MonomialOrdering=default_ordering(base_ring(J))) where { T <: MPolyRingElem }
   @req is_exact_type(elem_type(base_ring(J))) "This functionality is only supported over exact fields."
-  if ordering == degrevlex(base_ring(J)) && is_prime(characteristic(base_ring(J)))
+  if ordering == degrevlex(base_ring(J)) && typeof(base_ring(J)) == FqField && prime_field(base_ring(J)) == base_ring(J)
```
Comment (thofma) [inline src/Rings/groebner.jl]:
```suggestion
  if ordering == degrevlex(base_ring(J)) && typeof(base_ring(J)) == FqField && absolute_degree(base_ring(J)) == 1
```

Comment (thofma) [reply src/Rings/groebner.jl]: (Should we have a method `is_prime_field(F)`?)

Comment (ederc) [reply src/Rings/groebner.jl]: Would make tests for situations where msolve is applicable easier. But if that's the only use case, maybe it's not worth the effort.

**Review by thofma — APPROVED** [review]

**Comment by thofma** [comment]
At some point it might be a good idea to refactor this using an `_is_msolve_applicable` helper.
