### PR TITLE
Fix `f_vector` for cones with lineality (and the point)

### LINKED ISSUE #5714: f-vector of cone with lineality space computed incorrectly
If `C` is, say, a `Cone{QQFieldElem}` with positive lineality dimension `ldim`, then `f_vector(C)[ldim]` will be `0` but should be `1` (cf. [docs](https://docs.oscar-system.org/dev/PolyhedralGeometry/cones/#f_vector-Tuple%7BCone%7D)). This happens because the [polymake f-vector is prepended with `fill(0, ldim)`](https://github.com/oscar-system/Oscar.jl/blob/b46adfdacdd4ace1995b25dc729b59894f9e3f5d/src/PolyhedralGeometry/Cone/properties.jl#L343) instead of `==(ldim).(1:ldim)` or the like. 

Example:
```
C = positive_hull([1 0 0; 0 1 0], [0 0 1]); f_vector(C)
2-element Vector{ZZRingElem}:
 0
 2
```
but for the same cone constructed as a `Polyhedron{QQFieldElem}`:
```
P = polyhedron([-1 0 0; 0 -1 0], [0, 0]); f_vector(P)
3-element Vector{ZZRingElem}:
 0
 1
 2
```
By convention, `f_vector(C)` starts with $f_1$ while `f_vector(P)` starts with $f_0$, so `f_vector(C)[1]` should equal `f_vector(P)[2]`.

### PR DESCRIPTION
**Pull request by imkhln**
This resolves https://github.com/oscar-system/Oscar.jl/issues/5714.

I have no permission to assign but @lkastner this one's for you.

### CODE REVIEW

File: src/PolyhedralGeometry/Cone/properties.jl [hunk 1]
```diff
@@ -339,8 +339,14 @@ julia> f_vector(square)
 """
 function f_vector(C::Cone)
   pmc = pm_object(C)
-  ldim = pmc.LINEALITY_DIM
-  return Vector{ZZRingElem}(vcat(fill(0, ldim), pmc.F_VECTOR))
+  ld = pmc.LINEALITY_DIM
+  fv = ld == pmc.CONE_DIM ? ZZRingElem[] : pmc.F_VECTOR
```
Comment (benlorenz) [inline src/PolyhedralGeometry/Cone/properties.jl]:
```suggestion
  ld = lineality_dim(C)
  fv = ld == dim(C) ? ZZRingElem[] : pmc.F_VECTOR::Polymake.Vector{Polymake.Integer}
```
I recommend adding type assertions for polymake properties because julia cannot deduce the return type and also use the existing methods where possible.

**Review by benlorenz — COMMENTED** [review]
Looks like the tests are also wrong, Cone2 should indeed have `[1,2]` and not `[0,2]`.

File: src/PolyhedralGeometry/Cone/properties.jl (hunk 1 above)
Comment (imkhln) [reply src/PolyhedralGeometry/Cone/properties.jl]: Done.

**Review by benlorenz — APPROVED** [review]
